### PR TITLE
Issue 328.  TextString support for Solr.

### PR DESCRIPTION
**Pull request by holleyism**
Signed-off-by: Adam Holley <git@holleyism.com>
Issue #328 

This is the new pull request to replace pull 713.

### CODE REVIEW

**Comment by pluradj** [comment]
@holleyism Can you update the initial comment on this PR to include the PR checklist template?

**Comment by pluradj** [comment]
@holleyism I'm hitting the same errors as Travis on my local build.
```
Running org.janusgraph.diskstorage.solr.BerkeleySolrTest
Tests run: 28, Failures: 2, Errors: 0, Skipped: 1, Time elapsed: 384.93 sec <<< FAILURE! - in org.janusgraph.diskstorage.solr.BerkeleySolrTest
testListUpdate(org.janusgraph.diskstorage.solr.BerkeleySolrTest)  Time elapsed: 80.998 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.janusgraph.testutil.JanusGraphAssert.assertCount(JanusGraphAssert.java:42)
	at org.janusgraph.graphdb.JanusGraphIndexTest.testListUpdate(JanusGraphIndexTest.java:269)
        ...
```

**Comment by holleyism** [comment]
@pluradj. Yeah. I’m working through it. Think I’m close.

**Comment by pluradj** [comment]
any updates @holleyism?

**Comment by holleyism** [comment]
@pluradj I was making progress and then got stuck.  
This test is passing:
        query = new IndexQuery(store, PredicateCondition.of(STRING, Cmp.EQUAL, "Tom or Jerry"));
        assertEquals(query.toString(), 1, tx.queryStream(query).count());
This test is failing:
            query = new IndexQuery(store, PredicateCondition.of(FULL_TEXT, Cmp.EQUAL, "Tom or Jerry"));
            assertEquals(query.toString(), 1, tx.queryStream(query).count());

Which appears to be using the _t text index, but somethings off.

I'm still looking into it but have been fairly swamped for most of the year.  If you know any Solr experts that might be able to provide some insight, let me know.  Otherwise I'll keep looking.

**Comment by wojciechwojcik** [comment]
any updates @holleyism?

**Comment by farodin91** [comment]
@holleyism Do you like to rebase this PR on to of current master and try to fix current build failures?

**Comment by holleyism** [comment]
@farodin91 A simple rebase does not appear to fix this.  I think more changes are required because of the differences in Elasticsearch and Solr.  Unfortunately I am not currently allowed to work on this project.

**Pull request closed without merging**
