### PR TITLE
Rename docs from *.txt to *.adoc

### PR DESCRIPTION
**Pull request by mbrukman**
Partially addresses issue #615 (renames files); more work to be done to fully address the issue.

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [-] Is your initial contribution a single, squashed commit?
  No, it's easier to review file renames + updates via multiple commits.

### For code changes:
- [] Have you written and/or updated unit tests to verify your changes?
- [] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?
  Preview at https://mbrukman.github.io/docs.janusgraph.org/0.3.0-SNAPSHOT/index.html
- [x] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mbrukman** [comment]
Should this PR target `0.2` branch or `master`?

**Comment by robertdale** [comment]
I would prefer it targeted 0.2 otherwise it would have a slightly different release process. I think it's a worthy goal to keep them as close as possible.  See also https://github.com/JanusGraph/janusgraph/pull/730#issuecomment-346029203

**Comment by mbrukman** [comment]
@sjudeng wrote:

> A number of the files show up as deleted/added instead of moved. Can you try git mv on these if you haven't already? If you move files externally Git can often still figure it out but not in cases where there were significant changes to the moved file.
> 
> advanced.adoc
> index.adoc
> internals.adoc
> usefultools.adoc

I did use `git mv` to move them; note that this PR contains 4 separate commits (the move commit actually includes the `git mv` command used in a script to generate that commit). If you look specifically at the commit that moved files, you'll see they're all pure moves, and the edits happen in a separate commit. However, when you look at the overall diffs, GitHub appears to be glitchy in that some of the move + edit appear as as a unit, while others appears as a remove + add.

**Comment by mbrukman** [comment]
@robertdale — rebased PR onto `0.2` and updated the base branch.

**Comment by mbrukman** [comment]
@sjudeng — are you sure you want the commits squashed? I specifically kept them separate because doing so will lose the two separate changes which are the (a) move and the (b) renames, which makes the code harder to review retroactively. Having a merge with 4 commits is still atomic: they're all either present or not present on the branch, there's no way to see a state where some but not all of the commits are there.

That said, if you prefer, I'm happy to do that either manually (push a new single squashed commit), or as part of the merge (GitHub lets you squash + merge).

**Comment by sjudeng** [comment]
You can edit a renamed file in the same commit and still have a clean diff. I tested it squashing your commits (see [here](https://github.com/JanusGraph/janusgraph/compare/0.2...sjudeng:docs-rename-txt-to-adoc2)).

Thanks for the explanation on the renamed files, I missed there were multiple commits.

**Comment by mbrukman** [comment]
@sjudeng — are you OK if I squash the commits as part of the merge, as per suggestion from @amcp?

**Pull request merged**
