### PR TITLE
Remove coverity

### PR DESCRIPTION
**Pull request by farodin91**
Signed-off-by: Jan Jansen <jan.jansen@gdata.de>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mbrukman** [comment]
I _think_ Coverity does more than just code style, test coverage, etc. that Codacity does, e.g., I think it also included security issues and richer static analysis of potential problems, beyond just stylistic issues that I see showing up on PR reviews.

That said, I haven't compared Coverity and Codacy in great detail, and haven't looked at the Coverity report in a while, so if you have, and you believe you're not gaining much from it, it's your call.

**Comment by farodin91** [comment]
> I think Coverity does more than just code style, test coverage, etc. that Codacity does, e.g., I think it also included security issues and richer static analysis of potential problems, beyond just stylistic issues that I see showing up on PR reviews.

* Codacy directly comments on the PR which allows us to see problems directly. 
* Github provides already a really good security check for dependences
* Codecov does testcoverage for us also

All of these are executed automatically and coverity is justed executed on a special branch.

**Comment by porunov** [comment]
@farodin91 I've checked some reports from Coverity. I now see that some of those reports might be useful. For example, it detects unsynchronized singleton creation which might be unsafe in some situations (of course the logic should be checked to verify that).
I didn't find the same detected problems in Codacy. What I see, is that both analysis may be helpful (from Codacy and from Coverity).
I am not sure how the Coverity works. I see that the last time JanusGraph was analysed is in May 2019 (long time ago). I think it would be more helpful to just run analyse again for the `master` branch.

@mbrukman I see that @farodin91 isn't added as a member into Coverity. Would you be able to add him as a member? My invite button doesn't work in Coverity. Most likely I don't have necessary permissions to add new members.
Also, if you can, it would be useful to start `master` branch analyse by Coverity.

**Comment by farodin91** [comment]
@porunov I close this PR and we should open a issue to let this tool run on each master build.

**Comment by mbrukman** [comment]
@farodin91 wrote:
> @porunov I close this PR and we should open a issue to let this tool run on each master build.

Synopsys/Coverity don't want us to run a scan on every PR/build because it's very computationally expensive and they're providing this service to us for free.

https://scan.coverity.com/travis_ci says (emphasis mine):

> **It's probably overkill to run static analysis on each and every commit of your project.** To increase availability of the free service to more projects, the addon is designed by default to run analysis on a per-branch basis. We recommend you create a branch named `coverity_scan`, which you can merge into whenever you would like to trigger analysis.

This is the approach we're following—we should periodically update `coverity_scan` branch and push to it to trigger the build once in a while, to get the latest analysis results.

https://community.synopsys.com/s/article/Five-Common-Misconceptions-How-best-to-use-Coverity-to-detect-defects says (emphasis mine):

> **The scan frequency should be from one to seven days.** If the scan frequency is less than one day, there will be few new defects found with each scan due to the small number of changes in the code, which wastes Coverity resources.

**Pull request closed without merging**
