### PR TITLE
Remove Bigtable as tested compatibility

### LINKED ISSUE #3371: Remove Bigtable from list of tested compatibility versions
The changelog currently lists quite a few Bigtable versions under "Tested Compatibility": 
> Google Bigtable 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.14.0

but we have no automated tests for Bigtable: #415

I think we should remove Bigtable completely from the list under _tested compatibility_ until we have some automated tests for this backend in place. We might not even notice if we break compatibility with Bigtable right now.

We also don't list Scylla there for the same reason: #2451

### PR DESCRIPTION
**Pull request by FlorianHockmann**
Fixes #3371

We can add it back there as soon as we have some automated tests in place: #415

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Review by farodin91 — APPROVED** [review]

**Comment by rngcntr** [comment]
What about the previous versions? If I understand #415 correctly, we never had Bigtable tests in place. Right now, one may interpret the docs saying Bigtable was tested in 0.6.2 for example but we dropped support in 0.6.3. That could fool users into thinking they should opt for 0.6.2 when operating JanusGraph on Bigtable.

**Comment by FlorianHockmann** [comment]
> What about the previous versions? If I understand https://github.com/JanusGraph/janusgraph/issues/415 correctly, we never had Bigtable tests in place. Right now, one may interpret the docs saying Bigtable was tested in 0.6.2 for example but we dropped support in 0.6.3. That could fool users into thinking they should opt for 0.6.2 when operating JanusGraph on Bigtable.

That's a good point. The problem is however that these versions are already released and I think we should not modify past releases, including their release notes. We also distribute the docs as a zip archive for each release. So, if we modify the changelog of a past release then the online docs for that release will differ from the docs shipped with the release.

**Comment by farodin91** [comment]
We could upgrade instruction with the note that we are looking for help.

**Comment by rngcntr** [comment]
@FlorianHockmann As a first measure we could simply append a line in the changelog for the new versions stating that the tests have not been removed but rather never existed.

**Comment by FlorianHockmann** [comment]
> As a first measure we could simply append a line in the changelog for the new versions stating that the tests have not been removed but rather never existed.

I just updated the commit to include such a remark.

**Review by farodin91 — APPROVED** [review]

**Comment by FlorianHockmann** [comment]
> As an organization that uses JanusGraph over BigTable - what do you recommend we do going forward?
Migrate away from BigTable? How much confidence does running our traversals against the BigTable emulator should provide?
Many thanks!

Using JanusGraph with the Bigtable backend uses the same code that JanusGraph uses for HBase and that is tested extensively, just with HBase, not with Bigtable. This means that as long as Bigtable is compatible with HBase, JanusGraph should work with Bigtable just the same as with HBase.
But we unfortunately don't know whether changes we make to the HBase storage adapter might break compatibility with Bigtable if that backend behaves slightly different than HBase in cases that we didn't have before, but got due to the changes in our HBase adapter.
We also don't know whether updates in Bigtable break compatibility with HBase which is why we don't update the Bigtable client library any more.

Overall, I think if you test your own traversals with the Bigtable emulator, then that should provide good confidence that it will also work in production. (I don't know much about Bigtable and it's emulator. I'm assuming here that the emulator won't behave differently than Bigtable itself.)

The best way to get confidence in the Bigtable storage adapter would of course be if you try to contribute to JanusGraph to get automatic testing in place for the backend. I haven't looked into it, but that may be as simple as allowing the HBase tests to be executed with a different Docker image (Bitable emulator instead of HBase) and then adding GitHub actions with that image for the HBase tests (basically copy all HBase GitHub actions and then apply config to use the Bigtable image). #2352 did that for Scylla and the CQL backend.

Over the long term, we will probably need some automatic testing for Bigtable or we will have to drop official support for it completely as it doesn't make much sense to stay on an outdated client library for Bigtable. Every change to the HBase storage adapter we make basically also increases the probability of getting compatibility problems.

**Review by li-boxuan — APPROVED** [review]
Ideally, we could set up some CI job that runs the test suite against a real BigTable instance before release, but it will require quite some work and I am not sure who's gonna pay for the cost.

The same applies to Amazon Keyspace. We don't document Amazon keyspace as tested compatibility even though I manually test it against recent releases.

**Comment by FlorianHockmann** [comment]
> Ideally, we could set up some CI job that runs the test suite against a real BigTable instance before release, but it will require quite some work and I am not sure who's gonna pay for the cost.

You mean a real instance instead of the emulator that was mentioned in #415?

Having automated testing in place would of course be ideal and then we wouldn't need to remove Bigtable from the tested compatibility list. But since #415 has been open for so long I don't expect this to be implemented soon. Or are you planning to work on it before the next release?
Otherwise, I'd say we merge this now and then we can later just revert it as soon as we have automated testing in place.

> We don't document Amazon keyspace as tested compatibility even though I manually test it against recent releases.

Good to know that you at least test it manually. But yes, automated testing would also be great there and then we could also add it to the list.

**Comment by li-boxuan** [comment]
Yeah I meant by a real instance rather than an emulator, ultimately. Having an emulator in place would be great, but unfortunately I don’t have a plan to implement that in recent future.

I agree with merging this PR.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FlorianHockmann** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v0.6|[](https://github.com/JanusGraph/janusgraph/pull/3443)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
