### PR TITLE
JANUSGRAPH-1996 Decode meta-properties in Hadoop vertex deserializer

### LINKED ISSUE #1996: Meta Properties of a vertex property missing after retrieving data from cassandra DB
I am using Janus Graph and we are facing issue , when we want to handle meta properties of a vertex property , issue is meta properties are missing , we are not able to see them , i doubt on the class   `org.janusgraph.hadoop.formats.util.JanusGraphVertexDeserializer ` ,  here data is being deserialized , and i did not see any code to retrieve meta properties here , is this need to implemented or am missing something ?

janusgraph-hadoop-core-0.4.0  jar version

For complete details 

https://stackoverflow.com/questions/60221573/how-to-retrieve-meta-properties-defined-for-a-vertex-property-in-java-code

It seems their is code issue

### PR DESCRIPTION
**Pull request by YevIgn**
Refactored properties decoding step to apply it for both edge properties and meta-properties.

Fixes #1996 

Signed-off-by: Evgeniy.Ignatiev <yevgeniy.ignatyev@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by YevIgn** [comment]
Sorry, incorrect setup of mine name as author and signing-off caused this stream of pushes.

**Comment by YevIgn** [comment]
Not sure if CLA status should just refresh itself eventually.

**Comment by porunov** [comment]
@mbrukman `janusgraph-bot` keeps adding `cla: no` to this PR even so the PR is signed. Do you know what could cause this behaviour?

**Comment by mbrukman** [comment]
@porunov — the @janusgraph-bot is probably seeing an issue for the same reason that **communitybridge-easycla** bot is [saying](https://github.com/JanusGraph/janusgraph/pull/2173#issuecomment-661213465):

> [CLA Check](https://api.lfcla.com/v2/repository-provider/github/sign/1543822/77385607/2173)<br /><ul><li>:x:The commit (94a037510146b74a9a8438fe125892d49b57e8fa) is missing the User's ID, preventing the EasyCLA check. [Consult GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve. For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).</li></ul>

I should update @janusgraph-bot to clarify the error—it's most likely happening due to an empty "GitHub user id" field, as pointed out by the EasyCLA bot—which typically happens when the email address used in the commit isn't added to the user's GitHub account, so GitHub doesn't attach the commit to a GitHub account when accessed via the API, which is how both EasyCLA and @janusgraph-bot see it. I'm guessing EasyCLA is then approving it based on the registered email account, but @janusgraph-bot uses the GitHub id as canonical because anyone can set any email address on their commit (it's unauthenticated), so that's why they're both showing this error, and it should be fixed.

@YevIgn — please check to see if the email address you're using in your commits is added to your GitHub account, and if not, please add it. Note that it doesn't have to be primary, and it doesn't have to be made public, it just has to be added to your account. Once you do, you can force re-review from both via a simple trick of "rebasing" without doing anything, which changes the commit hash, and then `git push -f`:

```
$ git rebase HEAD~1

[don't change anything, just save and exit]
[you should now have the same commit, but with a different commit hash on this branch]

$ git push -f
```

**Comment by mbrukman** [comment]
@YevIgn — I see you force-pushed some updates; I don't see EasyCLA having fixed itself (it usually notices pretty quickly), but I see that @janusgraph-bot appears to be exceeding its API quota so I can't even debug it right now, as GitHub is returning error 403 for all requests to it; I will check it later today once its requests are going through.

There's nothing for you to do at this time, I will get back to you once I have more information. Sorry for the inconvenience.

**Comment by YevIgn** [comment]
> @YevIgn — I see you force-pushed some updates; I don't see EasyCLA having fixed itself (it usually notices pretty quickly). Can you please confirm that you added your email address to your GitHub profile as well?
> 
> I see that @janusgraph-bot appears to be exceeding its API quota so I can't even debug it right now, as GitHub is returning error 403 for all requests to it; I will check it later today once its requests are going through.
> 
> There's nothing for you to do at this time, I will get back to you once I have more information. Sorry for the inconvenience.

Hi, @mbrukman 
Sorry for long reply. Yes, tried to align everything as it was in my previous PR when CLA was green. My email address is the same - still in GitHub profile (the one I signed commit with). Commit hash listed in EasyCLA message still points to the commit that I pushed initially - https://github.com/JanusGraph/janusgraph/commit/94a037510146b74a9a8438fe125892d49b57e8fa
But current one is different - https://github.com/JanusGraph/janusgraph/pull/2173/commits/027aacaf1cf9a85a45b96ac312e6d4621daa4c6b

Maybe this causes the issue?

**Comment by mbrukman** [comment]
@YevIgn — I think I see the problem. TL;DR: you need to make sure your name and email match your CLA entry exactly:

https://github.com/JanusGraph/legal/blob/539fde5f65278e49f5d96d5c997c4bef32091d24/CLA_SIGNERS.yaml#L46-L48

Your [`94a03`](https://github.com/JanusGraph/janusgraph/commit/94a037510146b74a9a8438fe125892d49b57e8fa.patch) commit says:

```
From: "Evgeniy.Ignatiev" <Evgeniy.Ignatiev@[company-elided].com>
[...]
Signed-off-by: Evgeniy.Ignatiev <yevgeniy.ignatyev@gmail.com>
```

Your [`027aa`](https://github.com/JanusGraph/janusgraph/commit/027aacaf1cf9a85a45b96ac312e6d4621daa4c6b.patch) commit says:

```
From: Evgenii Ignatev <yevgeniy.ignatyev@gmail.com>
[...]
Signed-off-by: Evgenii Ignatev <yevgeniy.ignatyev@gmail.com>
```

However, the name still doesn't match the CLA entry: "Evgenii" (in the commit) vs "Evgeniy" (in the CLA).

I don't know what name/email you used with EasyCLA, but your commit should match that entry, or you should update the entry you have on file with LF EasyCLA to match this one.

**Comment by YevIgn** [comment]
> @YevIgn — I think I see the problem. TL;DR: you need to make sure your name and email match your CLA entry exactly:
> 
> https://github.com/JanusGraph/legal/blob/539fde5f65278e49f5d96d5c997c4bef32091d24/CLA_SIGNERS.yaml#L46-L48
> 
> Your [`94a03`](https://github.com/JanusGraph/janusgraph/commit/94a037510146b74a9a8438fe125892d49b57e8fa.patch) commit says:
> 
> ```
> From: "Evgeniy.Ignatiev" <Evgeniy.Ignatiev@[company-elided].com>
> [...]
> Signed-off-by: Evgeniy.Ignatiev <yevgeniy.ignatyev@gmail.com>
> ```
> 
> Your [`027aa`](https://github.com/JanusGraph/janusgraph/commit/027aacaf1cf9a85a45b96ac312e6d4621daa4c6b.patch) commit says:
> 
> ```
> From: Evgenii Ignatev <yevgeniy.ignatyev@gmail.com>
> [...]
> Signed-off-by: Evgenii Ignatev <yevgeniy.ignatyev@gmail.com>
> ```
> 
> However, the name still doesn't match the CLA entry: "Evgenii" (in the commit) vs "Evgeniy" (in the CLA).
> 
> I don't know what name/email you used with EasyCLA, but your commit should match that entry, or you should update the entry you have on file with LF EasyCLA to match this one.

Got it. When I got my international passport - it came with updated transliteration rules so - Evgenii Ignatev is how my name is written in legal documents. Can it be updated in CLA signers?

**Comment by YevIgn** [comment]
To clarify - before I was using "Evgeniy Ignatiev" everywhere, but now it should be "Evgenii Ignatev" officially - I'm not aware how this update should be handled in regards to CLA.

**Comment by mbrukman** [comment]
@YevIgn wrote:

> Got it. When I got my international passport - it came with updated transliteration rules so - Evgenii Ignatev is how my name is written in legal documents. Can it be updated in CLA signers?

Of course. Rather than replacing the current version, I'll add this new spelling as an alternative, so that past commits are also marked as valid (in case we merge a branch into another branch, it may bring in past commits, and we don't want to invalidate them).

However, I can only fix this for @janusgraph-bot — for LF EasyCLA, please use the web UI to update it, or file a ticket as you can see in the commit from the EasyCLA bot.

**Comment by YevIgn** [comment]
> @YevIgn wrote:
> 
> > Got it. When I got my international passport - it came with updated transliteration rules so - Evgenii Ignatev is how my name is written in legal documents. Can it be updated in CLA signers?
> 
> Of course. Rather than replacing the current version, I'll add this new spelling as an alternative, so that past commits are also marked as valid (in case we merge a branch into another branch, it may bring in past commits, and we don't want to invalidate them).
> 
> However, I can only fix this for @janusgraph-bot — for LF EasyCLA, please use the web UI to update it, or file a ticket as you can see in the commit from the EasyCLA bot.

Thank you, I think I have already updated it for LF EasyCLA - the check is marked as passed right now.

**Comment by mbrukman** [comment]
@YevIgn — thanks for your contribution and your patience with working out the CLA issues!

@farodin91, @porunov — we're all set with this PR from a CLA perspective, ready to merge whenever you decide.

**Comment by YevIgn** [comment]
Failed test seems unrelated to PR - https://travis-ci.org/github/JanusGraph/janusgraph/jobs/714481133#L1275 - previous build passed, maybe the test is not stable?

**Review by porunov — APPROVED** [review]
LGTM. Thank you @YevIgn !

**Pull request merged**
