### PR TITLE
Merge fix assembly

### PR DESCRIPTION
**Pull request by robertdale**
Merge 0.2 #768

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mbrukman** [comment]
@robertdale — there are 4 commits on this PR, but the only change appears to be the latest commit to add the fix for the assembly, which suggests that `master` already has a bunch of those changes. Do you want to rebase your branch on `master` so that it only has the single additional commit you're merging?

**Comment by robertdale** [comment]
@mbrukman  I made the branch from the tip of master.  It looks like the last merge didn't end up being like a regular merge. They look like cherry-picks.

**Comment by sjudeng** [comment]
Is it possible you did a "Rebase and merge" instead of "Create a merge commit" when merging #762?

**Comment by robertdale** [comment]
@sjudeng I probably picked the default

**Comment by sjudeng** [comment]
That's it then and I guess it was bound to happen since we're rebasing by default. While it makes sense to rebase new commits, when merging commits from the release branch we want to keep them exactly as-is so they should be merged (e.g. merge commit).

**Comment by sjudeng** [comment]
@mbrukman, @pluradj Maybe it's worth considering changing the default back to "Create a merge commit" since the impact if someone does this instead of rebasing is just a extra merge commit versus accidentally rebasing which causes duplicate commits.

**Comment by mbrukman** [comment]
@sjudeng — there isn't a notion of "default" for that button in the settings. The only options we have are whether or not to enable any of these, with the caveat that at least one option must be checked:

> # Merge button
> When merging pull requests, you can allow any combination of merge commits, squashing, or rebasing. At least one option must be enabled.
> 
> - [ ] Allow merge commits  
>     Add all commits from the head branch to the base branch with a merge commit.
> - [ ] Allow squash merging  
>     Combine all commits from the head branch into a single commit in the base branch.
> - [ ] Allow rebase merging  
>     Add all commits from the head branch onto the base branch individually.

**Comment by sjudeng** [comment]
@mbrukman Gotcha, thanks for checking. We'll just need to remember/document that merges of release branches into master should be done "with merge commit".

**Pull request merged**
