### PR TITLE
Externalize TIMEOUT_MS so that backends can change the timeout

### PR DESCRIPTION
**Pull request by amcp**
When testing DynamoDB LogTest in the multiple item data model for the following methods:

- [x] MultiDynamoDBLogTest/mediumSendReceiveSerial
- [x] MultiDynamoDBLogTest/testMultipleReadersOnSingleLog
- [x] MultiDynamoDBLogTest/testMultipleReadersOnSingleLogSerial

I found that these tests failed because the timeout was too small. I would like to externalize timeoutMS in methods sendReceive and sendReceiveSimple so that I can adjust the timeout so that the tests pass in my dev environment.

Related [issue](https://github.com/awslabs/dynamodb-titan-storage-backend/issues/110) on the DynamoDB backend. [Current build](https://travis-ci.org/awslabs/dynamodb-titan-storage-backend) reproduced the timeout failure in the [MultiIdAuthorityLogLockStore](https://travis-ci.org/awslabs/dynamodb-titan-storage-backend/jobs/227387308) module.

### CODE REVIEW

**Comment by amcp** [comment]
https://travis-ci.org/awslabs/dynamodb-titan-storage-backend/jobs/227387308
Failed tests: 
  MultiDynamoDBLogTest>LogTest.mediumSendReceiveSerial:93->LogTest.simpleSendReceive:256->LogTest.sendReceive:275 Did not read expected number of messages before timeout was reached (latch count is 1414)
  MultiDynamoDBLogTest>LogTest.testMultipleReadersOnSingleLog:103->LogTest.sendReceive:275 Did not read expected number of messages before timeout was reached (latch count is 5)
  MultiDynamoDBLogTest>LogTest.testMultipleReadersOnSingleLogSerial:98->LogTest.sendReceive:275 Did not read expected number of messages before timeout was reached (latch count is 3)
Tests run: 42, Failures: 3, Errors: 0, Skipped: 0

**Comment by amcp** [comment]
FYI, Changing the timeout on my side fixed testMultipleReadersOnSingleLogSerial, but not mediumSendReceiveSerial and testMultipleReadersOnSingleLog.
https://travis-ci.org/awslabs/dynamodb-titan-storage-backend/jobs/227405969

**Comment by sjudeng** [comment]
Is there work still pending on this PR or is it ready to merge?

**Comment by amcp** [comment]
@sjudeng @analytically I forgot to increase the visibility of the consumer classes at the bottom. However raising from private to protected does not break anything so I can proceed with the merge.

**Pull request merged**
