### PR TITLE
Makes Janusgraph run as a non-privileged user in docker

### PR DESCRIPTION
**Pull request by tonit**
In this commit i also incorporated a small fix to the overall size by removing the zip file after extraction.

### CODE REVIEW

**Comment by pluradj** [comment]
@tonit could you please retarget this for the `0.2` branch? thanks.

**Comment by tonit** [comment]
Yes sure. I missed the comment.

**Comment by tonit** [comment]
> @tonit could you please retarget this for the `0.2` branch? thanks.

https://github.com/JanusGraph/janusgraph/pull/1289

**Comment by chupman** [comment]
duplicate of #1289.

**Comment by tonit** [comment]
@chupman no its not a dupe as its a separate PR for master and for the 0.2 branch

**Comment by porunov** [comment]
@tonit All commits from lower versions will be merged in upper versions and in master. There is no need to provide separate PRs for `0.2` and `master`. When we merge your PR into `0.2` it will eventually be merged into `0.3` and `master` branches.

**Comment by farodin91** [comment]
Do we need this docker file any longer since we have an extra repo docker?

**Comment by chupman** [comment]
Closing as a duplicate of PR #1289 which has been merged and will be later merged upstream.

**Pull request closed without merging**
