### PR TITLE
Don't set CQL NETTY_{ADMIN,IO}_SIZE by default

### LINKED ISSUE #2936: storage.cql.netty.admin-size default value is 0 instead of 2
### Context:
- Version: 0.6.0
- Storage Backend: cql

### Description:
Cassandra's default size for Netty admin-group is 2 [doc](https://docs.datastax.com/en/developer/java-driver/4.13/manual/core/performance/#thread-pooling), [code](https://github.com/datastax/java-driver/blob/4.13.0/core/src/main/resources/reference.conf#L2219)

JanusGraph 0.6.0 overrides it and sets it to 0 (`Runtime.getRuntime().availableProcessors() * 2`) by default [doc](https://docs.janusgraph.org/configs/configuration-reference/#storagecqlnetty), [code 1](https://github.com/JanusGraph/janusgraph/blob/v0.6.0/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java#L351), [code 2](https://github.com/JanusGraph/janusgraph/blob/v0.6.0/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLProgrammaticConfigurationLoaderBuilder.java#L165).

We should probably leave `NETTY_IO_SIZE`/`NETTY_ADMIN_SIZE` unset by default and let Cassandra pick the defaults.
If that's not doable, we could set the default value to 2 in JanusGraph.

### PR DESCRIPTION
**Pull request by cdegroc**
Fixes #2936

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there an issue associated with this PR? Is it referenced in the commit message?
- [X] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Review by porunov — COMMENTED** [review]
Thank you @cdegroc .
LGTM but I would probably target `master` branch here because it looks like a breaking change unless there is a reason to introduce this change in 0.6.1 release.
I would also recommend to add this configuration change in upgrade instructions here: https://github.com/JanusGraph/janusgraph/blob/master/docs/changelog.md#upgrade-instructions
I.e. what parameters were changed and what to do if you want to preserve the old default behavior

**Comment by li-boxuan** [comment]
@porunov I don't think it's a breaking change because it seems to fix a regression problem caused by the 0.6.0 release. If it's true, then it makes sense to release it in v0.6.

**Comment by porunov** [comment]
> @porunov I don't think it's a breaking change because it seems to fix a regression problem caused by the 0.6.0 release. If it's true, then it makes sense to release it in v0.6.

Got it. You right then

**Review by porunov — APPROVED** [review]
LGTM. Thank you @cdegroc !

**Review by FlorianHockmann — APPROVED** [review]

**Pull request merged**
