### PR TITLE
Report cache hits explicitly

### PR DESCRIPTION
**Pull request by tunaygur**

### CODE REVIEW

**Comment by mbrukman** [comment]
Hi @tunaygur, the email address you provided us earlier for the CLA is not the one you used for commits in this PR. I can fix this for you in the CLA verifier to use your corporate email address rather than your personal one.

Also, you need the "Signed-off-by:" in your commit, please see the `CONTRIBUTING.md` in the root of the JanusGraph repo for details on how to add it; you don't need to create a new PR for this, you can fix it in-place.

**Comment by countrodrigo** [comment]
Hi Misha, I just signed the commit.

**Comment by twilmes** [comment]
Thanks for the contribution @countrodrigo. Is there an issue associated with this PR? If not, could you create one and reference it here? I can see what the code is doing but it makes it easier to construct the changelog for releases. Thanks!

**Comment by countrodrigo** [comment]
This PR addresses this issue: #267

**Comment by sjudeng** [comment]
Looks like there are some test failures.

ExpirationCacheTest#testSmallCache
```
mvn clean install -Dtest=ExpirationCacheTest#testSmallCache -pl janusgraph-test
...
testSmallCache(org.janusgraph.diskstorage.cache.ExpirationCacheTest)  Time elapsed: 0.118 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.janusgraph.diskstorage.keycolumnvalue.cache.KCVSCache.incActionBy(KCVSCache.java:49)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.ExpirationKCVSCache.getSlice(ExpirationKCVSCache.java:133)
	at org.janusgraph.diskstorage.cache.KCVSCacheTest.testSmallCache(KCVSCacheTest.java:122)
```

HBaseOperationCountingTest#testCacheSpeedup
```
mvn clean install -Dtest=HBaseOperationCountingTest#testCacheSpeedup -pl :janusgraph-hbase-10
...
testCacheSpeedup(org.janusgraph.graphdb.hbase.HBaseOperationCountingTest)  Time elapsed: 58.815 sec  <<< ERROR!
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:57)
...
Caused by: java.lang.AssertionError: null
	at org.janusgraph.diskstorage.keycolumnvalue.cache.KCVSCache.incActionBy(KCVSCache.java:49)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.ExpirationKCVSCache.getSlice(ExpirationKCVSCache.java:133)
```

Once you've resolved these would you run the full default test suite (`mvn clean install`) and post the build summary result ("BUILD SUCCESSFUL...")?

**Comment by tunaygur** [comment]
Closing this PR as it's obsolete..

**Comment by mbrukman** [comment]
@tunaygur — since you say "it's obsolete", is there another PR that replaces this one? Issue #267 that this PR is pointing to is still open.

**Pull request closed without merging**
