### PR TITLE
Set version to 0.4.1-SNAPSHOT [skip ci]

### LINKED ISSUE #1664: Initialize master branch for 0.4.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by FlorianHockmann**
Fixes #1664

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [-] Have you written and/or updated unit tests to verify your changes?
- [-] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [-] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [-] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [-] Have you ensured that format looks appropriate for the output in which it is rendered?
- [-] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by porunov** [comment]
@FlorianHockmann I think the PR can be merged with CTR and don't need approvals. Also, I would like to ask you to make `0.4` branch after merging this PR because we need to bump master to `0.5.0-SNAPSHOT` version.

**Comment by FlorianHockmann** [comment]
@porunov I agree about CTR here and think in general that a PR shouldn't be needed for this as it's part of the release process.
Can't you create the `0.4` yourself?

**Comment by porunov** [comment]
@FlorianHockmann I will try to create '0.5' branch on Monday because I am currently on the vacation and don't have a laptop with me

**Comment by mbrukman** [comment]
I just created the `0.4` branch. In trying to add branch protections for the new branch (which isn't automatically covered since we're not using wildcard patterns), I've noticed some inconsistencies, so we should discuss them separately — I'd like to unify them and make branch protections automatic going forward.

**Comment by porunov** [comment]
@mbrukman Could you please tell more about branch protraction and inconsistencies?

In addition, we should bump current `master` branch to `0.5.0-SNAPSHOT` version

**Comment by mbrukman** [comment]
@porunov wrote:

> Could you please tell more about branch protraction and inconsistencies?

Some branches require a certain number of reviews (`0.1`), others don't. If you can see this page: https://github.com/JanusGraph/janusgraph/settings/branches, you can see each branch's current settings.

> In addition, we should bump current `master` branch to `0.5.0-SNAPSHOT` version

That's a good point; should this be part of the release process?

**Comment by porunov** [comment]
@mbrukman I don't have a permission to see JanusGraph settings, so I am not aware of those branch settings.

Currently, the PR should be created to bump the version to '0.5.0-SNAPSHOT' and it should be included into a '0.5.0' milestone. The PR should be similar to this one. But I don't see a point for it, so I agree here with @FlorianHockmann that we can juse make a CTR commit for it without a PR.

**Pull request merged**
