### PR TITLE
Fix code comment for Python doc

### PR DESCRIPTION
**Pull request by XD-DENG**
To address https://github.com/JanusGraph/janusgraph/issues/1706

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?
- [x] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by porunov** [comment]
@XD-DENG Thanks for the contribution!

There is a requirement that each contributor must sign a CLA. It isn't automate right now but JanusGraph members are working on it.

To contribute you should:
1. Sign a CLA. Instructions are here: https://github.com/JanusGraph/legal/blob/master/README.md
2. Follow this instructions: https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md

Please feel free to ask any questions if you have some.

**Comment by XD-DENG** [comment]
Thanks @porunov . Sure, I will figure out the CLA later and ping you here.

**Comment by XD-DENG** [comment]
Hi @porunov  , I may not sign the CLA at this moment. However, to fix the issue, if you don't mind, may you help raise a PR with the same change here? I declare that I'm fine with it. Thanks.

**Comment by porunov** [comment]
Thank you @XD-DENG . I have created the PR #1764 to address the issue

**Comment by XD-DENG** [comment]
Thanks @porunov

**Pull request closed without merging**
