### PR TITLE
Issue 648 - avoid excessive array list resizing for MKS queries

### PR DESCRIPTION
**Pull request by pencal**
Resolving #648  

Signed-off-by: pencal <ckplei@gmail.com>

Thank you for contributing to JanusGraph.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by robertdale** [comment]
See https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md

**Comment by pencal** [comment]
Thanks. @robertdale  When I submitted the PR, I followed the document and I am definitely in the CLA. I noticed the PR was signed off using my github account name instead of my name. So I closed this PR and opened another with the correct name in the sign-off. But I am getting the same cla:no label. I have already emailed the  janusgraph-cla@googlegroups.com as suggested by the document.

**Comment by mbrukman** [comment]
@pencal – the reason your PRs are not getting `cla: yes` is because you are not using the same name (your full name) as in the CLA.

This is documented in the [contribution guidelines](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#configure-your-repo-to-match-the-cla) along with how to fix existing branches and exiting PRs.

Please follow those instructions to change your name from your GitHub username to your actual full name, and the bot will recognize you.

**Comment by pencal** [comment]
@mbrukman found the issue. Did a git config -l and noticed that i have a local config in my project root that was still using my github username instead of my full name. Hopefully this is it. Thank you for all the help and sorry for the confusions of creating many PRs.

**Comment by mbrukman** [comment]
@pencal – yep, that was it, one of your PRs I was debugging had the issue where Author != Committer, and I see you've now fixed that, and the CLA tag is now green so you're good to go!

**Pull request closed without merging**
