### PR TITLE
Issue #1200: Update traversal source map in JanusGraphManager when new graph is dynamically created

### PR DESCRIPTION
**Pull request by paul-k-civitas**
Fixes issue #1200  

@dpitera When a new graph is created using the JanusGraphManager, the graph and its traversal source are added to the script engine's global variable bindings, but the traversal is not added to the graph manager's map of registered traversal sources; this prevents a client from creating a remote traversal object (using `GraphTraversalSource.withRemote()`) or from creating an aliased Gremlin Server client (using `Client.alias()`). This PR addresses that.

(Aside) I'm just getting the CLA process started on my end, so it may be some time for that to get addressed.

Signed-off-by: Paul Khermouch <paul.khermouch@civitaslearning.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by CptQuint** [comment]
I've just performed a build from the master branch with these changes included and unfortunately it's still failing to create the remote traversal:

`gremlin> :remote connect tinkerpop.server conf/remote.yaml session testing0
==>Configured localhost/127.0.0.1:8182-[testing0]
gremlin> :remote console
==>All scripts will now be sent to Gremlin Server - [localhost/127.0.0.1:8182]-[testing0] - type ':remote console' to return to local mode
gremlin>
gremlin> map = new HashMap<String, Object>()
gremlin> map.put("storage.backend", "cassandrathrift")
==>null
gremlin> map.put("storage.hostname", "127.0.0.1")
==>null
gremlin> ConfiguredGraphFactory.createTemplateConfiguration(new MapConfiguration(map))
==>null
gremlin> graphName = "test0"
==>test0
gremlin> ConfiguredGraphFactory.create(graphName)
==>standardjanusgraph[cassandrathrift:[127.0.0.1]]
gremlin> :remote close
==>Removed - Gremlin Server - [localhost/127.0.0.1:8182]-[testing0]
gremlin> :remote connect tinkerpop.server conf/remote.yaml session testing1
==>Configured localhost/127.0.0.1:8182-[testing1]
gremlin> :remote console
==>All scripts will now be sent to Gremlin Server - [localhost/127.0.0.1:8182]-[testing1] - type ':remote console' to return to local mode
gremlin> ConfiguredGraphFactory.getGraphNames()
==>test0
gremlin> test0
==>standardjanusgraph[cassandrathrift:[127.0.0.1]]
gremlin> test0_traversal
No such property: test0_traversal for class: Script13
Type ':help' or ':h' for help.
Display stack trace? [yN]y
org.apache.tinkerpop.gremlin.jsr223.console.RemoteException: No such property: test0_traversal for class: Script13
        at org.apache.tinkerpop.gremlin.console.jsr223.DriverRemoteAcceptor.submit(DriverRemoteAcceptor.java:178)
        at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.execute(GremlinGroovysh.groovy:99)
        at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:122)
        at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:95)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:165)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:130)
        at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:59)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:165)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:89)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
        at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:146)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
        at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:453)
gremlin> :remote close
==>Removed - Gremlin Server - [localhost/127.0.0.1:8182]-[testing1]
gremlin> :exit
`

**Comment by paul-k-civitas** [comment]
@CptQuint I found a bug in the implementation of `JanusGraphManager.getAsBindings()` and fixed it; I think this should address your test case.

**Comment by CptQuint** [comment]
@paul-k-civitas unfortunately this test was performed on a JanusGraph server built from the master branch including your fix.

**Comment by pluradj** [comment]
@paul-k-civitas any news on the CLA?

**Comment by paul-k-civitas** [comment]
Sorry about the delay on this -- apparently a meeting was missed, and rescheduled for next Monday... _soon_, I promise...

**Comment by CptQuint** [comment]
Any updates on this? It'd be great if this made the v0.3.1 release.

**Comment by paul-k-civitas** [comment]
The CLA stuff was approved by the right person today, now we just have to fill the paperwork out... _almost there_...

**Comment by paul-k-civitas** [comment]
@mbrukman I just emailed the CCLA to the janusgraph-cla google group!

**Pull request merged**
