### PR TITLE
Issue 329 - Added commits for Solr

### PR DESCRIPTION
**Pull request by holleyism**
Signed-off-by: Adam Holley <holleya@us.ibm.com>

### CODE REVIEW

**Comment by holleyism** [comment]
Isn't this part of the commit contract?  Even in production I would think I should be able to know that a vertex has been committed and is available for query. If not then we should probably document that commit when using Solr is not deterministic.

**Comment by sjudeng** [comment]
For performance some indexing/storage backends only guarantee eventual consistency as part of their distributed storage model. Do you know if waits are included in other indexing/storage backends?

**Comment by robertdale** [comment]
There is already an option to wait for the index. See `wait-searcher` -   http://docs.janusgraph.org/latest/config-ref.html#_index_x_solr  

I know that elasticsearch also does not immediately commit or make visible.  It has an index refresh interval.

**Comment by holleyism** [comment]
Ok. I'll remove this and see if I can update the unit test config to still avoid using sleep.

**Comment by sjudeng** [comment]
Does it work to set `wait-searcher` in the test configs, or is the option not working? If not then it seems like your updates are the correct behavior if the option is set (good call @robertdale).

**Comment by holleyism** [comment]
Going to look into this more as it appears the unit tests are already setting wait-searcher to true, and SolrIndex sets the commit to wait if true.

**Comment by holleyism** [comment]
This PR should also close #429 as it's not necessary.

**Comment by holleyism** [comment]
@sjudeng Can you please review again?  Removed all changes except those for unit-tests.  Thanks.

**Comment by sjudeng** [comment]
I'm going to rerun the tests in Travis a few times. I want to make sure there's not a sporadic timing issue.

**Pull request merged**
