### PR TITLE
Name Backend Threads

### LINKED ISSUE #2708: Name threads in ExecutorService for parallel backend queries
As requested here: https://github.com/JanusGraph/janusgraph/pull/2700#discussion_r670590598
It would be useful to add meaningful names to such threads

### PR DESCRIPTION
**Pull request by cdegroc**
Fixes #2708

Signed-off-by: Clement de Groc <clement.degroc@datadoghq.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there an issue associated with this PR? Is it referenced in the commit message?
- [X] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by cdegroc** [comment]
Hey @porunov. Any chance you can review this small addition and optionally retry the failing CI checks please 🙏?

**Review by porunov — APPROVED** [review]
LGTM. Thank you @cdegroc !

**Comment by porunov** [comment]
@cdegroc could you please rebase you PR against the latest commit in `master`? It has a fix for `dist-tests`.

**Review by li-boxuan — APPROVED** [review]
LGTM 👍

**Pull request merged**
