### PR TITLE
Add Times Internet as a production user [skip ci]

### PR DESCRIPTION
**Pull request by mbrukman**
Adding per request of a company representative's post on
janusgraph-users@; more information at the URL.

-----

/cc: @pankajydv — please review and approve.

### CODE REVIEW

**Comment by pankajydv** [comment]
@mbrukman The images in our original [email post](https://groups.google.com/forum/#!msg/janusgraph-users/HK88QIGRpnY/FNK5t4eDBAAJ) are broken and in the next [email post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/janusgraph-users/HK88QIGRpnY/N-_ecCcLAQAJ) - the images are in-place but the whole text is collapsed as -_show hidden text_-. Please let me know if I shall write a new post so that all images and the message text is in place in a new email post. Apart from this, it looks good.

**Comment by pankajydv** [comment]
@mbrukman request you to please link to this [blog](http://denmarkblog.timesinternet.in/blogs/graph/times-internet-is-using-janusgraph-as-main-database-in-cms-for-all-newsrooms/articleshow/63709837.cms). Please note this blog is powered from Times Internet CMS - (content management system) which is running on this same janusgraph/cassandra system.

**Comment by mbrukman** [comment]
@pankajydv — thanks for the feedback! I've fixed URL and added additional description text.

Please take another look.

**Comment by pankajydv** [comment]
The changes look good and I have approved, please go ahead - thanks

**Pull request merged**
