### PR TITLE
Enclosing transaction is closed error fix

### LINKED ISSUE #422: Edges traversal streaming - enclosing transaction is closed error.
Hello.

I've REST API service for graph interaction.
For retrieving graph object I use traversal.toStream API.

On some load(other requests processing (create/get objects)), edges stream failed with error:
```Operation cannot be executed because the enclosing transaction is closed
java.lang.IllegalStateException: Operation cannot be executed because the enclosing transaction is closed
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.verifyOpen(StandardJanusGraphTx.java:299)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.getVertex(StandardJanusGraphTx.java:383)
	at org.janusgraph.graphdb.relations.RelationIdentifier.findRelation(RelationIdentifier.java:155)
	at org.janusgraph.graphdb.relations.RelationIdentifier.findEdge(RelationIdentifier.java:186)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$8.apply(StandardJanusGraphTx.java:1327)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$8.apply(StandardJanusGraphTx.java:1322)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:817)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at org.janusgraph.graphdb.query.LimitAdjustingIterator.next(LimitAdjustingIterator.java:94)
	at org.janusgraph.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:55)
	at org.janusgraph.graphdb.query.ResultSetIterator.next(ResultSetIterator.java:67)
	at org.janusgraph.graphdb.query.ResultSetIterator.next(ResultSetIterator.java:28)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:674)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:131)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.DedupGlobalStep.processNextStart(DedupGlobalStep.java:105)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
```

Vertex streaming working fine.

setup:
JanusGraph 0.1.1
storage backend - cassandra.
tinkerpop (3.2.3/3.2.5)

### PR DESCRIPTION
**Pull request by xdev-developer**
Fixed enclosing transaction is closed error when multiple threads interact with graph
Fixes #422

### CODE REVIEW

**Comment by mbrukman** [comment]
Please be sure to follow [these instructions](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#commit-changes-and-sign-the-developer-certificate-of-origin) to add a `Signed-off-by` tag to your commits to signify commitment to the Developer Certificate of Origin.

Note that you can do this in-place using the same branch and the same PR, as before.

**Comment by xdev-developer** [comment]
done!

**Comment by xdev-developer** [comment]
running now.

**Comment by sjudeng** [comment]
@mbrukman It doesn't look like @davidclement90 has write access to the repo (his approval above has a caveat).

**Comment by mbrukman** [comment]
Good catch, @sjudeng! My apologies, @davidclement90, I did not add you to the `committers` group in the @JanusGraph org when you were announced as a new committer. A belated welcome and thank you for your contributions!

I just sent you an invitation to join the group; once you do, you will have write access to the JanusGraph repos, and your PR approvals will get the same green checkmark as other committers and maintainers.

**Comment by davidclement90** [comment]
The mail was in my spam...
I just accept it.

**Pull request merged**
