### PR TITLE
docs: Add solr, remove data types [skip ci]

### PR DESCRIPTION
**Pull request by robertdale**
Syncing docs to match current state.

### CODE REVIEW

**Comment by robertdale** [comment]
@amcp code -  https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/StandardSerializer.java#L130

**Comment by robertdale** [comment]
@amcp not sure what you mean about generating the configuration reference.  The lists I'm referring to are static lists in the docs.  These data types were previously removed from the graph section in PR #170 but were not removed from the search predicate docs.

**Comment by robertdale** [comment]
@amcp on generating the supported types list, I would say no to graph because there are many types for internal use beyond what is supported for user. [See here. ](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/StandardSerializer.java#L76) 

For indexes, also no, because there's no succinct list, just if statements checking type.

**Comment by robertdale** [comment]
@amcp T[he full list of types.](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/StandardSerializer.java)

**Comment by amcp** [comment]
@robertdale Understood. Why is UUID not a a supported type for users, even though it is a primitive type? seem like most of the primitive types are in the documentation's list.

**Comment by robertdale** [comment]
@amcp Good catch.  UUID is a supported property key type, but not listed in **search** data types. It appears that all search backends do support UUID.  The only caveat is that only `eq()` and `neq()` predicates are supported.   I've added it to the search docs.

**Pull request merged**
