### PR TITLE
Make index selection strategy configurable 

### PR DESCRIPTION
**Pull request by li-boxuan**
This adds a new query.index-select-strategy config option,
so that users can choose which index selection strategy to
use.

Related to #2048

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by li-boxuan** [comment]
>  it will only pass as long as the ThresholdBasedIndexSelectionStragegy is set by default. If we switch to another strategy at some point, this test could possibly fail.

Thanks for the review! I am not quite sure about this choice. It was more or less by intention so that if anyone accidentally changed the default behavior, this test would fail.

**Comment by rngcntr** [comment]
Alright, I understand your intention. How about making this an explicit test for the strategy and _additionally_ writing a test that checks that the correct strategy is selected by default?

At the current state, I'm ok with merging but I would prefer to give a "weak approve".

**Comment by li-boxuan** [comment]
@rngcntr Sorry for being quiet for some time. Point taken; In order to write the test properly, I end up making the index select strategy configurable, which I think might be useful (in the future).

**Review by rngcntr — APPROVED** [review]
Now is my time to apologize for being quiet.
I like the new changes and I think this is ready to go!

**Review by porunov — APPROVED** [review]
LGTM. Thank you @li-boxuan for the contribution! Thank you @rngcntr for the review!

**Review by farodin91 — APPROVED** [review]
LGTM! Thank you @li-boxuan.

**Pull request merged**
