### PR TITLE
Update coverity scan

### PR DESCRIPTION
**Pull request by chupman**
It's been over a year and 300+ commits since our last coverity scan. I figured we were due.
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mbrukman** [comment]
Interesting, looks like this PR somehow got a `[cla: no]` tag, which is somewhat concerning as we're not handling something, somewhere here... Wonder if this will become an issue with the Linux Foundation CLA verifier as well or not.

In any case, I believe @sjudeng and I simply fast-forwarded the `coverity_scan` branch periodically to match `master` rather than using the PR approach (which creates a merge commit); you should be able to do this as a committer; if not, one of the admins can do this.

**Comment by chupman** [comment]
Thanks @mbrukman I'll do that instead. Coverity didn't actually get updated.

This is total conjecture, but there was a [PR](https://github.com/JanusGraph/janusgraph/pull/868) over a year ago that had to be rolled back due a lack of CLA. I think it might be in this batch and might explain the CLA:no.

**Comment by chupman** [comment]
@sjudeng would you be able to fix the `coverity_scan` branch? With the current branch permissions force pushing isn't allowed to `coverity_scan` so I can't resolve the situation I created. Once it's fixed I was planning to automate a weekly scan in a travis cron job so it shouldn't happen again.

**Comment by mbrukman** [comment]
@chupman — I can help with that. Would you like me to force-push `coverity_scan` to match the current `master` or a different branch?

**Comment by chupman** [comment]
@mbrukman master probably makes the most sense.

**Comment by mbrukman** [comment]
Done. https://github.com/JanusGraph/janusgraph/tree/coverity_scan says it's now even with `master`.

**Comment by chupman** [comment]
Thanks Misha!

**Pull request merged**
