### PR TITLE
Correct name of storage.hbase.ext

### PR DESCRIPTION
**Pull request by kottmann**
This fixes issue #134

### CODE REVIEW

**Comment by kottmann** [comment]
I signed the ICLA and submitted it.

**Comment by mbrukman** [comment]
@kottmann – the email address you are using for your commits does not match the email address used on your ICLA. You have to be consistent; otherwise, it will not be recognized. Will you be signing commits with Gmail or Apache email address?

Also, please sign off on your commits as per [`CONTRIBUTING.md`](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#commit-changes-and-sign-the-developer-certificate-of-origin).

**Comment by kottmann** [comment]
@mbrukman I signed the commit now with my apache code signing key and I also changed the author and committer to my apache address. I didn't expect the CLA process and only looked into it after my commit. You might want to add a template with a checklist that people see when they send you a PR. 

@jerryjch let me update the commit itself as you suggested

**Comment by kottmann** [comment]
Should I open a new PR to have the cla check run again?

**Comment by mbrukman** [comment]
@kottmann – no need to open a new PR. This will be handled shortly.

**Pull request merged**
