### PR TITLE
Add Astra to Cassandra Backends docs page

### LINKED ISSUE #2879: Add Astra to Cassandra Backends docs page
**Describe the feature:**
- Add Astra to Cassandra Backends docs page: https://docs.janusgraph.org/storage-backend/cassandra/

### PR DESCRIPTION
**Pull request by alexleventer**
Add Astra to Cassandra Backends docs page: https://docs.janusgraph.org/storage-backend/cassandra/

Fixes #2879 

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by mbrukman** [comment]
@alexleventer — thanks for your contribution! Please ask your employer to sign a Corporate CLA with The Linux Foundation.

**Comment by alexleventer** [comment]
Done @mbrukman - thanks!

**Comment by farodin91** [comment]
@alexleventer Would you like to change base v0.6?

**Comment by alexleventer** [comment]
Done @farodin91

**Comment by farodin91** [comment]
@alexleventer My idea that you change your branch which currently master and change it to v0.6. You can easy do it with git stash. 
Following commands should work:
```
git reset HEAD~2
git stash
git reset --hard upstream/v0.6
git stash apply
...commit now.
```

**Comment by mbrukman** [comment]
@alexleventer — in the future, please consider not using the `master` branch for creating your PR, but create a separate feature branch for the purpose of the PR, which makes it easy to rebase your branch on top of another branch from the repo, without pulling in additional commits. The number of additional commits you see added to your branch may be because you were using the `master` branch while trying to submit to the `v0.6` branch.

E.g., here's a sample workflow:

```
$ git checkout v0.6
$ git checkout -b add-astra-to-docs
# make changes to the files
$ git add [...]
$ git commit
$ git push
```

Please see https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#create-a-new-branch for more info.

**Comment by alexleventer** [comment]
Thanks @mbrukman - will do. Appreciate it 👍

**Pull request closed without merging**
