### PR TITLE
removed empty files referenced in issue #664

### PR DESCRIPTION
**Pull request by chupman**
Wanting to verify that removing the files referenced in issue #664 will pass travis-ci tests

Thank you for contributing to JanusGraph.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mbrukman** [comment]
@pluradj — looks like @chupman is from IBM; can you please confirm and add him to the IBM CCLA?

**Comment by mbrukman** [comment]
The CCLA addition is being handled by @pluradj in https://github.com/JanusGraph/legal/pull/73

**Comment by mbrukman** [comment]
@chupman — please add a `Signed-off by` block to your commit as per `CONTRIBUTING.md` document.

**Comment by chupman** [comment]
Sorry I forgot the sign-off. Just added it in.

**Comment by robertdale** [comment]
@chupman Could you rebase this PR on 0.2 and the merge to master on a new PR?

**Comment by chupman** [comment]
@robertdale I was getting conflicts when I rebased off the 0.2 branch so I ended up stashing and popping my changes.

**Comment by robertdale** [comment]
@chupman You just need to update this PR such that the base is 0.2.  https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

**Comment by robertdale** [comment]
@chupman Great.  Now you can merge to master and then make a PR for that.

**Pull request merged**
