### PR TITLE
Unix style directory path usage in tests makes build fail on Windows #2887

### PR DESCRIPTION
**Pull request by sandeep-mishra**
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there an issue associated with this PR? Is it referenced in the commit message?
- [X] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you written and/or updated unit tests to verify your changes?
- [] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by li-boxuan** [comment]
@sandeep-mishra Thank you for contributing! Can you please squash your commits into a single commit, and [sign](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#commit-changes-and-sign-the-developer-certificate-of-origin) it properly?

**Comment by sandeep-mishra** [comment]
@li-boxuan It's updated accordingly. Please help check.

**Comment by sandeep-mishra** [comment]
I have checked failed build log. It is not relevant to changes in PR. @li-boxuan Please help retrigger build.
Seems the build failed due to network error. 
RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.

**Review by li-boxuan — APPROVED** [review]
LGTM, thank you @sandeep-mishra

**Review by farodin91 — APPROVED** [review]
LGTM!

**Pull request merged**
