### PR TITLE
Checkstyle for OneTopLevelClass and testsources

### PR DESCRIPTION
**Pull request by farodin91**
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by porunov** [comment]
I think we will need to add documentation about enforced styles, so that people who break those styles don't search too long in error logs to find out that some imports ordering is enforced or nested classes are not allowed. 
Probably, if we are following some code style practices from Google or Sun or other companies, we could just include the link to code style guide into Contributing.md and say that style checks are enforced for some things.

**Comment by farodin91** [comment]
> I think we will need to add documentation about enforced styles, so that people who break those styles don't search too long in error logs to find out that some imports ordering is enforced or nested classes are not allowed.
> Probably, if we are following some code style practices from Google or Sun or other companies, we could just include the link to code style guide into Contributing.md and say that style checks are enforced for some things.

Good idea, I will look into writing a documentation.

**Review by rngcntr — APPROVED** [review]
LGTM. Regarding the documentation, I don't think that has do be done as part of this PR. I would prefer to open a new issue for that.

**Review by porunov — APPROVED** [review]
LGTM but we should rebase this PR against the latest master commit before merging it.

**Comment by farodin91** [comment]
I'm on vacation and won't be able rebase it before mid/end of august. 
I think it be good merge this into 0.6 to reduce the merge conflict of back ports. 
If someone wants to rebase it go for it.

**Comment by farodin91** [comment]
@porunov  I rebased this PR. Should i merge it or should we wait for the release?

**Comment by porunov** [comment]
@farodin91 Feel free to merge it. We are going to repack 0.6.0 release as there were several fixes.
Moreover we probably will wait for #2757 anyway and potentially for #2763 before 0.6.0 release.

**Pull request merged**
