### PR TITLE
Change "Saturn"'s Vertex label back to "titan" (0.1 branch)

### PR DESCRIPTION
**Pull request by mbrukman**
This PR is a cherry-pick of PR #194 from `master` to the `0.1` branch.

Thanks to @sdmonov for catching this and sending the original PR.

### CODE REVIEW

**Comment by mbrukman** [comment]
Did something change somewhere? It looks like `0.1` is not a branch that Travis runs on (case in point this PR), and it's not listed on [Travis CI's list of active branches](https://travis-ci.org/JanusGraph/janusgraph/branches).

I thought the removal of the list of branches meant that it runs on everything, I guess that's not the case?

**Comment by sjudeng** [comment]
Need to merge #183

**Comment by mbrukman** [comment]
I remember seeing that PR, @sjudeng, and after seeing it approved, I assumed it would have been merged, but it wasn't, apparently. Just merged it, so it will kick in next time, but I presume we don't need to rerun the entire test suite for this cherry-pick, what do you think? :-)

**Comment by sjudeng** [comment]
I think you can just merge this. Travis ran okay (or as good as usual) on the original master-based PR (https://travis-ci.org/JanusGraph/janusgraph/builds/219384251). But I'll try to run all tests one more time on 0.1 leading up to the release vote.

**Comment by sdmonov** [comment]
@mbrukman you are welcome!

**Pull request merged**
