### PR TITLE
Add license header check and missing headers #525

### LINKED ISSUE #525: Automate verification of license headers
As pointed out in issue #522, we can get into a situation where some files are missing license headers (or have duplicate or incorrect headers). In other cases, reviewers have had to manually point out to contributors that the new files they were adding were missing license headers.

It should be possible to automate this verification as a test, so that files are not committed to the repository without having a header, and this check is done automatically, without relying on manual reminders from maintainers, or after-the-fact fixes such as PR #523.

Some options for implementing this are:

* http://www.mojohaus.org/license-maven-plugin/
* http://checkstyle.sourceforge.net/config_header.html

and there may be other alternatives available as well.

### PR DESCRIPTION
**Pull request by FlorianHockmann**
The [Apache Rat](https://creadur.apache.org/rat/) Maven Plugin is used to enforce the presence of license headers. This check made it necessary to add a license header to files where such a header was missing.

The PowerShell script I used to add the missing license headers is included in the commit message.

This check lets the build fail immediately if a source file has no license header. I excluded docs (and some other files) here as they don't have a license header at the moment and it seems to be not necessary for them to have one.

Fixes #525

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [-] Have you written and/or updated unit tests to verify your changes?
- [-] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [-] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [-] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [-] Have you ensured that format looks appropriate for the output in which it is rendered?
- [-] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by chupman** [comment]
Hey @FlorianHockmann, I just ran the check on your branch and I still see 5 failures. 

```
5 Unknown Licenses

*****************************************************

Files with unapproved licenses:

  janusgraph-hbase-parent/janusgraph-hbase-server/conf/hadoop-metrics.properties
  janusgraph-hbase-parent/janusgraph-hbase-server/conf/log4j.properties
  janusgraph-hbase-parent/janusgraph-hbase-098/conf/whirr-hbase.properties
  janusgraph-hbase-parent/janusgraph-hbase-098/conf/hadoop-metrics.properties
  janusgraph-hbase-parent/janusgraph-hbase-098/conf/log4j.properties

*****************************************************
```

I think it would be really nice to add this to travis. If it can run without errors we can just throw `mvn org.apache.rat:apache-rat-plugin:check` somewhere in `.travis.yml` and it'll be one less thing we need to worry about going forward.

Also, nice work and thanks for doing this.

**Comment by FlorianHockmann** [comment]
Did you execute `mvn clean` first? I think those files shouldn't be present on the `0.3` branch any more.

> I think it would be really nice to add this to travis.

This will be run as part of the usual Maven build in the `validate` phase. So, it is included in every build automatically, both locally and on Travis.

**Comment by chupman** [comment]
Running `mvn clean validate` (or clean install) I'm still seeing these three:
  janusgraph-hbase-parent/janusgraph-hbase-098/conf/whirr-hbase.properties
  janusgraph-hbase-parent/janusgraph-hbase-098/conf/hadoop-metrics.properties
  janusgraph-hbase-parent/janusgraph-hbase-098/conf/log4j.properties

**Comment by FlorianHockmann** [comment]
I also just had some errors with this check while merging, so I added more exclusions:

```xml
<exclude>**/.classpath</exclude>
<exclude>**/.project</exclude>
<exclude>**/.settings/**</exclude>
```

If we get more errors in the future, especially from files that are auto-generated, then we can just add more of these exclusions.

**Pull request merged**
