### PR TITLE
Remove unused java classes to improve test coverage

### PR DESCRIPTION
**Pull request by li-boxuan**
I have checked that JanusGraph is not using the classes removed in this PR by using Intellij to find usage and searching the class name in the codebase. There are still some unused classes that I am not 100% sure whether some users are using, e.g. AllEdgesIterable, thus not included in this PR.

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by farodin91** [comment]
We could remove also janusgraph-core/src/main/java/org/janusgraph/graphdb/schema

**Comment by li-boxuan** [comment]
> We could remove also janusgraph-core/src/main/java/org/janusgraph/graphdb/schema

Thanks, I found out they are only used by tests. Thus I moved them to janusgraph-backend-testutils module.

**Comment by farodin91** [comment]
If we want to remove SchemaProvider, than we should remove also test for it.

https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java#L1169-L1184

I could create also different PR for and mark it as deprecated in 0.6 and we can removed after completely.

**Comment by li-boxuan** [comment]
> I could create also different PR for and mark it as deprecated in 0.6 and we can removed after completely.

Sure, I have reverted my commit to the previous one.

**Review by farodin91 — APPROVED** [review]
LGTM! Thank you for looking for these cases.

**Pull request merged**
