### PR TITLE
CQLStoreFeature updated - AWSKeyspace supports cell level TTL

### PR DESCRIPTION
**Pull request by abhirj87**
AWSKeyspace now supports TTL. So updating the feature builder accordingly

Fixes: https://github.com/JanusGraph/janusgraph/issues/3325

### CODE REVIEW

**Review by li-boxuan — APPROVED** [review]
Thanks for bringing this up. I have tested it out and verified TTL works. A side note would be we have to make sure we add

```
ALTER TABLE my_table WITH CUSTOM_PROPERTIES={'ttl':{'status': 'enabled'}};
```

```java
mgmt = graph.openManagement()
tweet = mgmt.makeVertexLabel('tweet').setStatic().make()
mgmt.setTTL(tweet, Duration.ofMinutes(5))
mgmt.commit()
g.addV("tweet").next()
g.tx().commit()
```
The vertex gets auto-deleted after 5 minutes.

**Comment by li-boxuan** [comment]
It would make more sense to target this to the v0.6 branch, but I can do that after this PR is merged.

**Comment by abhirj87** [comment]
> Thanks for bringing this up. A side note would be we have to make sure we add
> 
> ```
> ALTER TABLE my_table WITH CUSTOM_PROPERTIES={'ttl':{'status': 'enabled'}};
> ```
> 
> I have tested it out and verified TTL works:
> 
> ```java
> mgmt = graph.openManagement()
> tweet = mgmt.makeVertexLabel('tweet').setStatic().make()
> mgmt.setTTL(tweet, Duration.ofMinutes(5))
> mgmt.commit()
> g.addV("tweet").next()
> g.tx().commit()
> ```
> 
> The vertex gets auto-deleted after 5 minutes.

thanks a lot!!

**Comment by abhirj87** [comment]
Merging is still blocked. Because of few problems. Don't know why this is failing https://github.com/JanusGraph/janusgraph/actions/runs/3522538141/jobs/5928302083 Is there a way to rerun this?

**Review by porunov — APPROVED** [review]
I didn't test it but the change makes sense to me as @abhirj87 and @li-boxuan tested it already. LGTM. Thank you @abhirj87 !

**Comment by abhirj87** [comment]
Thank you! @porunov

**Pull request merged**
