### PR TITLE
Fix doc on Vertex-centric edge indexing [skip ci]

### LINKED ISSUE #1515: Mistake in section 9.2 of the documentation
Section 9.2 of the Janusgraph Documentation has the following:

Building a vertex-centric index by time speeds up such traversal queries.

```groovy
graph.tx().rollback()  //Never create new indexes while a transaction is active
mgmt = graph.openManagement()
time = mgmt.getPropertyKey('time')
battled = mgmt.getEdgeLabel('battled')
mgmt.buildEdgeIndex(battled, 'battlesByTime', Direction.BOTH, Order.decr, time)
mgmt.commit()
//Wait for the index to become available
mgmt.awaitGraphIndexStatus(graph, 'battlesByTime').call()
//Reindex the existing data
mgmt = graph.openManagement()
mgmt.updateIndex(mgmt.getGraphIndex("battlesByTime"), SchemaAction.REINDEX).get()
mgmt.commit()
```

The following line might be incorrect. It gives a null pointer exception.

```groovy
mgmt.updateIndex(mgmt.getGraphIndex("battlesByTime"), SchemaAction.REINDEX).get()
```

Instead the correct line I suppose is:

```groovy
mgmt.updateIndex(mgmt.getRelationIndex("battlesByTime"), SchemaAction.REINDEX).get()
```

### PR DESCRIPTION
**Pull request by darwinyip**
Closes #1515

### CODE REVIEW

**Comment by porunov** [comment]
@darwinyip Thanks for the contribution!

There is a requirement that each contributor must sign a CLA. It isn't automate right now but JanusGraph members are working on it.

To contribute you should:
1. Sign a CLA. Instructions are here: https://github.com/JanusGraph/legal/blob/master/README.md
2. Follow this instructions: https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md

Please feel free to ask any questions if you have some.

**Comment by mbrukman** [comment]
@darwinyip — please also note that the email used in this commit:

> ```
> From: Darwin Yip <darwinyip@users.noreply.github.com>
> ```

differs from [the one in the CLA](https://github.com/JanusGraph/legal/pull/145), and they need to match for the CLA check to go through.

Please see https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#configure-your-repo-to-match-the-cla to fix it (which will also fix the DCO check as well, via the `-s` flag).

**Comment by darwinyip** [comment]
@mbrukman Fixed

**Comment by farodin91** [comment]
@darwinyip Could change the commit message from [skip ci] to [doc only]? We updated our build system.

@porunov @mbrukman Why did our new cla didn't show anything?

**Comment by porunov** [comment]
@jmertic Do you know why our new cla didn't show anything?

**Comment by porunov** [comment]
@jmertic I mean there is no comment from from EasyCLA in this PR. I.e. something like this one https://github.com/JanusGraph/janusgraph/pull/1753#issuecomment-523839573
Can trigger EasyCLA to check old PRs?

**Comment by porunov** [comment]
@darwinyip have you signed CLA? I would suggest to close this PR and open a new identical PR. After that you will be able to sign CLA online instead of manual signing

**Pull request closed without merging**
