### PR TITLE
remove unused imports (reduce eclipse warnings)

### PR DESCRIPTION
**Pull request by amcp**

### CODE REVIEW

**Comment by jerryjch** [comment]
LGTM  
How did you grep all the un-used imports? A global search?
Also, can you open an Issue for this PR?

**Comment by amcp** [comment]
Sure, ill open an issue for eclipse warnings (there are a few PR in flight for them). All I did was sort eclipse warnings and right-clicked on the entire list of unused imports.

**Comment by amcp** [comment]
fixes part of #113

**Comment by jerryjch** [comment]
LGTM You are ready to go @amcp (after resolving conflicts).

**Pull request merged**
