### PR TITLE
Add IgnorePropertySchemaMaker

### LINKED ISSUE #2162: Provide option to ignore unknown properties
**Describe the feature:**
When DefaultSchemaMaker is used, any unknown property (that has not yet been defined explicitly) will be defined implicitly automatically. When DisableSchemaMaker is used, any unknown property will lead to an exception. It would be nice to have a solution somewhere in the middle which allows unknown property but simply overlooks it. The benefit is no exception will be thrown.

**Describe a specific use case for the feature:**
In our case, we have programs that periodically pull data from other sources and then persist in the graph. We definitely don't want the process to fail when there are new fields (properties) showing up in the data source. We would like to simply ignore these properties.

### PR DESCRIPTION
**Pull request by li-boxuan**
The new SchemaMaker works almost like DisableSchemaMaker that disables
automatic schema creation, but it allows and simply ignores unknown
properties.

Closes #2162

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by li-boxuan** [comment]
After adding `schema.default=ignore-prop` to config file, it works like this:

```groovy
gremlin> graph = JanusGraphFactory.open('conf/janusgraph-inmemory.properties')
==>standardjanusgraph[inmemory:[127.0.0.1]]
gremlin> mgmt = graph.openManagement()
==>org.janusgraph.graphdb.database.management.ManagementSystem@7209ffb5
gremlin> name = mgmt.makePropertyKey('nickname').dataType(String.class).cardinality(Cardinality.SET).make()
==>nickname
gremlin> p4 = mgmt.makePropertyKey('p4').dataType(Integer.class).make()
==>p4
gremlin> follow = mgmt.makeEdgeLabel('follow').make()
==>follow
gremlin> mgmt.commit()
==>null
gremlin> g = graph.traversal()
==>graphtraversalsource[standardjanusgraph[inmemory:[127.0.0.1]], standard]
gremlin> v1 = g.addV().property("name", "robert").property("nickname", "bob").next()
==>v[4320]
gremlin> g.V(v1).property("p3", 3).property("p4", 4).property("p5", 5)
==>v[4320]
gremlin> v2 = g.addV().next()
==>v[8416]
gremlin> e = g.V(v1).addE('follow').to(v2).next()
==>e[1zw-3c0-2dx-6hs][4320-follow->8416]
gremlin> g.E(e).property("unknown_prop", 0).property("p4", 3)
==>e[1zw-3c0-2dx-6hs][4320-follow->8416]
gremlin> g.V(v1).valueMap()
==>[nickname:[bob],p4:[4]]
gremlin> g.E(e).valueMap()
==>[p4:3]
```

**Review by farodin91 — APPROVED** [review]
@li-boxuan Thank you for the PR. I really like the idea. LGTM!

**Comment by li-boxuan** [comment]
@farodin91 Would you be able to review again? I just added some new test cases and also separate/rewrote some existing test cases.

**Review by farodin91 — APPROVED** [review]
LGTM! Thank you @li-boxuan.

**Pull request merged**
