### PR TITLE
Cover ReadConfigurationBuilder with unit tests

### PR DESCRIPTION
**Pull request by porunov**
Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

This PR is related to a flow to improve test coverage of the old `GraphDatabaseConfiguration`.
Related to #1148 and #1347

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by porunov** [comment]
@chupman Will you be able to review this PR?

**Comment by chupman** [comment]
Going to restart this [job](https://travis-ci.org/JanusGraph/janusgraph/jobs/499561728) just to see if it fails again. In the event it passes I wanted to note the NullPointerException.
 
```
[ERROR] Tests run: 93, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 430.252 s <<< FAILURE! - in org.janusgraph.graphdb.thrift.ThriftGraphCacheTest
[ERROR] testVertexTTLImplicitKey  Time elapsed: 2.829 s  <<< ERROR!
java.lang.NullPointerException
```

**Comment by porunov** [comment]
I am going to merge this PR in 2 days unless anyone wants to make a review.

**Comment by chupman** [comment]
I'll carve out some time on Monday to do PR reviews. Sorry I've been pretty backed up the last 2 weeks and haven't found time to look at the open PRs.

**Comment by porunov** [comment]
@chupman Thank you for the review. I've changed the scope of those variables. When the travis is finished I will merge it.

**Pull request merged**
