### PR TITLE
Added a Travis CI badge.

### PR DESCRIPTION
**Pull request by mbrukman**
Click on the "View" button in the diffs to see the rendered view on my branch.

### CODE REVIEW

**Comment by mbrukman** [comment]
@sjudeng – looks like `berkeleyje` is now failing: https://travis-ci.org/JanusGraph/janusgraph/jobs/198165185

Should we switch it to a single-thread test suite, or is this a deeper problem?

**Comment by sjudeng** [comment]
Unfortunately I think it's a deeper problem. I know I saw sporadic failures running tests in Travis in all but the janusgraph-test module. You can try going to single thread but that was a shot in the dark on my part and it didn't consistently resolve the issue for me. For now I'd recommend dropping back to just running tests for janusgraph-test in master. Otherwise I suspect you'll see this (e.g. build failures not related to PR) more often then not.

Meanwhile you might keep one of your existing automated test issues open or create a new one to track the effort to try and understand what the issue is and if there are any workarounds.

**Comment by mbrukman** [comment]
@sjudeng – turns out, it's possible to mark a specific job as `allowed_failure`, so I've just done this for `berkeleyje`, and let's see what happens. If needed, we can mark the `lucene` similarly.

Unfortunately, this requires a top-level `matrix` section, which previously conflicted with our nested

```
env:
  matrix:
    ...
```

section, so we may need to remove it if this doesn't quite work.

**Comment by mbrukman** [comment]
Looks like it nicely separates required from allowed failures: https://travis-ci.org/JanusGraph/janusgraph/builds/198198304 — this is awesome!

**Comment by sjudeng** [comment]
Yeah that's perfect. For diagnosing the sporadic fail issue it will be great to have history on the failures. Nice find.

**Pull request merged**
