### PR TITLE
Use larger id block size and avoid deprecated methods.

### PR DESCRIPTION
**Pull request by amcp**
I now use the default block size here. I think we need to opt-out of some tests still
Signed-off-by: Alexander Patrikalakis <amcp@amazon.co.jp>

### CODE REVIEW

**Comment by amcp** [comment]
Fixes #243

**Comment by analytically** [comment]
I think this can be merged now.

**Comment by sjudeng** [comment]
@analytically I thought there were a number of test failures in the TinkerPop suite with this update as is. @amcp Can you confirm?

**Comment by sjudeng** [comment]
@amcp @analytically I (finally) ran through the whole suite myself with this commit (rebased on master) and all tests passed. Thanks for fixing this (and sorry that I caused the issue)!

**Pull request merged**
