### PR TITLE
Get rid of the Titan-oriented introduction ('JanusGraph of time')

### PR DESCRIPTION
**Pull request by JoelSanchez**
Doesn't make much sense now IMHO.

### CODE REVIEW

**Comment by pluradj** [comment]
LGTM, pending [CLA signing](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md).
Thanks for the contribution @JoelSanchez !

**Comment by pluradj** [comment]
@JoelSanchez have you submitted a CLA?

**Comment by JoelSanchez** [comment]
@pluradj I know I have to submit a CLA but I need access to a printer (mine's broken), so I'll have to go somewhere to print it, haven't done it yet

@mbrukman I agree.

**Comment by mbrukman** [comment]
@JoelSanchez — sorry for the inconvenience! Haven't had time to make the CCLA / ICLA process electronic yet, but plan to do so in the future. Please submit a paper CLA at your convenience.

Also, please note that if you're affiliated with an organization (e.g., via employment) such that they may have claim over your IP, you need them to sign an CCLA rather than you signing an ICLA.

**Comment by mbrukman** [comment]
@JoelSanchez – We'll be wrapping up the work for the first release (v0.1.0) and it would be great to have this change in before then. Any chance you'll be able to submit a CLA so we can review + merge this PR?

**Comment by JoelSanchez** [comment]
@mbrukman I'll send it today

**Comment by JoelSanchez** [comment]
@mbrukman Sent it, I've removed another paragraph too
Greets

**Comment by jerryjch** [comment]
@mbrukman Are you able to process the CLA?
This looks like a nice to have in 0.1.0.

**Comment by mbrukman** [comment]
@JoelSanchez — the email address you submitted on your CLA does not match the email address used in this commit, which you can see via https://patch-diff.githubusercontent.com/raw/JanusGraph/janusgraph/pull/156.patch

Also, you need to add a `Signed-off-by:` line to your commit as specified in the [`CONTRIBUTING.md` guide](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#commit-changes-and-sign-the-developer-certificate-of-origin), this is done via `git commit -s` during the initial commit.

You can fix both of these issues by following [these instructions](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#configure-your-repo-to-match-the-cla).

You need to do this for each of the two commits in your PR, or you can squash them into a single commit to make it easier via `git rebase -i HEAD~2` and then you only have to deal with a single commit.

Let me when you've done this and selected your preferred email address and we'll address the CLA issue. 

Thanks again for the fixes!

**Comment by JoelSanchez** [comment]
@mbrukman All fixed, I want to use the email address I used in the CLA and in the new commit (webmaster@kazer.es)

Greets

**Pull request merged**
