### PR TITLE
Add Target as a production user [doc only]

### LINKED ISSUE #1781: Add Target as a production user
[Target](http://target.com) is using JanusGraph in production for internal use cases. More information can be found in the second presentation of the JanusGraph meetup №2:
https://training.experoinc.com/janus-meetup-august7/

### PR DESCRIPTION
**Pull request by porunov**
Fixes #1781

@aploetz Please, tell if you and Becky Nelson approve to list Target as a production user.

Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?
- [x] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by FlorianHockmann** [comment]
I think we always ask the responsible employees of the company in question whether it's OK to list them. (See for example PRs #478 and #1020.) It would be good to have someone from Target review and approve this PR, ideally @aploetz or Becky Nelson who gave the talk at the meetup.

**Comment by aploetz** [comment]
Let me forward that along.  I know our legal dept can be picky about things like this.

Hang on...I’ll get back to you on this.

Thanks!

Aaron

**Comment by porunov** [comment]
@aploetz Is there any news? We got approval to use Target logo on `janusgraph.org` from Target Vendor Tagging Compliance. Do we need to ask their permission for this PR also?

**Comment by li-boxuan** [comment]
@aploetz I know this thread might be too old, but... is there any update?

**Comment by aploetz** [comment]
This is a definite "no" from Target legal.  Also, it would be great if our
logo could be removed from this page:

https://janusgraph.org/

Thanks,

Aaron

**Comment by porunov** [comment]
@aploetz Could you please confirm that Target legal asked to remove logo from the JanusGraph website?
We got an approval from Target legal to show that logo on janusgraph.org earlier. In case Target legal decided to remove the logo we will definitely remove it but we never received such a request from them.

We received the approval from VendorTaggingCompliance@target.com on 10/8/2019. Please, let us know if that isn't valid anymore

**Comment by porunov** [comment]
Closing the PR with wait for confirmation of #80

**Pull request closed without merging**
