### PR TITLE
Fixing Issue #4401

### PR DESCRIPTION
**Pull request by Eric-Chng**
### For all changes:
Issue associated: https://github.com/JanusGraph/janusgraph/issues/4401

For unit testing, try commenting out the 1 line fix in OrderedKeyValueStoreAdapter and run the test to see the error. Uncomment the 1 line fix and run test to see expected correct behavior.

### For code changes:
- [Y ] Have you written and/or updated unit tests to verify your changes?
- [N/A ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ N/A] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ N/A] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [N/A ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Review by li-boxuan — APPROVED** [review]
This is great! Cannot imagine this evident bug has existed in the codebase for such a long time :) Glad that you found it out.

**Comment by Eric-Chng** [comment]
> li-boxuan

Glad to contribute! I started working on janusgraph pretty recently and actually read your 3 part janusgraph deep dive to help me learn and understand things better! Really cool to see you comment on this PR :)

**Review by porunov — APPROVED** [review]
LGTM. Thank you @Eric-Chng !

**Comment by Eric-Chng** [comment]
Minor change to fix some of the code coverage/styling issues. Hopefully that helps the test pass all the checks now 👍

**Comment by janusgraph-automations** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v1.0|[](https://github.com/JanusGraph/janusgraph/pull/4417)|

Note: Successful backport PRs will be merged automatically after passing CI.

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/JanusGraph/janusgraph/actions/runs/8852579369) for details

**Pull request merged**
