### PR TITLE
Remove duplicate addProperty calls in StandardJanusGraphTx:: makeSchemaVertex

### LINKED ISSUE #2613: Duplicate addProperty calls in StandardJanusGraphTx:: makeSchemaVertex
Maybe this isn't a bug,Just my mistake(If so, sorry)

In StandardJanusGraphTx class
 makeSchemaVertex(JanusGraphSchemaCategory, String, TypeDefinitionMap) function
...
        updateSchemaVertex(schemaVertex);
        addProperty(schemaVertex, BaseKey.SchemaUpdateTime, times.getTime(times.getTime()));
...

line 1 is: add a "SchemaUpdateTime" property for this schemaVertex,
but line 2 is also,
Must we add two same property for this vertex???

### PR DESCRIPTION
**Pull request by li-boxuan**
Closes #2613

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Review by porunov — COMMENTED** [review]
(nitpick) I would prefer to remove `addProperty(schemaVertex, BaseKey.SchemaUpdateTime, times.getTime(times.getTime()));` instead of `updateSchemaVertex(schemaVertex)` to reduce code duplication

**Comment by li-boxuan** [comment]
@porunov I was trying to be 100% sure that we don't accidentally change the behavior, so I removed the first and retained the second one.

`updateSchemaVertex(schemaVertex)` calls

`addProperty(VertexProperty.Cardinality.single, schemaVertex, BaseKey.SchemaUpdateTime, times.getTime(times.getTime()));`

which is not exactly the same as 

`addProperty(schemaVertex, BaseKey.SchemaUpdateTime, times.getTime(times.getTime()))`

They are equivalent iff schemaVertex is always of SINGLE cardinality. It seems to be the case, but I am not 100% sure about that.

**Comment by porunov** [comment]
`SchemaUpdateTime` has cardinality `Cardinality.SINGLE`.
```
public static final BaseKey SchemaUpdateTime =
            new BaseKey("SchemaUpdateTimestamp", Long.class, 36, Index.NONE, Cardinality.SINGLE);
```
The cardinality is `final`. Thus, calling `addProperty(schemaVertex, BaseKey.SchemaUpdateTime, times.getTime(times.getTime()))` will essentially call `addProperty(VertexProperty.Cardinality.single, schemaVertex, BaseKey.SchemaUpdateTime, times.getTime(times.getTime()))`.

Unless I miss anything, the execution of those methods are the same.

**Comment by li-boxuan** [comment]
> SchemaUpdateTime has cardinality Cardinality.SINGLE.

You are right, I somehow missed that earlier.

**Review by porunov — APPROVED** [review]
LGTM. Thank you @li-boxuan !

**Pull request merged**
