### PR TITLE
Cleanup maven

### PR DESCRIPTION
**Pull request by farodin91**
* Remove shading
* Remove bunch of maven plugins
* Remove bunch of unsed dependencies
* Bump maven version requirement

Signed-off-by: Jan Jansen <jan.jansen@gdata.de>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by porunov** [comment]
I would like to check the release flow to confirm everything works but I'm currently blocked by #2379 (not related to this PR)

**Comment by farodin91** [comment]
I can execute it on this branch on my machine and does work fine.

**Comment by porunov** [comment]
I tried to build janusgraph release using this PR on Fedora 32. Everything worked as expected. I also tested janusgraph-full release with all examples from https://docs.janusgraph.org/master/getting-started/basic-usage/ - everything worked.

I tried to use JanusGraph embedded into Java application with some integration tests. We are using Spring framework but for some reason tests are just not started. I guess, there are some dependencies problems I need to resolve. 
Right now I'm getting infinite OOM exceptions without any meaningful logs.
```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 108"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 512"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 299"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 358"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-33-thread-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "I/O dispatcher 156"
```
I also find that `JanusGraphElasticsearchContainer` is not available anymore. 
Again, I didn't investigate anything deep yet. It is just something I tried very quickly, so maybe I just did something wrong somewhere

**Comment by porunov** [comment]
Okay, I'm seeing the same just behaviour with master branch. I think it is related to my local environment.

**Comment by porunov** [comment]
Problems described [here](https://github.com/JanusGraph/janusgraph/pull/2378#issuecomment-766223498) were caused by my local environment problems not related to JanusGraph

**Review by porunov — APPROVED** [review]
LGTM. Thank you @farodin91 !

Tested build and release build. Tested changes with custom integration tests in embedded mode (ScyllaDB + ElasticSearch). Tested janusgraph-full build with all queries from `Basic Usage` documentation (Cassandra + ElasticSearch).

**Pull request merged**
