### PR TITLE
Update version compatibility table for 0.1.0 release

### PR DESCRIPTION
**Pull request by mbrukman**
Partially addresses issue #102 (for HBase only) as part of the upcoming 0.1.0
release.

### CODE REVIEW

**Comment by mbrukman** [comment]
@jerryjch — done for both. Bigtable has only a single version ("live"); noted as such in the docs.

**Comment by sjudeng** [comment]
Can you also change the TinkerPop version to 3.2.x?

**Comment by jerryjch** [comment]
Good point.  Should be in both jg01 and master.

**Comment by mbrukman** [comment]
My recommendation would be to commit to `master` and then to cherry-pick / merge manually into the release branch.

I don't think we can just commit to a release branch and merge it into `master` (or _vice versa_) as `master` will quickly diverge from a release branch, at which point it won't cleanly merge in either direction.

**Comment by sjudeng** [comment]
I think the release branch can always be merged into master but not the other way around. Can we work through this on the dev list?

Also regarding Bigtable version @jerryjch made a comment on this in #184 and here I see you're using version "live" but on [Maven central](https://search.maven.org/#search%7Cga%7C1%7Cbigtable) and in [bigtable.txt](https://github.com/JanusGraph/janusgraph/blob/e41daefe3eca0f4de951c9468c1e78d1862e71ce/docs/bigtable.txt#L40) I see versions of the form 0.9.x.

**Comment by mbrukman** [comment]
@sjudeng — sorry for the delay, I was out for a few days. Will update this PR as follows:

* rebase on the `0.1` branch
* change Bigtable to 0.9.x (good point)
* change TinkerPop to 3.2.x

**Comment by mbrukman** [comment]
@sjudeng — do you want to re-review this PR given the changes I made after your approval?

**Comment by sjudeng** [comment]
LGTM!

**Pull request merged**
