### PR TITLE
[0.4 is blocked] WIP: Merge 0.3 branch

### PR DESCRIPTION
**Pull request by porunov**
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by porunov** [comment]
@mad Please verify that I have merged your changed correctly into `0.4` branch because there were a lot of conflicts during the merge.

**Comment by porunov** [comment]
@mbrukman Looks like there is something with branch settings because `0.4` branch now requires 1 approving review which make impossible to follow `lazy consensus` for commits from committers. Please disable this requirement.

**Comment by mad** [comment]
@porunov LGTM

**Comment by porunov** [comment]
@mad To not block you I've merged this PR into master branch.

The branch `0.4` is now inconsistent and should be fixed by TSC members.

**Comment by porunov** [comment]
@FlorianHockmann @pluradj @mbrukman I am asking to unblock the branch `0.4` (branch protection).

**Comment by mbrukman** [comment]
@porunov — fixed, sorry about that. I added a new protection to `0.*` wildcard (which covers `0.4` branch, and will automatically cover all future `0.y` branches without having to create a separate policy) and checked the box which requires a pull request before merging. I unchecked the box and saved settings, so you should be good to go now.

**Comment by porunov** [comment]
@mbrukman Thank you! It works now

**Pull request merged**
