### PR TITLE
Bump Lucene Solr to 8.7.0

### PR DESCRIPTION
**Pull request by porunov**
Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Review by farodin91 — APPROVED** [review]
LGTM! Thank you.

**Comment by porunov** [comment]
Looks like something is changed in Solr 8.8.1 because I'm getting the next error in GH actions:

```
Error:  Failures: 
Error:    BerkeleySolrTest>JanusGraphIndexTest.testListDeleteAddInOneTransaction:513 expected: <0> but was: <1>
Error:    CQLSolrTest>JanusGraphIndexTest.testListDeleteAddInOneTransaction:513 expected: <0> but was: <1>
Error:  Errors: 
Error:    SolrIndexWithoutKerberosTest>IndexProviderTest.multipleStores:185->IndexProviderTest.storeTest:512->IndexProviderTest.clopen:169->IndexProviderTest.close:164 » JanusGraph
Error:    SolrIndexWithoutKerberosTest>IndexProviderTest.singleStore:180->IndexProviderTest.storeTest:512->IndexProviderTest.clopen:169->IndexProviderTest.close:164 » JanusGraph
Error:    SolrIndexWithoutKerberosTest>IndexProviderTest.testAddFieldThenDeleteDoc:929->IndexProviderTest.runConflictingTx:876 » JanusGraph
```

That said, when running those tests separately in my local environment, they work as expected.

**Comment by porunov** [comment]
Looks like it's not related to the client Solr library but to Solr server (docker container) because when running with lib 8.8.1 and Solr server 8.5.2 - all tests pass. When we bump Solr container to 8.8.1 - some Solr related tests fail.

**Comment by porunov** [comment]
Solr 8.7.0 works. After updating server (docker container) to 8.8.0 - the above errors happen in tests.
Most likely some configuration could be changed in Solr 8.8.0 which causes such behavior.

**Comment by porunov** [comment]
@farodin91 
Looks like 8.8.0 and 8.8.1 versions of Solr seems to not be fully compatible with JanusGraph right now. At least some tests are failing and it's not obvious why they are failing right now.
Thus, I changed this PR to upgrade Solr to 8.7.0 version instead of 8.8.1. Let me know if that's OK. We could try to work in a separate PR to upgrade Solr to 8.8.1.

**Comment by farodin91** [comment]
Sounds okay for me

**Comment by porunov** [comment]
Looks like Solr update is tricky. If I bump versions to `8.7.0` - HBase tests take forever to run. If I bump Solr to `8.8.0` or `8.8.1` then the next tests are failing: https://github.com/JanusGraph/janusgraph/pull/2526#issuecomment-805927916 
Thus, I'm closing this PR as for now. If I manage to find a solution to update Solr, I will open a new PR but for now I think that's fine to leave it as is.

**Comment by li-boxuan** [comment]
I tried bumping to 8.7.0 earlier as well - encountered the same error and gave up after some trial.

**Pull request closed without merging**
