### PR TITLE
Fix doc on Vertex-centric edge indexing [doc only]

### PR DESCRIPTION
**Pull request by darwinyip**
Fix for #1515 
Signed-off-by: Darwin Yip <yip.darwin@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?
- [x] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by darwinyip** [comment]
@porunov I've reopened this as a new PR but still `cla: no`. Here is the legal PR with the CLA info https://github.com/JanusGraph/legal/pull/145 which matches.

**Comment by porunov** [comment]
@darwinyip looks like github doesn't recognize you with email `yip.darwin@gmail.com`. Is it bind to your github account? If no, you should bind this email so that github recognize you (darwinyip) as a committer.

**Comment by porunov** [comment]
@darwinyip Go to your github `Settings`. Then click `Emails` and add additional email `yip.darwin@gmail.com`

**Comment by darwinyip** [comment]
@porunov Good call! That was the issue.

**Comment by porunov** [comment]
@darwinyip I think we can merge this commit with CTR. Also, I think it would be better if this commit would go to all branches. Can you retarget your commit into `v0.2` branch and add `CTR` line into the message of the commit?

1) Add JanusGraph as upstream
`git remote add upstream https://github.com/JanusGraph/janusgraph`

2) Fetch everything
`git fetch --all`

3) Make a new branch
`git checkout -b fix-vertex-centric-doc`

4) Make the branch identical to current `v0.2` branch
`git reset --hard upstream/v0.2`

5) Pick your commit
`git cherry-pick 54c86975783dd370fa558bed8c49a8447d136152`

6) Add CTR line to your commit message
`git commit --amend -s`

The commit message should look something like 
```
Fix doc on Vertex-centric edge indexing [doc only]

CTR
Fixes #1515

Signed-off-by: Darwin Yip <yip.darwin@gmail.com>
```

7) Push your branch
`git push --set-upstream origin fix-vertex-centric-doc`

8) Open a new PR to merge changes from `fix-vertex-centric-doc` into `v0.2`.

After that I will be able to instantly merge your PR into all branches.

**Pull request merged**
