### PR TITLE
Remove HBase 0.94 support

### PR DESCRIPTION
**Pull request by jerryjch**
#36 Remove HBase 0.94 support

### CODE REVIEW

**Comment by jerryjch** [comment]
@mbrukman 
Is the 'cla:no' because I used a different email in the commit?

**Comment by hsaputra** [comment]
Yeah, it has to use the same name you used in the ICLA

**Comment by mbrukman** [comment]
@jerryjch:

* by "deprecate", I believe you actually mean "delete" — deprecate doesn't remove code, just marks it as `@deprecated` or similar
* @hsaputra is correct: the email address used in this commit does not match the one on the CCLA, which are listed in [this file](https://github.com/JanusGraph/legal/blob/master/CLA_SIGNERS.yaml)
* you also did not add the `Signed-off-by: ...` line as per the DCO requirement from The Linux Foundation

My recommendations:

* rename this issue: s/Deprecate/Delete/ (or Remove), similarly for PR and commit descriptions
* change the email used by default in your local repo clone:

   ```bash
   git config user.email ...     # as per CCLA
   ```

* update the commit (both description + email)

   ```bash
   git commit -s --amend
   ```

   This will let you edit the commit description, and will auto-update the email address at the same time to use the one in your config. The `-s` flag will add the `Signed-off-by` line. To make this easier, see the instructions in [`CONTRIBUTING.md`](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md) — search for `alias`.

* update this PR in-place:

   ```bash
   git push -f
   ```

Once you do this, @janusgraph-bot will review the commit and update the tags accordingly.

**Comment by jerryjch** [comment]
@mbrukman Thanks for inputting. I updated the PR title, issue title, etc to 'Remove HBase 0.94 support'.
Use sign-off and amend the commit.

**Comment by jerryjch** [comment]
Had to use git commit -s --amend --reset-author
to get the email from the new git config.

**Comment by jerryjch** [comment]
@mbrukman Looks like my merge permission is not up yet.
Also from the command like, it got rejected as well:

remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.
To git@github.com:JanusGraph/janusgraph
 ! [remote rejected] upstream-master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:JanusGraph/janusgraph'

Could you check my permission?

**Comment by mbrukman** [comment]
@jerryjch try again?

**Comment by jerryjch** [comment]
@mbrukman The command line push still does not work. But merge PR worked.  Thanks.

**Pull request merged**
