### PR TITLE
Handle migration scenario where ES multitype is not set

### LINKED ISSUE #591: ES: useMultitypeIndex is not set to true on migrated JanusGraph instance
Testing out a migration from JanusGraph 0.1.1 to JanusGraph 0.2.0 with Elasticsearch 1.5.1, ran into this when opening up the graph:

```
java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.es.ElasticSearchIndex
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:69)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:477)
	at org.janusgraph.diskstorage.Backend.getIndexes(Backend.java:464)
	at org.janusgraph.diskstorage.Backend.<init>(Backend.java:149)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1897)
	at org.janusgraph.graphdb.database.StandardJanusGraph.<init>(StandardJanusGraph.java:136)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:164)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:133)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:80)
	at org.janusgraph.core.JanusGraphFactory$open.call(Unknown Source)
	... more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58)
	... 54 more
Caused by: java.lang.IllegalArgumentException: The key 'root.index.elasticsearch.use-deprecated-multitype-index' cannot be false when existing index contains multiple types.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.<init>(ElasticSearchIndex.java:235)
	... 59 more
```

For a migrated graph, [`useMultitypeIndex`](https://github.com/JanusGraph/janusgraph/blame/master/janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java#L202) should be set to true.

### PR DESCRIPTION
**Pull request by pluradj**
Fixes #591

Signed-off-by: Jason Plurad <pluradj@us.ibm.com>

Thank you for contributing to JanusGraph.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there an issue associated with this PR? Is it referenced in the commit message?
- [X] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [] Have you written and/or updated unit tests to verify your changes?
- [] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jerryjch** [comment]
The Solr-7 seems to be failing on Travis occasionally.

**Comment by pluradj** [comment]
@jerryjch Yea, I couldn't figure a simple way to add a JUnit test. It was a bit of a chicken and egg problem because the property is set in the constructor, the property is `GLOBAL_OFFLINE`, and there is no way to remove a property from the configuration once it is stored in the graph. If anybody has a good idea on how to add a test, I'm all ears.

Random Solr 7 failures have nothing to do with this code change.

**Comment by pluradj** [comment]
@jerryjch correct

**Comment by robertdale** [comment]
VOTE +1
This test passes:
```
import org.janusgraph.diskstorage.configuration.TransactionalConfiguration;
import org.janusgraph.diskstorage.configuration.ModifiableConfiguration;
import static org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.*;
import org.janusgraph.diskstorage.configuration.BasicConfiguration;
import static org.janusgraph.diskstorage.es.ElasticSearchIndex.*;

// Get and Set to true (default is false)
graph = JanusGraphFactory.open('conf/janusgraph-cassandra-es.properties')
transactionalConfig = new TransactionalConfiguration(graph.getBackend().getGlobalSystemConfig())
modifyConfig = new ModifiableConfiguration(ROOT_NS, transactionalConfig, BasicConfiguration.Restriction.GLOBAL);
modifyConfig.get(USE_DEPRECATED_MULTITYPE_INDEX, "search")
modifyConfig.set(USE_DEPRECATED_MULTITYPE_INDEX, true, "search")
transactionalConfig.commit()
graph.tx().commit()
modifyConfig.get(USE_DEPRECATED_MULTITYPE_INDEX, "search")
graph.close()

// Get and Remove
graph = JanusGraphFactory.open('conf/janusgraph-cassandra-es.properties')
transactionalConfig = new TransactionalConfiguration(graph.getBackend().getGlobalSystemConfig())
modifyConfig = new ModifiableConfiguration(ROOT_NS, transactionalConfig, BasicConfiguration.Restriction.GLOBAL);
// verify true value persisted
modifyConfig.get(USE_DEPRECATED_MULTITYPE_INDEX, "search")
// Remove
modifyConfig.remove(USE_DEPRECATED_MULTITYPE_INDEX, "search")
transactionalConfig.commit()
graph.tx().commit()
// Should get default false
modifyConfig.get(USE_DEPRECATED_MULTITYPE_INDEX, "search")
graph.close()

// Verify graph can be created and get default value false
graph = JanusGraphFactory.open('conf/janusgraph-cassandra-es.properties')
transactionalConfig = new TransactionalConfiguration(graph.getBackend().getGlobalSystemConfig())
modifyConfig = new ModifiableConfiguration(ROOT_NS, transactionalConfig, BasicConfiguration.Restriction.GLOBAL);
modifyConfig.get(USE_DEPRECATED_MULTITYPE_INDEX, "search")
graph.close()
```

**Comment by robertdale** [comment]
BTW, that test fails without this change.

**Comment by pluradj** [comment]
@robertdale do you suggest we pull that code into a test case before merging?

**Comment by robertdale** [comment]
@pluradj I think you should do whatever needs to be done for code coverage :smiley_cat:

**Comment by sjudeng** [comment]
You can add the following test to ElasticSearchConfigTest. This will hit the missing branch (see [Code cov report](https://codecov.io/gh/JanusGraph/janusgraph/src/697088b1be0a1aa3be19e5e8f8033044bed99149/janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java#L233...240)).

```java

    @Test
    public void testMultiTypeUpgrade() throws InterruptedException, BackendException, IOException {
        // create multi-type index
        ModifiableConfiguration config = esr.setElasticsearchConfiguration(GraphDatabaseConfiguration.buildGraphConfiguration(), INDEX_NAME);
        config.set(USE_DEPRECATED_MULTITYPE_INDEX, true, INDEX_NAME);
        Configuration indexConfig = config.restrictTo(INDEX_NAME);
        IndexProvider idx = open(indexConfig);
        simpleWriteAndQuery(idx);
        idx.close();

        // should be able to open multi-type index if USE_DEPRECATED_MULTITYPE_INDEX is unset
        config.remove(USE_DEPRECATED_MULTITYPE_INDEX, INDEX_NAME);
        indexConfig = config.restrictTo(INDEX_NAME);
        idx = open(indexConfig);
        idx.close();
    }
```

**Pull request merged**
