### PR TITLE
Fix error with field key unique constraint violation

### PR DESCRIPTION
**Pull request by VladimirBogomolov**
Error occurs with berkeley backend

Signed-off-by: Vladimir Bogomolov <vladimir.bogomoloff@gmail.com>

-----
Resolve Issue #1916
-----

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz  where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### CODE REVIEW

**Comment by porunov** [comment]
@VladimirBogomolov could you please a test to cover this bugfix?

**Comment by VladimirBogomolov** [comment]
> @VladimirBogomolov could you please a test to cover this bugfix?
Sorry, but this is very difficult. As I wrote in my issue, this error is not 100% reproducible. But I think that due to the fact that BerkeleyJEKeyValueStore::acquLock is not implemented, data race sometimes occurs, which leads to duplication of schema nodes for schema fields. That is why this error occurs.

**Comment by porunov** [comment]
> Sorry, but this is very difficult. As I wrote in my issue, this error is not 100% reproducible. But I think that due to the fact that BerkeleyJEKeyValueStore::acquLock is not implemented, data race sometimes occurs, which leads to duplication of schema nodes for schema fields. That is why this error occurs.

I see. Yes, sometimes this is difficult to write a test case for race conditions. I would just like to understand a typical flow in which this bug happens. As I understand, sometimes we are inserting the same entry in the `ImmutableMap` and it causes conflicts.
This fix will fix the problem, but it would be good if we could understand the root of the problem. Do you know in which cases we might get this bug? As I understand, `getFieldKeys()` returns duplicate values for mixed indexes but it would be good if we could understand why it returns duplicate values and if we can prevent that.

**Comment by VladimirBogomolov** [comment]
> > Sorry, but this is very difficult. As I wrote in my issue, this error is not 100% reproducible. But I think that due to the fact that BerkeleyJEKeyValueStore::acquLock is not implemented, data race sometimes occurs, which leads to duplication of schema nodes for schema fields. That is why this error occurs.
> 
> I see. Yes, sometimes this is difficult to write a test case for race conditions. I would just like to understand a typical flow in which this bug happens. As I understand, sometimes we are inserting the same entry in the `ImmutableMap` and it causes conflicts.
> This fix will fix the problem, but it would be good if we could understand the root of the problem. Do you know in which cases we might get this bug? As I understand, `getFieldKeys()` returns duplicate values for mixed indexes but it would be good if we could understand why it returns duplicate values and if we can prevent that.

I agree that this does not eliminate the root of the problem.
The case where this happens is when I add a lot of indexes and then wait for each index to be enabled after `JanusGraphManagement :: updateIndexStatus`.
Maybe I need to investigate the problem more. I close PR and issue to more details.

**Pull request closed without merging**
