### PR TITLE
updated maven-shade version in core and codepipelines poms

### LINKED ISSUE #867: IncompatibleClassChangeError opening in-memory graph under Java 9
## Steps to reproduce:

1. Create a project with dependency `org.janusgraph:janusgraph-core:0.2.0`
    - demo project: [janus-icce](https://github.com/dmolesUC3/janus-icce)
2. Under Java 9, run the following code:

```
    JanusGraph graph = JanusGraphFactory.build().set("storage.backend", "inmemory").open();
```

## Expected:

In-memory `JanusGraph` instance is a drop-in replacement for in-memory TinkerGraph (`TinkerGraph.open()`).

## Actual:

```
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception

	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:57)

...

Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent exception while executing backend operation getConfiguration
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:82)

...

Caused by: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/janusgraph/diskstorage/StaticBuffer. Method lambda$static$0([BII)[B at index 105 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at org.janusgraph.diskstorage.StaticBuffer.<clinit>(StaticBuffer.java:79)
	at org.janusgraph.diskstorage.configuration.backend.KCVSConfiguration$1.call(KCVSConfiguration.java:105)
	at org.janusgraph.diskstorage.configuration.backend.KCVSConfiguration$1.call(KCVSConfiguration.java:100)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:148)
```

(Full stack trace in a [gist here](https://gist.github.com/dmolesUC3/e6cdcbf0bcbcb1ba60678886e2c7f6d6).)

## Environment

OS: mac OS Sierra 10.12.6 (16G1114)

Java: 9.0.1+11

```
$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

### PR DESCRIPTION
**Pull request by chupman**
resolves #867 

Completed local testing with java 9 for janusgraph-core.
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there an issue associated with this PR? Is it referenced in the commit message?
- [X] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by mbrukman** [comment]
@chupman — please add `Signed-off-by` line in your commits as specified in the `CONTRIBUTING.md` guide.

If you're making a new commit, follow these steps: https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#commit-changes-and-sign-the-developer-certificate-of-origin

If you need to amend an existing commit: https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#configure-your-repo-to-match-the-cla

**Comment by chupman** [comment]
Sorry about that @mbrukman. I added the sign off on this PR and 877 as well.

**Comment by mbrukman** [comment]
@chupman — have you had a chance to test with Java 9? Is this PR ready to be merged?

**Comment by chupman** [comment]
@mbrukman I had some trouble running the tests locally. I'm going to spend some more time today troubleshooting and going through the docs.

Also for codepipelines-ci do I need to have an AWS setup to test?

**Comment by mbrukman** [comment]
@chupman — if you're having trouble running _all_ the tests under Java 9, can you at least verify that the [original bug report](https://github.com/JanusGraph/janusgraph/issues/867#issue-286091076) fails in JanusGraph without this change, and succeeds with PR?

@amcp — can you please test the CodePipelines CI module after the changes in this PR to update one of the modules?

**Comment by chupman** [comment]
@mbrukman changes have been tested locally.

I compiled the branch locally with java8 and confirmed that the errors were no longer present after running the [use case](https://github.com/dmolesUC3/janus-icce) provided by dmolesUC3 using java 9.

**Comment by chupman** [comment]
PR note has been updated.

**Pull request merged**
