### PR TITLE
Add Sift Security blog post and slides. [skip ci]

### PR DESCRIPTION
**Pull request by mbrukman**
Link to Sift Security's blog post about the Event Graph, which is the
use case powered by JanusGraph, as well as slides from their talk.

@rcanzanese, please review and approve.

### CODE REVIEW

**Comment by mbrukman** [comment]
JanusGraph committers: even though this PR is now "green to merge", please do not merge until @rcanzanese approves. Thanks!

**Comment by FlorianHockmann** [comment]
@rcanzanese: Do you approve that we link to your blog post and the slides in our README.md?

**Comment by FlorianHockmann** [comment]
@mbrukman: Do we really need permission to add links to a blog post or to slides if we already got the permission to link the company in general?
If we really don't want to merge the PR without that, I'd suggest closing it now as it has been sitting here for nearly half a year now.

**Comment by farodin91** [comment]
The PR was now nearly two years open.

**Pull request closed without merging**
