### PR TITLE
Issue 512 Use hbase shaded client and server

### LINKED ISSUE #512: Use hbase shaded client and server
We should start using hbase shaded client to avoid dependency conflicts.
See https://issues.apache.org/jira/browse/HBASE-18800
and #488

### PR DESCRIPTION
**Pull request by jerryjch**
Fix #512 

Signed-off-by: Jerry He <jinghe@us.ibm.com>

Thank you for contributing to JanusGraph.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jerryjch** [comment]
There have been a lot of complains about the Guava version incompatible conflicts.
See the linked issue.

After the change, in the janus-graph/lib, we will have hbase-shaded-client-1.2.6.jar  and hbase-shaded-server-1.2.6.jar with many of their dependencies shaded and included within.

For example, 
`org/apache/hadoop/hbase/shaded/com/google/common/base/Stopwatch.class`

This will not solve all the problems, but at least in term of hbase, it is all shaded and included.

**Comment by jerryjch** [comment]
I could remove the `Stopwatch` and `Closeables` hack code in janusgraph-hbase-core.
But I am thinking we will remove it when we remove the hbase-098 shim in future release since 0.98 does not have a shaded client.

**Comment by jerryjch** [comment]
@sjudeng  This will make the  -Dhbase100.core.version=1.1.12  testing work too.

**Comment by jerryjch** [comment]
`mvn test -Dhbase100.core.version=1.1.12 -pl :janusgraph-hbase-10`
```
Results :

Tests in error:
  HBaseMultiWriteStoreTest>MultiWriteKeyColumnValueStoreTest.setUp:63 Â» Runtime ...

Tests run: 173, Failures: 0, Errors: 1, Skipped: 2
```
The error is same NPE I cited in PR #568 for -Dhbase100.core.version=1.1.10

**Comment by pluradj** [comment]
Wouldn't this be a good time to remove 0.98 support then?

**Comment by pluradj** [comment]
Also, I'd assume that the HBase example should use `hbase-shaded-client` also?
https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-examples/example-hbase/pom.xml#L31

**Comment by jerryjch** [comment]
@pluradj  Updated the janusgraph-examples as well.
We remove the 0.98 in the next release? There are still lot of existing 0.98 installations out there.
Or I am being too conservative? :-)

**Comment by pluradj** [comment]
No idea on usage @jerryjch. Leave it for now, but let's start a mailing list thread to remove for next release.

**Pull request merged**
