### PR TITLE
issue-357: Fix NullPointerException in loadRelations()

### LINKED ISSUE #357: NullPointerException - Collections.binarySearch while querying for edges
`(new MultiVertexCentricQueryBuilder((StandardTitanTx) trans)).(vertices).labels(GraphConstants.M_PUBLISH).direction(Direction.IN).edges();
`

The above query fails with NullPointerException sometimes (it behaves correctly at times) in case if there are no incident edges for the input.

```
java.lang.NullPointerException
        at java.util.Collections.binarySearch(Collections.java:212)
        at com.thinkaurelius.titan.diskstorage.keycolumnvalue.SliceQuery.getSubset(SliceQuery.java:94)
        at com.thinkaurelius.titan.graphdb.vertices.CacheVertex.loadRelations(CacheVertex.java:55)
        at com.thinkaurelius.titan.graphdb.query.vertex.SimpleVertexQueryProcessor.getBasicIterator(SimpleVertexQueryProcessor.java:111)
        at com.thinkaurelius.titan.graphdb.query.vertex.SimpleVertexQueryProcessor.iterator(SimpleVertexQueryProcessor.java:68)
```

The exception mentioned above is for titan-cassandra-1.0.0, but is reproducible for janusgraph as well.

### PR DESCRIPTION
**Pull request by pankajydv**
Fixes #357 
Signed-off-by: Pankaj Yadav <pankaj.yadav@timesinternet.in>

### CODE REVIEW

**Comment by mbrukman** [comment]
@pankajydv — please follow the instructions in [`CONTRIBUTING.md`](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md) to sign the CLA. We cannot accept your PR until you've done so.

**Comment by pluradj** [comment]
@pankajydv will you be signing a CLA? If not we should probably close this PR because we can't accept it without a CLA.

**Comment by pankajydv** [comment]
@pluradj - I have sent the signed ICLA document to janusgraph-cla@googlegroups.com. Please review and let me know if anything else is required.

**Comment by mbrukman** [comment]
The CCLA for Times Internet folks was added in https://github.com/JanusGraph/legal/pull/93 and [this commit](https://github.com/JanusGraph/janusgraph/pull/362.patch) matches the email address in the CCLA, so we should be all set.

The very likely reason this PR has a `[cla: no]` label is probably because @pankajydv's email address used in the commit is not registered and confirmed in @pankajydv's GitHub account. Note that it doesn't have to be a _public_ email address, it just needs to be added as one of email addresses, and then verified (by clicking on a link sent by GitHub) to connect the email address and the GitHub account.

We've seen this happen in other cases as well, and adding email address to one's GitHub profile fixes it.

**Comment by pankajydv** [comment]
@pluradj This is an intermittent issue - I am not sure with a reproducible testcase. I have been somehow encountering this issue sometimes in my production setup. After I made this change in my local setup, I have never encountered this again.

**Comment by mglusiuk** [comment]
this happens if you use cassandra cluster as a backend
with single node all works without fix
if you can not setup test case with cluster you will be not able to reproduce

**Comment by mglusiuk** [comment]
it is developer job to create unittests

you should thank community for reporting bug with ready resolution ;)

if you are not happy about pull request please close it and start solving this bug yourself by reproducing it

**Comment by pankajydv** [comment]
As stated in my earlier [comment](https://github.com/JanusGraph/janusgraph/pull/362?_pjax=%23js-repo-pjax-container#issuecomment-379712465), this is an intermittent issue and I have not been able to find exact steps to reproduce this issue, hence I'll not be able to write unit test cases for this issue.

**Comment by sjudeng** [comment]
@pankajydv Thanks for your patience. Unit tests are something that's always requested for contributions (see [here](https://github.com/JanusGraph/janusgraph/blob/master/.github/PULL_REQUEST_TEMPLATE.md#for-code-changes)). As @amcp mentioned you can mock what's necessary. This might be close to what you want: https://github.com/sjudeng/janusgraph/commit/10b4067291fc22b340eca6badf3ce05785d01cb1.

**Comment by chupman** [comment]
@sjudeng is the [test](https://github.com/sjudeng/janusgraph/commit/10b4067291fc22b340eca6badf3ce05785d01cb1) you mentioned already working? Or does additional work need to be done?

If it's already completed I'm thinking it might be easier to just add it in a separate PR.

**Comment by chupman** [comment]
This commit was combined with the suggested test in #1581 which has now been merged. Closing as duplicate.

**Pull request closed without merging**
