### PR TITLE
Fixed @return comments to remove javadoc warnings

### PR DESCRIPTION
**Pull request by dbolcioni**
Signed-off-by: Davide Bolcioni <dbolcion@uber.com>

### CODE REVIEW

**Comment by mbrukman** [comment]
@dbolcioni -- the change looks good, but could you please change your commit description to be more meaningful? E.g., "fixed `@return` comments to remove warnings" -- exercising GitHub workflow is nice, but won't be meaningful in history when someone is reviewing past commits to JanusGraph.

**Comment by mbrukman** [comment]
You can do this easily via:

```bash
$ git commit --amend

  # change the description, save and exit your editor

$ git push -f
```

**Comment by sjudeng** [comment]
I would have thought for validation you need to have both the method description and the description of return argument. Doesn't this change cause a new warning about a missing method description?

**Comment by dbolcioni** [comment]
@sjudeng I tried building both with and without this diff, without the diff I get:
[WARNING] /home/uber/usecurity/janusgraph/janusgraph-core/src/main/java/org/janusgraph/diskstorage/MetaAnnotated.java:28: warning - @return tag has no arguments.
[WARNING] /home/uber/usecurity/janusgraph/janusgraph-core/src/main/java/org/janusgraph/diskstorage/MetaAnnotated.java:34: warning - @return tag has no arguments.

while with the diff I get no warning about MetaAnnotated.java.

**Comment by mbrukman** [comment]
@sjudeng – will wait for your review/approval before merging.

**Comment by sjudeng** [comment]
@dbolcioni, @mbrukman Thanks I'm good with this. I had to look it up: From http://docs.oracle.com/javase/8/docs/technotes/tools/unix/javadoc.html#JSSOR645, "comments can have a tag section and no main description".

**Comment by mbrukman** [comment]
@sjudeng – thanks for checking.

@dbolcioni – thanks again for the contribution!

**Pull request merged**
