### PR TITLE
Add Coverity config for static code analysis.

### PR DESCRIPTION
**Pull request by mbrukman**
Coverity includes Travis CI integration; this config is following the
instructions at the following page with minor modifications:
https://scan.coverity.com/projects/janusgraph-janusgraph/builds/new?tab=travis_ci

Signed-off-by: Misha Brukman <mbrukman@google.com>

### CODE REVIEW

**Comment by hsaputra** [comment]
When I try to login to see the page I got error:

`You are not authorized to access this page.`

**Comment by mbrukman** [comment]
@hsaputra — that's strange, it's currently configured as:

> Project access:  Project summary and defects are viewable in read-only mode by all users

Maybe it needs a successful run before it's visible? I invited you to the project to see it as well.

**Comment by hsaputra** [comment]
Restart CI

**Comment by mbrukman** [comment]
@hsaputra — turns out, Coverity only runs on branch pushes, not PRs (see references), so once the Travis build succeeds on the `master` branch with the fixed `if` / `then` / `else` clause (sorry!), we should merge this PR, and then I'll push to `coverity_scan` branch, which should trigger the Coverity scan.

References:

* http://vicrucann.github.io/tutorials/qtosg-coverity/
* https://github.com/travis-ci/travis-ci/issues/6142#issuecomment-259137469

**Pull request merged**
