### PR TITLE
Sync EvictionTrigger's openInstances on schedule

### PR DESCRIPTION
**Pull request by dpitera**
Without this change, any job to REGISTER an index requires
acknowledgement from every server on which the graph was open at the
time of index creation, however the index state change would never
fulfill should, for example, the DBA removed a JG node from the cluster.

Note that we do not make the EvictionTrigger take into account newly
added JG nodes because these nodes would never receive the message that
the index was is being registered and thus could never send an
acknowledgement message.

Issues: #716

Signed-off-by: David Pitera <dpitera@us.ibm.com>

Create ConfigOption REPLACE_INSTANCE_IF_EXISTS

If a user supplies their instance name (or suffix) at graph open time,
as well as use this new configuration option with a value of true, then
a graph trying to open with the same instance-id as one previously
opened will still open.

Issues: #716

Signed-off-by: David Pitera <dpitera@us.ibm.com>

ConfigOption to set graph-instance to hostname

This is useful if you want to track JG nodes by their hostnames, with
the option of appending suffix values to the end of the hostname,
whereas previously the suffix option is appended to a hex encoded local address.

Issues: #716
Signed-off-by: David Pitera <dpitera@us.ibm.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [x] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?
- [x] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by dpitera** [comment]
This is my branch to merge the changes from approved and merged into 0.2 #717 into master.

**Comment by dpitera** [comment]
> Can you do this as a merge of 0.2 into master? That will avoid a duplicate commit.

Quite the contrary, that will include the merge into 0.2 commit. I think rebasing where applicable is always preferable.

**Comment by sjudeng** [comment]
Just when merging features up from release branches into master we do want to preserve the merge commit to allow for consistent commit SHAs between branches. Where we've been sometimes rebasing is on the initial merge of a new feature (into release branch or master). See https://groups.google.com/forum/#!topic/janusgraph-dev/YZqk_wWfYBo.

**Comment by dpitera** [comment]
@sjudeng Done

**Comment by dpitera** [comment]
> Author of one or more commits is not listed as a CLA signer, either individual or as a member of an organization.

Can I sign the 2 merge commits?

**Comment by pluradj** [comment]
I think it's complaining about this commit https://github.com/dpitera/janusgraph/commit/894488c5c6896fd750147820a2046cf3fd3b6258 because the author name doesn't match the CLA exactly `Author: dpitera <dpitera@us.ibm.com>`

**Comment by dpitera** [comment]
@pluradj Thats a merge commit; what am I to do about that?

**Comment by sjudeng** [comment]
And it's already in 0.2: https://github.com/JanusGraph/janusgraph/commit/894488c5c6896fd750147820a2046cf3fd3b6258. Given this hopefully we can merge as is in this case.

@dpitera To avoid this in the future I think you just need to update your name in your GitHub profile (or add the alternate to the CLA if you prefer?). When you merged the PR into 0.2 through the GitHub UI it uses the name from your profile.

**Comment by sjudeng** [comment]
@mbrukman, @pluradj Can we merge this? Since the commit is already in 0.2 I don't think it should be modified in master. I think the only other option would be to add an additional entry to the CLA for the alias name.

**Comment by pluradj** [comment]
I've submitted a [CLA update](https://github.com/JanusGraph/legal/pull/90). I think that will clear it up.

**Comment by dpitera** [comment]
@pluradj Nice! Did you have to rebase the CLA update into this branch for it to take effect? (Might want to document)

**Pull request merged**
