### PR TITLE
Fix lucene docid tokenization

### PR DESCRIPTION
**Pull request by mad**
Fix for #1944

Signed-off-by: Pavel Ershov <owner.mad.epa@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by porunov** [comment]
@mad would you be able to add a test to cover the bugfix?

**Comment by mad** [comment]
@porunov done

**Comment by porunov** [comment]
@mad Which test should I check to get NPE?

All `InMemoryOLAPTest` are passing without:
```
if (LuceneIndex.DOCID.equals(fieldName)) {
    return analyzerFor(KEYWORD_ANALYZER);
}
```

**Comment by mad** [comment]
@porunov `LuceneIndexTest`

**Pull request merged**
