### PR TITLE
JanusGraph release v0.6.0 [cql-tests] [tp-tests]

### PR DESCRIPTION
**Pull request by porunov**
Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by farodin91** [comment]
Could you update the mkdocs.yml?

**Comment by li-boxuan** [comment]
I am curious why we don’t create RC releases before major releases. That would make it much easier to do user-acceptance testing especially when using janusgraph as a java library.

**Comment by porunov** [comment]
> Could you update the mkdocs.yml?

What exactly? It already lists 0.6.0 as the latest version.
0.6.1 is not yet started and will be updated after 0.6.0 is released

**Comment by porunov** [comment]
> I am curious why we don’t create RC releases before major releases. That would make it much easier to do user-acceptance testing especially when using janusgraph as a java library.

Totally makes sense but we didn't have such policies before. I think we should discuss our versioning in the dev channel.

**Comment by porunov** [comment]
@farodin91 Normally we return to next snapshot after we released current version. For example, like here: https://github.com/JanusGraph/janusgraph/commit/7ab8f607341eca121875643eb23359ed3b639591 (i.e. we updated `mkdocs.yml` with `0.5.4-SNAPSHOT` when we returned snapshot version in all `pom.xml` files).
I.e. I had plans to set snapshot version to `0.6.1-SNAPSHOT` after `0.6.0` is fully released because there could be some commits still which affect 0.6.0 release and not 0.6.1 release.

**Comment by mad** [comment]
3.5.0 TP has blocker issue https://issues.apache.org/jira/browse/TINKERPOP-2579

**Comment by porunov** [comment]
> 3.5.0 TP has blocker issue https://issues.apache.org/jira/browse/TINKERPOP-2579

Thanks for reporting @mad . Looks like the fix is on it's way here https://github.com/apache/tinkerpop/pull/1445

**Comment by tfcace** [comment]
Looks like the Tinkerpop issue was resolved

**Comment by porunov** [comment]
> Looks like the Tinkerpop issue was resolved

It is resolved in TinkerPop source code but there is no release which contains that fix yet. Probably we need to wait until TinkerPop 3.5.1 is released which will contain this fix.
https://github.com/apache/tinkerpop/blob/master/CHANGELOG.asciidoc#tinkerpop-351-release-date-not-officially-released-yet

**Comment by FlorianHockmann** [comment]
> It is resolved in TinkerPop source code but there is no release which contains that fix yet. Probably we need to wait until TinkerPop 3.5.1 is released which will contain this fix.

@porunov @mad Did you see the workaround @spmallette suggested in [TINKERPOP-2568](https://issues.apache.org/jira/browse/TINKERPOP-2568)? Can't we use that for 0.6.0 so we don't have to wait for TP 3.5.1?

**Comment by porunov** [comment]
> @porunov @mad Did you see the workaround @spmallette suggested in TINKERPOP-2568? Can't we use that for 0.6.0 so we don't have to wait for TP 3.5.1?

@FlorianHockmann as far as I know @li-boxuan already used that approach in JanusGraphTraversalUtil as discussed here: https://github.com/JanusGraph/janusgraph/pull/2619#discussion_r637935436

Personally I don't use `EventStrategy` currently but I don't know if it blocks those who are using it. Probably @mad could give more clear insights of this issue.

**Comment by mad** [comment]
@FlorianHockmann  @porunov Yes we are using event strategy and I don't know how to apply this workaround to this use case https://issues.apache.org/jira/browse/TINKERPOP-2579?focusedCommentId=17364795&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17364795

**Comment by porunov** [comment]
Started the discussion about TinkerPop 3.5.1 here: https://lists.apache.org/thread.html/r5c3e754750a2b20d4d06ba1cae1baaa3c6bd93fcd24f46ef20a5e55b%40%3Cdev.tinkerpop.apache.org%3E

**Comment by tfcace** [comment]
Seems like TinkerPop 3.5.1 was released about a week ago. Any ETA for JanusGraph 0.6.0?
Thanks!

**Comment by porunov** [comment]
@tfcace The PR to upgrade TinkerPop to 3.5.1 is here #2721

**Comment by porunov** [comment]
Proposing to start the release process on August 2 (Monday). If anyone has other thoughts and think that we should start release process earlier or later, I'm fine with that but would like to keep such discussion here: https://lists.lfaidata.foundation/g/janusgraph-dev/topic/81425771

I will rebase and make this PR ready for review on the agreed day (August 2 as for now).

**Comment by porunov** [comment]
The release PR is now ready for review

**Review by rngcntr — APPROVED** [review]

**Comment by porunov** [comment]
Currently I have troubles deploying JanusGraph because of `janusgraph-grpc` module. 
It's not yet clear to me how should I proceed as the proto classes are not generated, thus, deployment fails. If I generate classes deployment fails as well because of missing license.
I'm trying to figure our that but can't say estimated time. After I manage to solve those problems I will update the release day. If anyone has any thoughts or knows how to fix it, would be nice to have some help here.

Right now the next deployment command will throw an exception `mvn clean javadoc:jar deploy -Pjanusgraph-release -DskipTests=true`:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for JanusGraph: Distributed Graph Database 0.6.0:
[INFO] 
[INFO] JanusGraph: Distributed Graph Database ............. SUCCESS [  5.756 s]
[INFO] JanusGraph-gRPC: gRPC Components for JanusGraph .... FAILURE [  0.695 s]
[INFO] JanusGraph-Driver: Gremlin-Driver Library for JanusGraph SKIPPED
[INFO] JanusGraph-Core: Core Library for JanusGraph ....... SKIPPED
[INFO] JanusGraph-Backend-testutils: Collection of Backend tests SKIPPED
[INFO] JanusGraph-InMemory: InMemory Backend for JanusGraph SKIPPED
[INFO] JanusGraph-Server: Server Components for JanusGraph  SKIPPED
[INFO] JanusGraph-Test: Test Suite for JanusGraph ......... SKIPPED
[INFO] JanusGraph-BerkeleyJE: Distributed Graph Database .. SKIPPED
[INFO] JanusGraph-Hadoop: Module .......................... SKIPPED
[INFO] JanusGraph-CQL: Distributed Graph Database ......... SKIPPED
[INFO] JanusGraph-HBase: Distributed Graph Database ....... SKIPPED
[INFO] JanusGraph-Bigtable: Google Cloud Bigtable driver .. SKIPPED
[INFO] JanusGraph-ElasticSearch: Distributed Indexing Support SKIPPED
[INFO] JanusGraph-Lucene: Indexing Support ................ SKIPPED
[INFO] JanusGraph-Solr: Distributed Indexing Support ...... SKIPPED
[INFO] JanusGraph-All: Complete JanusGraph Distribution ... SKIPPED
[INFO] JanusGraph-Dist: Tar and Zip Archives .............. SKIPPED
[INFO] JanusGraph-Doc: Manual for JanusGraph .............. SKIPPED
[INFO] JanusGraph-Examples: Examples for JanusGraph ....... SKIPPED
[INFO] Example-Common: Common Graph Code for Examples ..... SKIPPED
[INFO] Example-BerkeleyJE: BerkeleyJE Storage, Lucene Index SKIPPED
[INFO] Example-Cql: Cassandra CQL Storage, Elasticsearch Index SKIPPED
[INFO] Example-HBase: HBase Storage, Solr Index ........... SKIPPED
[INFO] Example-RemoteGraph: Example with RemoteGraph ...... SKIPPED
[INFO] Example-TinkerGraph: Example with TinkerGraph ...... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.904 s
[INFO] Finished at: 2021-08-10T12:07:35+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (default-cli) on project janusgraph-grpc: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/JanusGraphManagerClient.java:20: error: package org.janusgraph.graphdb.grpc.types does not exist
[ERROR] import org.janusgraph.graphdb.grpc.types.JanusGraphContext;
[ERROR]                                         ^
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/JanusGraphManagerClient.java:26: error: package JanusGraphManagerServiceGrpc does not exist
[ERROR]     private final JanusGraphManagerServiceGrpc.JanusGraphManagerServiceBlockingStub blockingStub;
[ERROR]                                               ^
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/JanusGraphManagerClient.java:39: error: cannot find symbol
[ERROR]     public JanusGraphContext getContextByGraphName(String name) {
[ERROR]            ^
[ERROR]   symbol:   class JanusGraphContext
[ERROR]   location: class JanusGraphManagerClient
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/JanusGraphManagerClient.java:45: error: cannot find symbol
[ERROR]     public List<JanusGraphContext> getContexts() {
[ERROR]                 ^
[ERROR]   symbol:   class JanusGraphContext
[ERROR]   location: class JanusGraphManagerClient
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:20: error: package org.janusgraph.graphdb.grpc.types does not exist
[ERROR] import org.janusgraph.graphdb.grpc.types.EdgeLabel;
[ERROR]                                         ^
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:21: error: package org.janusgraph.graphdb.grpc.types does not exist
[ERROR] import org.janusgraph.graphdb.grpc.types.JanusGraphContext;
[ERROR]                                         ^
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:22: error: package org.janusgraph.graphdb.grpc.types does not exist
[ERROR] import org.janusgraph.graphdb.grpc.types.VertexLabel;
[ERROR]                                         ^
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:28: error: package SchemaManagerServiceGrpc does not exist
[ERROR]     private final SchemaManagerServiceGrpc.SchemaManagerServiceBlockingStub blockingStub;
[ERROR]                                           ^
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:29: error: cannot find symbol
[ERROR]     private final JanusGraphContext context;
[ERROR]                   ^
[ERROR]   symbol:   class JanusGraphContext
[ERROR]   location: class SchemaManagerClient
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:31: error: cannot find symbol
[ERROR]     public SchemaManagerClient(JanusGraphContext context, Channel channel) {
[ERROR]                                ^
[ERROR]   symbol:   class JanusGraphContext
[ERROR]   location: class SchemaManagerClient
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:36: error: cannot find symbol
[ERROR]     public SchemaManagerClient(JanusGraphContext context, String target) {
[ERROR]                                ^
[ERROR]   symbol:   class JanusGraphContext
[ERROR]   location: class SchemaManagerClient
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:48: error: cannot find symbol
[ERROR]     public VertexLabel getVertexLabelByName(String name) {
[ERROR]            ^
[ERROR]   symbol:   class VertexLabel
[ERROR]   location: class SchemaManagerClient
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:57: error: cannot find symbol
[ERROR]     public List<VertexLabel> getVertexLabels() {
[ERROR]                 ^
[ERROR]   symbol:   class VertexLabel
[ERROR]   location: class SchemaManagerClient
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:67: error: cannot find symbol
[ERROR]     public EdgeLabel getEdgeLabelByName(String name) {
[ERROR]            ^
[ERROR]   symbol:   class EdgeLabel
[ERROR]   location: class SchemaManagerClient
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:76: error: cannot find symbol
[ERROR]     public List<EdgeLabel> getEdgeLabels() {
[ERROR]                 ^
[ERROR]   symbol:   class EdgeLabel
[ERROR]   location: class SchemaManagerClient
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:46: error: reference not found
[ERROR]      * @return {@link VertexLabel}
[ERROR]                       ^
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:55: error: reference not found
[ERROR]      * @return Returns a list of {@link VertexLabel}
[ERROR]                                         ^
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:65: error: reference not found
[ERROR]      * @return {@link EdgeLabel}
[ERROR]                       ^
[ERROR] /home/alex/Documents/Apps/janusgraph/janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java:74: error: reference not found
[ERROR]      * @return Returns a list of {@link EdgeLabel}
[ERROR]                                         ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/jdk-oracle-8-281/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/alex/Documents/Apps/janusgraph/janusgraph-grpc/target/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :janusgraph-grpc
```

To compare, here is the branch where I generated proto classes: https://github.com/porunov/janusgraph/commit/591f2e978d482da4873f4f605fa5208aca43563f

cc @farodin91 , @JanusGraph/committers

**Comment by farodin91** [comment]
Could it be that Java doc is ignoring the generated code?

I will search for more information.

**Comment by porunov** [comment]
I opened the issue here: https://github.com/JanusGraph/janusgraph/issues/2750 regarding this problem. Current it's a blocker for 0.6.0 release.

**Comment by porunov** [comment]
Fixed the above problem.
The voting is now opened for 0.6.0 release at this location: https://lists.lfaidata.foundation/g/janusgraph-dev/topic/vote_janusgraph_0_6_0/84815207

**Pull request merged**
