### PR TITLE
Merge 0.1 into master

### PR DESCRIPTION
**Pull request by sjudeng**
Merge recent commits from 0.1 into master.

### CODE REVIEW

**Comment by mbrukman** [comment]
Please don't merge this PR just yet, let me figure out the issue with the CLA first.

**Comment by sjudeng** [comment]
@mbrukman If it's easier and you're amenable I think you can just merge and push to master directly yourself (as a repo admin) without going through the PR/review process.

**Comment by mbrukman** [comment]
Looks like this is marked as `[cla: no]` because @twilmes merged PR #179 (via web UI?), thus creating a commit using his default email address on GitHub, which is not the email address listed on the CLA.

I'll fix it by adding his other email address to the CLA signers group and we should be good to go here.

**Comment by mbrukman** [comment]
@sjudeng, @twilmes -- CLA issues resolved, so this PR is good to go.

Should we wait for Travis to turn green, or assume it's fine since it's just a merge from one branch to another?

**Comment by amcp** [comment]
Travis is OK now so merging

**Comment by twilmes** [comment]
Good catch @mbrukman.  It was the web UI, didn't think about the fact it was associated with the other email.  Thanks for adding that email to CLA group.

**Pull request merged**
