### PR TITLE
Exclude metrics-core 3.x from gremlin-server

### PR DESCRIPTION
**Pull request by cdegroc**
- Exclude `metrics-core` 3.x from gremlin-server.
- Import JmxReporter from `metrics-jmx` as it moved there in 4.x.

Fixes issue #2722

Signed-off-by: Clement de Groc <clement.degroc@datadoghq.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there an issue associated with this PR? Is it referenced in the commit message?
- [X] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by li-boxuan** [comment]
@cdegroc Thank you for finding and fixing the problem! Is it possible to include a test that reproduces what you said in #2722?

**Comment by cdegroc** [comment]
> @cdegroc Thank you for finding and fixing the problem! Is it possible to include a test that reproduces what you said in #2722?

Hey @li-boxuan 👋  I completely understand your point and having a single test we could keep would be great.

It's a bit harder here, because the issue only appears when JanusGraph's classpath has jars in a specific order.
The order can be different when JanusGraph is started with `janusgraph-server.sh` and in unit tests (and even there, it can depend on the content of Maven's pom files).

I've tried my best nonetheless, and I've added a test demonstrating the issue here: https://github.com/cdegroc/janusgraph/commit/fbeba221e46aa44b19115eac78b9dce6a7027479
You can see the test [failing in the CI](https://github.com/cdegroc/janusgraph/runs/3182468766) and should be able to reproduce the issue locally.

Of course, for such a change, we could also just wait for more users to test 0.6/master to see if they hit this issue.

**Review by porunov — APPROVED** [review]
LGTM. Thank you @cdegroc !

**Comment by li-boxuan** [comment]
@cdegroc Thanks for the explanation! I think the `testCqlMetricsInitialization` test in your commit fbeba221e46aa44b19115eac78b9dce6a7027479 is worth including in this PR. What do you think?

**Comment by cdegroc** [comment]
> @cdegroc Thanks for the explanation! I think the `testCqlMetricsInitialization` test in your commit [fbeba22](https://github.com/JanusGraph/janusgraph/commit/fbeba221e46aa44b19115eac78b9dce6a7027479) is worth including in this PR. What do you think? This is just to ensure (to some extent) the same problem does not occur again.

@li-boxuan I've added the test to the PR.

**Comment by porunov** [comment]
@cdegroc could you please rebase you PR against the latest commit in `master`? It has a fix for `dist-tests`.

**Review by li-boxuan — APPROVED** [review]
LGTM 👍

**Pull request merged**
