### PR TITLE
Fix issues with release build tests

### LINKED ISSUE #2024: AbstractJanusGraphAssemblyIT.command
## Flaky Test

* **Test Name:** `JanusGraphScriptIT.testGraphOfTheGodsGraphSON:26->AbstractJanusGraphAssemblyIT.unzipAndRunExpect:106->AbstractJanusGraphAssemblyIT.unzipAndRunExpect:81->AbstractJanusGraphAssemblyIT.parseTemplateAndRunExpect:102->AbstractJanusGraphAssemblyIT.expect:121->AbstractJanusGraphAssemblyIT.command:160 expected: <0> but was: <1>`
* **Branch:** `master`

### Stack Trace

```[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 69.586 s <<< FAILURE! - in org.janusgraph.pkgtest.JanusGraphScriptIT

[ERROR] testGraphOfTheGodsGraphSON  Time elapsed: 69.393 s  <<< FAILURE!

org.opentest4j.AssertionFailedError: expected: <0> but was: <1>

	at org.janusgraph.pkgtest.JanusGraphScriptIT.testGraphOfTheGodsGraphSON(JanusGraphScriptIT.java:26)

[INFO] 

[INFO] Results:

[INFO] 

[ERROR] Failures: 

[ERROR]   JanusGraphScriptIT.testGraphOfTheGodsGraphSON:26->AbstractJanusGraphAssemblyIT.unzipAndRunExpect:106->AbstractJanusGraphAssemblyIT.unzipAndRunExpect:81->AbstractJanusGraphAssemblyIT.parseTemplateAndRunExpect:102->AbstractJanusGraphAssemblyIT.expect:121->AbstractJanusGraphAssemblyIT.command:160 expected: <0> but was: <1>

[INFO] 

[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0
```

### PR DESCRIPTION
**Pull request by farodin91**
Fixes #2024

Signed-off-by: Jan Jansen <jan.jansen@gdata.de>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by farodin91** [comment]
I have no idea why no all env variables are inserted into the header line. Could be a bug in travis-ci

**Comment by farodin91** [comment]
> I thought that we decided to remove coverity.

I already opened a pr for it.

**Comment by porunov** [comment]
It is strange that this PR is also adds some parameters. I don't understand them. `COVERITY_SCAN_TOKEN=[secure]`, `COVERITY_EMAIL="sjudeng@gmail.com"`, `export= STRUCTOR_VERSION=v1.7.1`. Do we really need them? Currently our TravisCI parameters don't include them and they work normally. This PR adds those parameters but I don't understand why it adds those parameters and where they are added

**Comment by farodin91** [comment]
> It is strange that this PR is also adds some parameters. I don't understand them. `COVERITY_SCAN_TOKEN=[secure]`, `COVERITY_EMAIL="sjudeng@gmail.com"`, `export= STRUCTOR_VERSION=v1.7.1`. Do we really need them? Currently our TravisCI parameters don't include them and they work normally. This PR adds those parameters but I don't understand why it adds those parameters and where they are added

I think it is a bug in travis ci.

**Comment by farodin91** [comment]
@porunov release build tests are green again.

**Comment by porunov** [comment]
@farodin91 Indeed. That looks like TravisCI bug because I am getting the same strange parameters in my local TravisCI builds with no such changes.

**Pull request merged**
