### PR TITLE
Use fixed Java versions for releases

### PR DESCRIPTION
**Pull request by porunov**
Ensures deterministic releases from running the same CI (same Java version will be used).

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by farodin91** [comment]
@porunov Do we want to pin the java version of the docker image? If yes we should ensure dependabot should be able to update it. Same for github actions.

**Comment by porunov** [comment]
> @porunov Do we want to pin the java version of the docker image? If yes we should ensure dependabot should be able to update it. Same for github actions.

Yes, it would be great to pin Java version for Docker image as well. However, I'm not yet sure how to configure Dependabot to update Java version in GitHub workflow files. I will try to check it tomorrow, but if you know how, please, feel free to add commits into this PR because I allowed edits into this PR's branch for JanusGraph maintainers.

**Comment by porunov** [comment]
@farodin91 Docker uses eclipse temurin but we use azul zulu JDK builds in GitHub Actions. 
I also don't know how to configure dependabot to automate Java updates in either Docker or GitHub Actions.
I'm thinking of merging this PR as is for now. Please, let me know if you have any objections.

**Comment by farodin91** [comment]
> @farodin91 Docker uses eclipse temurin but we use azul zulu JDK builds in GitHub Actions. I also don't know how to configure dependabot to automate Java updates in either Docker or GitHub Actions. I'm thinking of merging this PR as is for now. Please, let me know if you have any objections.

I will check both later.

**Review by farodin91 — APPROVED** [review]

**Comment by farodin91** [comment]
@porunov Did want to backport it?

**Comment by porunov** [comment]
> @porunov Did want to backport it?

I’m not sure if there will be any release in 0.6 branch anymore, but I’m OK to backporting it

**Pull request merged**
