### PR TITLE
JanusGraph release 1.0.0 [cql-tests][tp-tests]

### PR DESCRIPTION
**Pull request by li-boxuan**
Tentative release date: October 21, 2023

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by porunov** [comment]
> https://github.com/JanusGraph/janusgraph/blob/master/.github/workflows/docker-release-tags.yml#L22 please update this.

I will update it during the release and create the new branch

**Comment by FlorianHockmann** [comment]
I think we should reorder the changelog a bit so that the most important changes are more prominent and the breaking changes are together.

**Comment by li-boxuan** [comment]
rebased on top of latest master

**Comment by porunov** [comment]
@FlorianHockmann the changelog was reordered by @li-boxuan . I would like to start the release process either on weekends or on Monday. If you have time to double check the changelog, it would be great.

@li-boxuan I'm closing this PR because I will need to trigger full tests before the release anyways and the release date might potentially be updated as well.

**Comment by FlorianHockmann** [comment]
I've just reviewed the current changelog and I like its current structure :)

**Pull request closed without merging**
