### PR TITLE
Make mapping support configurable for ES7 and drop it for future ES v…

### LINKED ISSUE #1659: Do not use mapping types for future ElasticSearch versions
Mapping is deprecated and disabled by default in ElasticSearch 7. Mapping support will be completely removed in ES 8. We need to prepare possibility to work without mappings for ES 8.

If we drop mapping types for ES 7 then it will be easier for users to upgrade their JanusGraph indexes from ES 7 to ES 8 but will require reindexing from ES 6 to ES 7. If we drop support for mapping types in ES 8 but save them in ES 7 then it will be easier for users to upgrade their JanusGraph indexes from ES 6 to ES 7 but will require reindexing from ES 7 to ES 8.

Maybe it is better to add an optional parameter to enable / disable mappings for ES 7 in JanusGraph.

### PR DESCRIPTION
**Pull request by porunov**
…ersions

- Added possibility to configure mapping types usage on ElasticSearch 7
- Dropped mapping types usage for ElasticSearch > 7
- Small performance improvement in bulk api

Fixes #1659

Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by porunov** [comment]
@FlorianHockmann could you please disable Codacy `Use explicit scoping instead of the default package private level` check? It isn't right. Package private level is stickier than `protected`.

**Comment by porunov** [comment]
@FlorianHockmann I have disabled `Use explicit scoping instead of the default package private level` check in Codacy. Also, I don't know why, but we are using `PMD (Legacy) 5.8.1` instead of `PMD 6.14.0` in Codacy patterns. Is there any reason why we use the older version?

**Comment by FlorianHockmann** [comment]
> Also, I don't know why, but we are using PMD (Legacy) 5.8.1 instead of PMD 6.14.0 in Codacy patterns. Is there any reason why we use the older version?

I haven't configured anything about that so it must be the default setting in Codacy. If you think that the newer version makes more sense, just go ahead and change that.

**Comment by porunov** [comment]
Merging by following lazy consensus

**Pull request merged**
