### PR TITLE
Convert HBase ttl param from Integer to long#1454

### LINKED ISSUE #1454: JanusGraph HBase TTL Limit
I have created a graph with hbase backend and set one edgelabel's ttl to 2160 hours(90 days). But when I do bulkload data to this graph, I found that BulkLoadVertexProgram can successfully work but all the edges cannot be loaded to hbase & all the vertices are loaded. 
When I check the source code of janusgraph and found a bug about this issue.
This issue is caused by format conversion from Interger to long. HBase Cell level TTL uses millisec but JanusGraph TTL use second. So in the HBaseStoreManager.java file (line 937 to 946), the code convert a Integer ttl to a long ttl with multiply by 1000 which would exceed the limit of int and will convert ttl to a negative number.
Thanks!

### PR DESCRIPTION
**Pull request by wangzheng90**
Fixes #1454

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by porunov** [comment]
@wangzheng90 Thanks for contribution!

If you would like this PR to be merged you should follow the contribution guideline [here](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md).
Right now you need sign ICLA or CCLA (the process isn't automated but JanusGraph members are working in this direction). Instruction for signing is [here](https://github.com/JanusGraph/legal).

**Comment by FlorianHockmann** [comment]
@wangzheng90 Thanks for your first contribution!

I just edited your pull request body to include the issue number. This allows GitHub to link your pull request to the issue.

Apart from the issues @porunov already mentioned: It would be good if you could also add a test that shows the problem you described in #1454. It should fail without your fix and pass with your change included.

**Comment by wangzheng90** [comment]
@porunov Thanks for reply! I've sign the CLA and send an email. Sorry for merge this commit to master branch. I'll retarget the PR to 0.2 branch.

**Comment by wangzheng90** [comment]
@FlorianHockmann Thanks for helping me edit the pull request body. I'll add a test for this issue.

**Comment by wangzheng90** [comment]
Hi @porunov @FlorianHockmann , I've added a test and retarget this pr to 0.2 branch in another PR https://github.com/JanusGraph/janusgraph/pull/1456. But the CLA label seems like still cla:no.

**Comment by FlorianHockmann** [comment]
Thanks for retargeting, although you could also have done that in this PR, but that's not that important.
CLA will take some time as it has to be processed manually.

I'm closing this now as it now obsolete because of your other PR which will be merged through all release branches and therefore also master.

**Comment by pluradj** [comment]
> @porunov Thanks for reply! I've sign the CLA and send an email. Sorry for merge this commit to master branch. I'll retarget the PR to 0.2 branch.

@wangzheng90 we have not received your CLA at the `janusgraph-cla (at) googlegroups.com` email address. Please send it along when you have a chance. Thanks.

**Comment by wangzheng90** [comment]
> > @porunov Thanks for reply! I've sign the CLA and send an email. Sorry for merge this commit to master branch. I'll retarget the PR to 0.2 branch.
> 
> @wangzheng90 we have not received your CLA at the `janusgraph-cla (at) googlegroups.com` email address. Please send it along when you have a chance. Thanks.

Re-send an email with CLA. Thanks!

**Comment by porunov** [comment]
@wangzheng90 You should change `(at)` to `@` symbol. The correct email address is:  
<janusgraph-cla@googlegroups.com>

**Comment by wangzheng90** [comment]
@porunov I've changed the symbol in my first email. It may spend some time because of unknown causes. But thank you all the same.  :)

**Pull request closed without merging**
