### PR TITLE
Update TinkerPop to 3.4.9 [tp-tests]

### PR DESCRIPTION
**Pull request by porunov**
All TP tests passed with `mvn clean install -Dtest.skip.tp=false -DskipTests=true`

Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by porunov** [comment]
The failed test is because of the bug #2205 which blocks TinkerPop upgrading in JanusGraph

**Comment by farodin91** [comment]
You could add [tp-tests] to your commit which will run all tp-tests on github actions.

**Comment by porunov** [comment]
@farodin91 I want to wait till TinkerPop 3.4.9 is released (if the release is approved) and then I will rebase this PR and change TinkerPop to 3.4.9

**Comment by porunov** [comment]
@farodin91 I added `[tp-tests]` to the commit message but they are not triggered. For some reason GitHub Actions skip `[tp-tests]` right now

**Comment by farodin91** [comment]
I have pretty good idea what's happened. Event doesn't contain correct infos under a pr, see your locale builds: https://github.com/porunov/janusgraph/runs/1584888202?check_suite_focus=true

To fix your local issue issues just remove -Pcoverage. I'm on it.

**Comment by porunov** [comment]
@farodin91 right now I just tested TP tests with `mvn clean install -Dtest.skip.tp=false -DskipTests=true` locally and all TP tests passed.

**Comment by farodin91** [comment]
I will provide a patch file to get the tp test running.

**Comment by farodin91** [comment]
This fix the build in your repo. For the pr need some time to investigate.

```patch
diff --git a/.github/workflows/ci-release.yml b/.github/workflows/ci-release.yml
index d5fb81200..3f53c54d0 100644
--- a/.github/workflows/ci-release.yml
+++ b/.github/workflows/ci-release.yml
@@ -33,7 +33,6 @@ on:
 env:
   ES_JAVA_OPTS: "-Xms256m -Xmx512m"
   BUILD_MAVEN_OPTS: "-DskipTests=true --batch-mode --also-make"
-  VERIFY_MAVEN_OPTS: "-Pcoverage"
 
 jobs:
   build-all:
@@ -106,4 +105,4 @@ jobs:
         with:
           java-version: 1.8
       - run: mvn clean install --projects janusgraph-${{ matrix.module }} ${{ env.BUILD_MAVEN_OPTS }} ${{ matrix.install-args }}
-      - run: mvn verify --projects janusgraph-${{ matrix.module }} ${{ env.VERIFY_MAVEN_OPTS }} ${{ matrix.args }}
+      - run: mvn verify --projects janusgraph-${{ matrix.module }} ${{ matrix.args }}
```

**Comment by porunov** [comment]
@farodin91 do you want to merge that patch into `master` branch? I'm not sure if that really related to this PR

**Comment by farodin91** [comment]
I merged the changes into master

**Comment by porunov** [comment]
@farodin91 All TP tests passed

**Review by farodin91 — APPROVED** [review]
LGTM

**Pull request merged**
