### PR TITLE
Merge javadoc fixes

### LINKED ISSUE #975: Clean up javadoc errors
When building the docs I'm currently seeing 308 errors. These should be cleaned up or set as exceptions in the maven job. Once all the errors are cleaned up I propose replacing the [skip ci] tag with a [docs] tag that does a doc build and sets up a gh-page for visual confirmation. On merge it should also update the docs so they get patched between major releases.

### PR DESCRIPTION
**Pull request by chupman**
Merge of the javadoc fixes in 0.2.0 and an additional commit that fixes some additional javadoc errors in 0.3.0 so that enabling linting would blow up builds. 

I built a local dist to test that everything was passing for me.
```
mvn clean install -Pjanusgraph-release -Dgpg.skip=true -DskipTests=true
```

fixes #975 
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pluradj** [comment]
This is fix for #975 merge to master

**Comment by amcp** [comment]
@chupman please rebase then i will merge

**Comment by sjudeng** [comment]
@amcp The commits that are already in 0.2 shouldn't be rebased though to avoid duplicate commits.

**Comment by sjudeng** [comment]
@amcp It can just be merged with a merge commit ("Create a merge commit" in the merge drop-down below). This is just so we don't end up with the same commit but with different commit SHA in 0.2 and master.

**Comment by chupman** [comment]
Hi @amcp p I can see the conflicts if I do a rebase, but from my github view I'm seeing ```This pull request can be automatically merged by project collaborators```

Based off the last comment from @sjudeng I'm going to leave this alone for unless I hear something new.

**Comment by pluradj** [comment]
@amcp @sjudeng We still need another approval on this PR (and others). Our policy has been to have 2 committers approving before merging, unless the PR author is a also committer (counting for 1 implicit approval).

**Pull request merged**
