### PR TITLE
Add warning against using older versions of dependencies [skip ci]

### LINKED ISSUE #424: Security Vulnerabilities with some of the components
Recently we scanned JanusGraph v.0.1.1 using Blackduck. The scan identified many open CVEs with some of the associated components included in the JanusGraph v.0.1.1 distribution:

Apache HttpComponents Client - 3.1
Apache Thrift 0.9.0 
Cassendar 2.1.9
Apache Tomcat 5.5.23

Any work going on to upgrade these? 

Is JanusGraph 0.1.1 production ready?

### PR DESCRIPTION
**Pull request by pluradj**
Fixes #424

Signed-off-by: Jason Plurad <pluradj@us.ibm.com>

Thank you for contributing to JanusGraph.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there an issue associated with this PR? Is it referenced in the commit message?
- [X] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by pluradj** [comment]
@sjudeng is it possible to run Travis CI against Cassandra 2.2.x, 3.0.x, and 3.11.x? Would be great to add those officially to the matrix.

**Comment by sjudeng** [comment]
@pluradj See https://travis-ci.org/sjudeng/janusgraph/builds/282055255. There are groups in there for 3.11.0, 3.0.14 and 2.2.10. These exclude SSL tests, which will take more work to setup. Same for janusgraph-hadoop tests (also note #562).

This is a manual Travis build for now. I created #584 to track updates to make this more automated.

**Comment by sjudeng** [comment]
I updated the above link. The first build had failures due to connection issues that were resolved. Also excluded embedded tests, which again would take more work to setup.

The current build does still show a small number of CQL test failures. In 3.11.0 and 3.0.14 there are three failures in CQLStoreTest (testDefaultCFCompressor, testCustomCFCompressor and testDisableCFCompressor). In 2.2.10 there is one failure in CQLLogTest (testFuzzMessagesSerial). @pkendall64, @samant-orionhealth Have you observed these issues/failures before with newer C*, or any ideas how they might be resolved?

**Comment by pluradj** [comment]
so close... these all look the same and seem like they'd be resolvable (389.11, 12, 25, 26): `sstable_compression` vs `class` as the key name in the map.

389.39 looks like a timeout.

**Comment by pluradj** [comment]
We should move C* support to a separate issue at this point since it looks like it will need a code update.

**Pull request merged**
