### PR TITLE
Fixed typo in sample configs

### PR DESCRIPTION
**Pull request by simonellistonball**

### CODE REVIEW

**Comment by mbrukman** [comment]
@simonellistonball — thanks for your contribution! Sorry for the inconvenience, but lawyers require us to have a CLA signed by every contributor (or their company) before accepting any contributions. For details, please see [`CONTRIBUTING.md`](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md) for details.

If you plan to contribute to JanusGraph in the future (which we certainly hope you will), you'll have to sign a CLA regardless to cover all changes. If not, please feel free to close this PR, and we'll have to recreate this change ourselves.

If you or your legal counsel have any questions about the CLA, please send email to the email address in [`JanusGraph/legal/README.md`](https://github.com/JanusGraph/legal/blob/master/README.md).

**Comment by simonellistonball** [comment]
@mbrukman would I not be covered under the Hortonworks corporate CLA?

**Comment by mbrukman** [comment]
@simonellistonball – the JanusGraph CLA verification process is specific to individuals (even in the presence of CCLAs) and precise in that it matches (name, GitHub username, email) for every commit.

If you're a Hortonworks employee (sorry, this is not at all obvious from either your GitHub profile or the email address used in your commits), please reach out to the existing Hortonworks employees listed in [`CLA_SIGNERS.yaml`](https://github.com/JanusGraph/legal/blob/master/CLA_SIGNERS.yaml) and have them update the Hortonworks section to include the required information for your account, at which point you'll be a recognized contributor. That file explicitly lists all users who are eligible to contribute to the JanusGraph repos — it covers all repos in the [JanusGraph org](https://github.com/JanusGraph).

The automated tool has no way of knowing that a contributor is employed by an organization which has already signed the CCLA unless the list of individuals on the CCLA is expanded to include more folks explicitly.

I'll start an email thread to discuss this.

**Comment by ptgoetz** [comment]
@simonellistonball has been added to the Hortonworks CCLA list.

**Comment by mbrukman** [comment]
Thanks for the fix, @simonellistonball!

**Pull request merged**
