### PR TITLE
Fix changes on master branch [doc only]

### PR DESCRIPTION
**Pull request by farodin91**
Signed-off-by: Jan Jansen <jan.jansen@gdata.de>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [x] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by porunov — APPROVED** [review]
LGTM

**Comment by farodin91** [comment]
@porunov https://github.com/JanusGraph/janusgraph/commit/1c7fc66cc5c8471ea6e340bdcd81c53e850bd6ca

**Comment by farodin91** [comment]
@porunov i will push a test branch and the changes on the test branch.

**Comment by farodin91** [comment]
branch called github-actions-docs

**Pull request merged**
