### PR TITLE
Upgrade TinkerPop to 3.5.4 and bump security related dependencies

### PR DESCRIPTION
**Pull request by li-boxuan**
Backport #3122, #3130, #3093, #3121, #3089, #2874, #2881

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Comment by li-boxuan** [comment]
I just signed CLA but still, the EasyCLA check is failing.

**Review by FlorianHockmann — APPROVED** [review]
The changes look good to me. It definitely makes sense in my opinion to also get these updates released in a 0.6 release soon.

I'm wondering in general whether we might want to discuss again about our branch strategy as we currently basically merge all PRs only into `master` which we'll only release as version 1.0.0 right now and that should include a lot of big breaking changes. So, all small updates like these patch version updates that are relevant for security basically have to wait for the 1.0.0 release or we need to manually backport them.
Any way, this PR is not the place to discuss this. I just wanted to write out my thoughts and maybe hear what you think about it as you just spent time to manually backport these changes. Then we can maybe start a discussion thread on the dev list about it.

**Comment by li-boxuan** [comment]
> I'm wondering in general whether we might want to discuss again about our branch strategy as we currently basically merge all PRs only into master which we'll only release as version 1.0.0 right now and that should include a lot of big breaking changes. So, all small updates like these patch version updates that are relevant for security basically have to wait for the 1.0.0 release or we need to manually backport them.

I feel like we should let those dependency-related PRs target the last stable version (0.6 at the moment), coz a major release usually takes a year or so.

**Review by farodin91 — APPROVED** [review]
LGTM! Thank you.

**Comment by FlorianHockmann** [comment]
> I feel like we should let those dependency-related PRs target the last stable version (0.6 at the moment), coz a major release usually takes a year or so. Not sure if this is configurable in dependabot.

Sounds like a good idea. I created a PR to configure Dependabot like that: #3169.

**Pull request merged**
