### PR TITLE
Index repair improvements

### PR DESCRIPTION
**Pull request by gguttikonda**
* Changed the work block size to be storage.page-size ( this makes the
pagination code cleaner ) and also make work block configurable.
* Removed QUEUE_SIZE from Scanner, it now follows storage.page-size
* ProcessQueue size would be numWorkers * workBlockSize * numDataPullers
* Add info logs for every job iteration to see the index update metrics.
* Handle the `doc-updates` count accurately matching with actual
updates.
* Fix for https://github.com/JanusGraph/janusgraph/issues/1895
* Same changes as PR ( https://github.com/JanusGraph/janusgraph/pull/1898 )
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by FlorianHockmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- janusgraph-test/src/test/java/org/janusgraph/graphdb/database/IndexSerializerTest.java  2
- janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java  1
         

Complexity decreasing per file
==============================
+ janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScannerExecutor.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/JanusGraph/janusgraph/pullRequest?prid=5275423&bid=17276551)

**Comment by farodin91** [comment]
@FlorianHockmann Do you want to review this PR again?

**Comment by FlorianHockmann** [comment]
@farodin91 again? I haven't reviewed this one yet. I'm only listed as a participant here because Codacy comments in my name as I activated that plugin.
I'm not sure whether I'll get to review this as I have some other PRs that I want to review already for quite some time first. You can also merge this after the 7 day cool down period from my side.

**Comment by farodin91** [comment]
@FlorianHockmann you reviewed the original pr.

**Comment by FlorianHockmann** [comment]
Ah, I didn't realize at first that this is only a squashed version of #1898. The contribution still looks good to me, but I'd prefer if @porunov could take a look at [this discussion](https://github.com/JanusGraph/janusgraph/pull/1898#discussion_r364239247).

**Pull request merged**
