### PR TITLE
Fix ordered iterator

### PR DESCRIPTION
**Pull request by mad**
Sample of code to reproduce issue

```
gremlin> graph=JanusGraphFactory.open("inmemory")
gremlin> graph.traversal()\
     .addV().property("a", "1").property("t", "1")\
     .addV().property("a", "1").property("t", "1")\
     .addV().property("b", "1").property("t", "1")\
     .addV().property("b", "1").property("t", "1")\
     .iterate()
gremlin> graph.tx().commit();
gremlin> graph.traversal().V().or(has("a", "1"), has("b", "1")).valueMap()
==>[a:[1],t:[1]]
==>[a:[1],t:[1]]
==>[t:[1],b:[1]]
==>[t:[1],b:[1]]
gremlin> graph.traversal().V().or(has("a", "1"), has("b", "1")).order().by("t").valueMap() <--- Issue here
==>[t:[1],b:[1]]
==>[t:[1],b:[1]]
graph.close()
```
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Review by porunov — APPROVED** [review]
Thank you @mad !
I haven't investigated `MultiDistinctOrderedIterator` too much, but as you were already contributing here multiple times you probably know better how to implement the fix.
I did check that the added test in `JanusGraphIndexTest` fails without your fix and passes with it. LGTM.

**Comment by FlorianHockmann** [comment]
I guess this should be backported to `v0.6`, right? I added the label for that to let the automation create a PR after this has been merged. If you disagree about backporting this, then just remove the label again and add `backport/skip` instead.

**Comment by janusgraph-automations** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|v0.6|Backport failed because of merge conflicts|

### Manual backport
To create the backport manually run:
```
backport --pr 3972
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/JanusGraph/janusgraph/actions/runs/6220154034) for details

**Comment by FlorianHockmann** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v0.6|[](https://github.com/JanusGraph/janusgraph/pull/3992)|

Note: Successful backport PRs will be merged automatically after passing CI.

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by FlorianHockmann** [comment]
Had to manually run the backport tool as there were merge conflicts since the last PR for this iterator wasn't backported to `v0.6`: #3342.

**Pull request merged**
