### PR TITLE
[skip ci] JanusGraphVertexProperty interface comments

### PR DESCRIPTION
**Pull request by alexBaiJW**
The JanusGraphVertexProperty comments says JanusGraphProperty which should be JanusGraphVertexProperty.

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by porunov** [comment]
@alexBaiJW Thanks for finding this misspell. I am not sure if you signed CLA or not so I will leave this comment here. 

There is a requirement that each contributor must sign a CLA. It isn't automate right now but JanusGraph members are working on it.

To contribute you should:
1. Sign a CLA. Instructions are here: https://github.com/JanusGraph/legal/blob/master/README.md
2. Follow this instructions to provide a correct PR: https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md

Please feel free to ask any questions if you have some.

**Comment by chupman** [comment]
I'm not sure if you're already in progress so I just wanted to check in, @alexBaiJW Do you have any intention of signing a CLA and amending this commit with a signoff for the DCO check?

If not please just let us know so I can open an issue with the documentation error and close this out.

**Comment by farodin91** [comment]
@alexBaiJW Do you want to sign our CLA and update the commit using `git commit --amend -s`?

**Comment by farodin91** [comment]
Nothing happened over a long time, so i'll close the PR.

**Pull request closed without merging**
