### PR TITLE
Fix for the streams closing issue reported by Fortify

### PR DESCRIPTION
**Pull request by skkolli**
Signed-off-by: Satish Kolli <satish.kolli@gmail.com>

### CODE REVIEW

**Comment by sjudeng** [comment]
@skkolli Thanks for the contribution. Can you update your title to something more descriptive and reference the issue number in the comments (e.g. "Fixes #...")? Also if you haven't already please follow the instructions in [`CONTRIBUTING.md`](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md) to sign the CLA.

**Comment by skkolli** [comment]
@sjudeng I emailed a signed CLA this morning.

**Comment by mbrukman** [comment]
You're all set from the CLA perspective, @skkolli! Thanks for your patience.

**Comment by mbrukman** [comment]
@skkolli, thanks for the contribution!

Please note that you used the `master` branch on your fork to make this contribution; this is not recommended, you should use a new feature branch per PR, because now your `master` and this repo's `master` have diverged, and you won't be able to cleanly pull.

Please delete your current fork on GitHub, create a new fork, and then clone the new clean fork locally, and for any future contributions, create a separate branch per PR, which you can delete after it is merged.

**Pull request merged**
