### PR TITLE
Issue 674 hadoop jars are missing in janusgraph 0.2.0 distribution 

### LINKED ISSUE #674: hadoop-hdfs jar is missing in janusgraph 0.2.0 distribution
hadoop-hdfs-2.7.2.jar is in the 0.1.0 release distribution, but not in 0.2.0.
Let's find out why and bring it back.

### PR DESCRIPTION
**Pull request by jerryjch**
Fixes #674 
Backport to branch 0.2

Thank you for contributing to JanusGraph.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jerryjch** [comment]
Understood.  That is the general topic and question in the discussion board.
What is your suggestion and steps here?   I am open with experimenting different things here, and see the pros and cons.  (That may benefit the general discussion as well.)  Bear in mind that we will do new dev on master and not all will go into 0.2.

**Comment by sjudeng** [comment]
Here the commit has already gone into master first so there is no longer a choice. Shouldn't the commit sha at least be the same for the commit between the two branches? Going forward I would like to see consensus on which approach to take and have that documented before accepting PRs that intend to be applied to multiple branches.

**Comment by jerryjch** [comment]
Why do you need the commit SHA to be kept the same?  Can you always maintain the same commit SHA through branch merges? 
It is an ideal way to track commits.  Normally the Issue # and PR # are better used to track commits.

**Comment by sjudeng** [comment]
If the commit SHA isn't the same then it would show up as a difference if commit logs were compared between the two branches. Also if 0.2 were merged into master the commit would appear twice.

```
$ git log --author="Jerry"
commit 8c434ff5f5485fad5c744bf581feab2d2264b2f9
Merge: 1578f98c0 7de45fa70
Author: Jerry He <jerryjch@apache.org>
Date:   Fri Nov 3 09:30:39 2017 -0700

    Merge pull request #683 from jerryjch/fix-hadoop-jars
    
    Issue 674 hadoop jars are missing in janusgraph 0.2.0 distribution

commit 27de14127e90c57b04cd16e60aa2a1b38fa11838
Author: Jerry He <jinghe@us.ibm.com>
Date:   Tue Oct 31 12:19:43 2017 -0700

    Issue 674 hadoop jars are missing in janusgraph 0.2.0 distribution

commit 7de45fa708b6dcdb2453a927cb8289fab3f7dfd2
Author: Jerry He <jinghe@us.ibm.com>
Date:   Tue Oct 31 12:19:43 2017 -0700

    Issue 674 hadoop jars are missing in janusgraph 0.2.0 distribution
```

**Comment by pluradj** [comment]
@jerryjch did you cherry pick from master or did you create a separate fix for this PR?

**Comment by jerryjch** [comment]
It was a cherry-pick.

**Comment by sjudeng** [comment]
Reading more it looks like the commit SHA can't be the same when cherry-picking now that master is ahead of the release branch (see https://stackoverflow.com/a/14676852 and https://gist.github.com/masak/2415865). Identical commit SHAs would require branching off 0.2 and then merging the commit into 0.2 and master. So the requested change is not possible here, sorry for the confusion. If we decide to merge 0.2 into master at some point I think we can just live with the duplicate commit.

I think this is another reason to consider switching our commit/branch workflow for bug fixes. Aside from improving consistency across the branches having identical commit SHAs would speed up the review process (e.g. if a commit SHA is identical to a previously approved commit then it can be approved immediately).

**Comment by davidclement90** [comment]
I try to do it (I did not save my PR) with my commit on Issue 661 but I have this extra commit (https://github.com/JanusGraph/janusgraph/commit/c982c4b07528d4afa872dcfc7f53d745ed8b7331) in my PR. Until this commit will not be in master. I think we can not do it. But I think is the best idea.

**Comment by sjudeng** [comment]
Yeah I if we were to merge 0.2 into master it's expected that we'd pick up that commit.

**Pull request merged**
