### PR TITLE
Add TEXTSTRING support for lucene index

### PR DESCRIPTION
**Pull request by VladimirBogomolov**
Signed-off-by: Vladimir Bogomolov <vladimir.bogomoloff@gmail.com>

-----

Resolve Issue #1971
-----

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz  where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### CODE REVIEW

**Comment by FlorianHockmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneCustomAnalyzer.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/JanusGraph/janusgraph/pullRequest?prid=5022368&bid=16554250)

**Comment by porunov** [comment]
@VladimirBogomolov thank you for the PR. Would you mind adding a test which tests a new feature? I.e. `TEXTSTRING`

**Comment by VladimirBogomolov** [comment]
> @VladimirBogomolov thank you for the PR. Would you mind adding a test which tests a new feature? I.e. `TEXTSTRING`

That test already exists.
All index tests enable or disable checks depending on supporting of TEXTSTRING mapping.
`.supportedStringMappings(Mapping.TEXT, Mapping.STRING, Mapping.TEXTSTRING)`

**Comment by VladimirBogomolov** [comment]
I think the test
HBaseSnapshotInputFormatIT.testGeoshapeGetValues
fails not because of my changes

**Comment by porunov** [comment]
@VladimirBogomolov could you please fix conflicts in this PR?

**Comment by FlorianHockmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java  1
         

Complexity decreasing per file
==============================
+ janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneCustomAnalyzer.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/JanusGraph/janusgraph/pullRequest?prid=5022368&bid=16554250)

**Comment by porunov** [comment]
@VladimirBogomolov could you please squash your commits into a single one and rebase against the `master` branch, so that there would be no conflicts?

**Comment by porunov** [comment]
@VladimirBogomolov  you can make:
```
git fetch --all
git rebase upstream/master
// fix conflicts
git rebase --continue
```

currently your PR has conflicts with the master branch, that is why we can't merge it

**Comment by FlorianHockmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java  1
         

Complexity decreasing per file
==============================
+ janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneCustomAnalyzer.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/JanusGraph/janusgraph/pullRequest?prid=5022368&bid=16554250)

**Comment by mbrukman** [comment]
@VladimirBogomolov — instead of merging the `master` branch, please use [`git rebase`][git-rebase] to rebase on `master` and squash the commits into a single one. Note that with the latest changes, the DCO check is also failing now.

[git-rebase]: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by FlorianHockmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java  1
         

Complexity decreasing per file
==============================
+ janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneCustomAnalyzer.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/JanusGraph/janusgraph/pullRequest?prid=5022368&bid=16554250)

**Pull request merged**
