### PR TITLE
Issue 674 hadoop jars are missing in janusgraph 0.2.0 distribution

### LINKED ISSUE #674: hadoop-hdfs jar is missing in janusgraph 0.2.0 distribution
hadoop-hdfs-2.7.2.jar is in the 0.1.0 release distribution, but not in 0.2.0.
Let's find out why and bring it back.

### PR DESCRIPTION
**Pull request by jerryjch**
Fixes #674 

Thank you for contributing to JanusGraph.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jerryjch** [comment]
There is no reason to exclude the hadoop-client from hadoop-gremlin.  I did a 'blame' on this pom file and this is the history why we excluded hadoop-client from hadoop-gremlin:
https://github.com/JanusGraph/janusgraph/commit/92ce7ef48cd65d538fc66f8725a7c8ce7d2ff96f

We need to include it now because we now rely on it for hadoop-gremlin to work.

I am not sure how it worked before, probably with hadoop jars pulling in by other janusgraph components transitively.

**Comment by jerryjch** [comment]
Since we are now using hbase shaded artifacts, it won't pull in the hadoop jars anymore.

**Comment by jerryjch** [comment]
Another way to fix the problem:

https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml#L22
https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-hadoop-parent/janusgraph-hadoop/pom.xml#L22

We need to remove the  `<optional>true</optional>` from these two pom files so that the dependencies will be included.

I tested this approach. It works too.

**Comment by robertdale** [comment]
This adds the following jars back into the dist:
```
hadoop-client-2.7.2.jar
hadoop-hdfs-2.7.2.jar
hadoop-mapreduce-client-app-2.7.2.jar
hadoop-mapreduce-client-common-2.7.2.jar
hadoop-mapreduce-client-core-2.7.2.jar
hadoop-mapreduce-client-jobclient-2.7.2.jar
hadoop-mapreduce-client-shuffle-2.7.2.jar
hadoop-yarn-api-2.7.2.jar
hadoop-yarn-client-2.7.2.jar
hadoop-yarn-common-2.7.2.jar
hadoop-yarn-server-common-2.7.2.jar
```

**Comment by jerryjch** [comment]
Thanks for the reviews.  If there is no more comments, I will commit shortly.
Do we all agree this needs to go to branch 0.2 as well?

**Comment by davidclement90** [comment]
I'm agree

**Pull request merged**
