### PR TITLE
Add sort field for STRING mappings in lucene index

### PR DESCRIPTION
**Pull request by VladimirBogomolov**
Resolve Issue #1396
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by porunov** [comment]
@VladimirBogomolov Thank you for the contribution! Have you sent your CLA to janusgraph-cla googlegroups?

**Comment by VladimirBogomolov** [comment]
Yes, I've sent

**Comment by mad** [comment]
@VladimirBogomolov Can you add sortField for Date type too?

**Comment by porunov** [comment]
@VladimirBogomolov your CLA is almost processed here: https://github.com/JanusGraph/legal/pull/133

Can you please check this message https://github.com/JanusGraph/legal/pull/133#discussion_r268877603?

**Comment by VladimirBogomolov** [comment]
> @VladimirBogomolov Can you add sortField for Date type too?
Yes sure

**Comment by porunov** [comment]
@VladimirBogomolov could you please sign the commit with the correct email?
```
git config user.name "Vladimir Bogomolov"
git config user.email "vladimir.bogomoloff@gmail.com"
git commit --amend -s --reset-author
git push -f
```

**Comment by porunov** [comment]
@VladimirBogomolov looks like you accidentally added two commits from `0.4` branch to your PR. Could you please exclude them?

**Comment by porunov** [comment]
Merging this PR with a lazy consensus

**Comment by porunov** [comment]
@VladimirBogomolov thank you for the contribution! The PR is merged in `0.3` and `master` branches now.

**Pull request merged**
