### PR TITLE
Fixed Titan compatibility if local configuration not set

### LINKED ISSUE #418: Failure to correctly set ids.store-name=titan_ids can corrupt a Titan Cassandra
I've been running into issues while connecting JanusGraph 0.1.2-SNAPSHOT to instances of Cassandra which have graphs previously populated by Titan 1.0.0. Initially things looked to be working fine as JanusGraph could read the data but things began to go wrong when I created a new property with something like the following:

```
JanusGraphManagement mgmt = g.openManagement();
mgmt.makePropertyKey("newProperty").dataType(type).make();
```

The `newProperty` which had a data type of `String` got created fine. However, I later discovered that one of my existing properties which had previously been of type `Long` had now changed to type `String` causing many of our application tests to fail and effectively **the graph within Cassandra was now corrupted**.

After digging around a bit found issue #228 about ID_STORE_NAME table renamed from Titan and thought that must be where I was going wrong. Looking in Cassandra I saw that in addition to the existing `titan_ids` a new `janusgraph_ids` had been created and that confirmed it. But that wasn't the whole story because just adding the following to the configuration when connecting:

```
graph.titan-version=1.0.0
ids.store-name=titan_ids
```

Works fine when connecting to an empty Cassandra, but if you connect to one which had previously been populated by Titan you'll get the following:

```
WARN [2017-07-18 12:03:43,880] [main] o.j.g.c.GraphDatabaseConfiguration -  Local setting ids.store-name=titan_ids (Type: GLOBAL_OFFLINE) is overridden by globally managed value (janusgraph_ids).  Use the ManagementSystem interface instead of the local configuration to control this setting. 

```

The message is questionable because the implicit value of `ids.store-name` in the Cassandra being connected to is actually `titan_ids` so we're not overridding anything. And worse still if you don't notice the message and then go on to change the schema you'll risk corrupting the graph because the changes will to into `janusgraph_ids` instead. I worked around the issue by using the  ManagementSystem interface as the warning suggested:

```
mgmt = g.openManagement();
mgmt.set(ConfigElement.getPath(GraphDatabaseConfiguration.IDS_STORE_NAME), "titan_ids");
mgmt.commit();
```

Even this had its complications as you need to bring down the cluster and connect with just a single JanusGraph / Titan as any other connected instances will prevent the change from being applied.

Raising this as an issue because while the [Upgrading from Titan](https://github.com/JanusGraph/janusgraph/blob/1239aad95a8bb96872303a95f7dedc17056df799/UPGRADE.asc) does mention `ids.store-name` it implies that setting it in the JanusGraph properties file is sufficient which in my experience it was not. Ideally I'd like to see it settable from the properties file, as that link suggests, though perhaps only allowed if `graph.titan-version=x.x.x` has also been set.

### PR DESCRIPTION
**Pull request by rafatuita**
The fixes #418 and #445 might not have taken into account systems that do not have local titan versions. Added a try/catch on that specific check fixes the issue and won't prevent embedded applications to start.

Signed-off-by: Rafael Fernandes <luizrafael@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes? [RF]: it already runs in many different unit tests with Restriction.LOCAL.
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by smcquillan** [comment]
@rafatuita I was able to reproduce by first connecting with the following set in my config:
```
graph.titan-version=1.0.0
```
which was accessible in both the global and local config and was written to Cassandra. Then when I attempted to connect a second time but without ` graph.titan-version=1.0.0` in my config I got the same stack trace. 


However, when I put the code in from this pull request to catch the exception and re-ran it no longer ran following bit of the code
```
overwrite.set(IDS_STORE_NAME, JanusGraphConstants.TITAN_ID_STORE_NAME);
```

To override the ID store back to the Titan default of `titan_ids` and a new ID store created named `janusgraph_ids` was created. This will lead to the type of corruption originally raised in issue #418.

I’m wondering if its best just to remove the setting and checking of the `localTitanConfigured` Boolean entirely and always overwrite the ID store name, because it wasn’t something which you could configure in Titan.

**Comment by smcquillan** [comment]
@pluradj @amcp @jerryjch @sjudeng I did some more testing on this today and I don't think we can fix it with the try /catch block currently being proposed as this will result in the [overwrite](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java#L1398) being missed and a second ID store named `janusgraph_ids` being created in addition to the existing `titan_ids` which is what #418 was intended to fix.

However, as @rafatuita points out we shouldn't force people to always include `titan-version` in their local configuration when its already there in the Global config. I think the fix is therefore just to remove the check for `titan-version` in the local config entirely as I've done on a branch in my fork  [here](https://github.com/JanusGraph/janusgraph/compare/master...smcquillan:titanCompatibleVersionsIsGlobal), I've left the white space to better illustrate what's changed.

This would mean that when `titan-version` is in the global config we'll **always** use `titan_ids` for the key store name. Which given that the key store name was not configurable in Titan I don't think would present a problem.

**Comment by amcp** [comment]
@rafatuita seems like you should update the content of this PR with your [fork](https://github.com/JanusGraph/janusgraph/compare/master...smcquillan:titanCompatibleVersionsIsGlobal) or create a new PR.

**Comment by pluradj** [comment]
Or @smcquillan can submit a PR with the fix proposed from his fork.

**Comment by smcquillan** [comment]
@pluradj @rafatuita Bit tied up with other things this week but unless I hear different I'll look to open an new PR next week from my fork.

**Comment by smcquillan** [comment]
@pluradj @rafatuita raised pull request #977 with the fix from my fork.

**Comment by pluradj** [comment]
Closing in favor of #1005. @rafatuita please refer to Issue #1012 to make sure I captured your intent correctly. Thanks.

**Pull request closed without merging**
