### PR TITLE
upgrade datastax cassandra driver version to 3.3.2 from 3.1.4

### LINKED ISSUE #864: Cassandra driver 3.1.4 is out of date
Hello,

Is it possible to update Cassandra driver to 3.2.0+ (The newest version right now is 3.3.2)? The problem with Cassandra drivers below 3.2.0 is that they are using Guava 19.0 dependency which is out of date. Most libraries which use Guava use Guava 20+. With fixes in the newest versions of Cassandra driver it will be possible to use newer versions of other libraries. I would suggest to update Cassandra driver dependency from 3.1.4 to 3.3.2. 

Best regards,
Alexandr

### PR DESCRIPTION
**Pull request by fbalicchia**
Fixes #864

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by davidclement90** [comment]
Hi,
Do you test your modification over ScyllaDB with the profile scylladb-test ?

**Comment by davidclement90** [comment]
@fbalicchia  — thank you for your contribution!

Please follow the instructions in [`CONTRIBUTING.md`](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md) to sign the CLA.

And can you add the link to the issue in you PR body and and you commit message ?

**Comment by fbalicchia** [comment]
Hi @davidclement90,
Yes I've test janusgraph-cql with scylladb-test profile and its ok for me, that profile is present also in janusgraph-cassandra but upgrade doesn't has impact on that module

**Comment by mbrukman** [comment]
CLA is being finalized in https://github.com/JanusGraph/legal/pull/87 — @sjudeng, if you approve and merge that PR, it will help move forward this PR.

**Comment by mbrukman** [comment]
@fbalicchia — please make sure your commit matches your ICLA exactly; right now, [your PR](https://github.com/JanusGraph/janusgraph/pull/900.patch)'s [commit](https://github.com/JanusGraph/janusgraph/commit/bd5c66a09e274ed6a68d05de8223e9e58917655f.patch) has the following format:

> ```
> From: fbalicchia <fbalicchia@gmail.com>
> ```

whereas you should use your full name here for the CLA for it to match. Please update it per [these instructions](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#configure-your-repo-to-match-the-cla) without creating a new PR.

**Comment by mbrukman** [comment]
@fbalicchia — thanks for making the changes! As you can see, the PR is now CLA-compliant; I will dismiss my review so that it can be merged once @sjudeng's review comments area addressed.

Thanks again for your patience!

**Comment by analytically** [comment]
3.4.0 is out with fixes: https://github.com/datastax/java-driver/tree/3.x/changelog

**Pull request merged**
