### PR TITLE
Update to maven-shade-plugin 3.1.0. 

### LINKED ISSUE #867: IncompatibleClassChangeError opening in-memory graph under Java 9
## Steps to reproduce:

1. Create a project with dependency `org.janusgraph:janusgraph-core:0.2.0`
    - demo project: [janus-icce](https://github.com/dmolesUC3/janus-icce)
2. Under Java 9, run the following code:

```
    JanusGraph graph = JanusGraphFactory.build().set("storage.backend", "inmemory").open();
```

## Expected:

In-memory `JanusGraph` instance is a drop-in replacement for in-memory TinkerGraph (`TinkerGraph.open()`).

## Actual:

```
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception

	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:57)

...

Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent exception while executing backend operation getConfiguration
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:82)

...

Caused by: java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/janusgraph/diskstorage/StaticBuffer. Method lambda$static$0([BII)[B at index 105 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at org.janusgraph.diskstorage.StaticBuffer.<clinit>(StaticBuffer.java:79)
	at org.janusgraph.diskstorage.configuration.backend.KCVSConfiguration$1.call(KCVSConfiguration.java:105)
	at org.janusgraph.diskstorage.configuration.backend.KCVSConfiguration$1.call(KCVSConfiguration.java:100)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:148)
```

(Full stack trace in a [gist here](https://gist.github.com/dmolesUC3/e6cdcbf0bcbcb1ba60678886e2c7f6d6).)

## Environment

OS: mac OS Sierra 10.12.6 (16G1114)

Java: 9.0.1+11

```
$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

### PR DESCRIPTION
**Pull request by dmolesUC3**
Fix #867.

Signed-off-by: David Moles <david.moles@ucop.edu>

### CODE REVIEW

**Comment by jerryjch** [comment]
Unrelated to here, I recently ran into https://issues.apache.org/jira/browse/MSHADE-247
in other work.
Good to upgrade.

**Comment by mbrukman** [comment]
@jerryjch — we should NOT have merged this PR, there's no ICLA or CCLA on file for this contributor.

**Comment by jerryjch** [comment]
Just realize that the CLA is no.

**Comment by mbrukman** [comment]
@jerryjch — I will need to update @janusgraph-bot to block merge of PR when `[cla: no]` is present to avoid this issue in the future. For now, please monitor the tags on the PR, and don't review a PR until it has the `[cla: yes]` tag.

**Comment by jerryjch** [comment]
@mbrukman I just realized it.  Should we 'revert' for now?
@dmolesUC3  Could you please take care of the CLA?

**Comment by mbrukman** [comment]
@jerryjch — that's correct, we have no choice but to revert the PR. I've merged your PR.

@dmolesUC3 — please see https://github.com/janusgraph/legal/ for the details on CLA; it's also documented in https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md

**Comment by jerryjch** [comment]
@mbrukman 
> I will need to update @janusgraph-bot to block merge of PR when [cla: no] is present
Sounds good!  Thanks.

**Comment by dmolesUC3** [comment]
@mbrukman @jerryjch Sorry for the thrash — I saw the technical instructions for signing the DCO, missed the link about signing the CLA till after I'd submitted the pull request. Based on past experience, getting the University of California to sign off on the CLA is likely to be a multi-week bureaucratic nightmare. As noted in my [comments](https://github.com/JanusGraph/janusgraph/issues/867#issuecomment-355646857) on the issue, it's probably better if someone else just makes the fix.

**Comment by mbrukman** [comment]
@dmolesUC3 — sorry to hear that (and I understand where you're coming from). That said, if you (or anyone else at University of California) would like to contribute in the future to JanusGraph, we would still need the CLA, and it looks like it would be a one-time process for all of the UC system of universities? That would be awesome, as it would pave the way to have a lot of folks participate and contribute, e.g., via [Google Summer of Code](https://summerofcode.withgoogle.com/)!

FWIW, the JanusGraph CLA is basically the same as Apache Software Foundation CLA (with `s/Apache Software Foundation/Linux Foundation/` as needed), so the review should be straight-forward if someone wanted to go through the process.

If there are any questions from from University of California, I'm happy to chat with them, or refer them to a lawyer at The Linux Foundation; please let me know if you'd like to pursue that route.

@jerryjch — the re-implementation would have to be done by someone who has not seen or reviewed the PR, which means neither you nor I are eligible to do it, and anyone else has to reimplement it based on the description in the issue itself, without looking at the commits.

**Comment by jerryjch** [comment]
@mbrukman That is tricky. Thanks for pointing it out.

**Pull request merged**
