### PR TITLE
Fix precondition checks

### PR DESCRIPTION
**Pull request by mad**
Avoid string concatenation in runtime

Signed-off-by: Pavel Ershov <owner.mad.epa@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Review by li-boxuan — APPROVED** [review]
LGTM

**Review by rngcntr — CHANGES_REQUESTED** [review]
Simple string concatenation is automatically done by `StringBuilder` in Java. In fact, it looks like string formatting is actually much slower compared to simple string concatenation: [Benchmark](https://kylewbanks.com/blog/java-string-concatenation-vs-stringbuilder-vs-string-format-performance)

**Comment by li-boxuan** [comment]
>  In fact, it looks like string formatting is actually much slower compared to simple string concatenation

Preconditions::checkArgument does not do string formatting unless the condition evaluates to false.

**Comment by rngcntr** [comment]
> Preconditions::checkArgument does not do string formatting unless the condition evaluates to false

Now I see what this is aiming for. Thanks for clarifying.

**Review by rngcntr — APPROVED** [review]

**Pull request merged**
