### PR TITLE
Fix conflicting versions of high-scale-lib

### PR DESCRIPTION
**Pull request by mad**
Fix for #634 
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by FlorianHockmann** [comment]
I just looked into this and was a bit confused at first that you changed the version from 1.1.4 to 1.0.6 which sounds like a downgrade, but 1.0.6 is actually the newer version here because it's based on this more recent fork:
https://github.com/boundary/high-scale-lib
right?

**Comment by mad** [comment]
@FlorianHockmann yes, and has some fixes https://github.com/JanusGraph/janusgraph/issues/634#issuecomment-515027265

**Comment by mad** [comment]
@mbrukman but currently JanusGraph override cassandra high-scale-lib potentially it may cause of errors. 

Do we need audit any transitive libraries? Or only direct included?

**Comment by porunov** [comment]
@mbrukman The library is distributed under MIT license. We don't use the source code of `high-scale-lib-1.0.6` which is available in GitHub. We are using a library from Maven Central which is distributed under the MIT license.
Please, check the license in Maven Central repository instead of checking it in GitHub repository.

https://search.maven.org/artifact/com.boundary/high-scale-lib/1.0.6/jar

**Comment by porunov** [comment]
@mbrukman can your check if your comments are resolved?

**Comment by mad** [comment]
@mbrukman changes request are relevant yet?

**Comment by porunov** [comment]
@mad will you merge it?

**Pull request merged**
