### PR TITLE
Bump TinkerPop from 3.7.0 to 3.7.1 [tp-tests][cql-tests]

### PR DESCRIPTION
**Pull request by li-boxuan**
-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Review by porunov — APPROVED** [review]

**Comment by li-boxuan** [comment]
I have totally forgotten about this. Seems I have to push a new commit to make the CI run again.

**Review by FlorianHockmann — APPROVED** [review]
Shouldn't this be added to the `1.1.0` milestone since its targeting `master`? The backport PR for the `v1.0` can then get the `1.0.1` milestone.

edit: And I think we also need to update the version for the docs here: https://github.com/JanusGraph/janusgraph/blob/master/mkdocs.yml#L99

**Comment by li-boxuan** [comment]
@FlorianHockmann you're right, thanks! Will do a CTR (is that still allowed? if not, I'll create a new PR) to fix the doc, so that we don't have to wait for another full build and waste CI cycles

**Comment by li-boxuan** [comment]
You can tell how much I have already forgotten about JanusGraph development cycle :)

**Comment by janusgraph-automations** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v1.0|[](https://github.com/JanusGraph/janusgraph/pull/4369)|

Note: Successful backport PRs will be merged automatically after passing CI.

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport) and see the [Github Action logs](https://github.com/JanusGraph/janusgraph/actions/runs/8641195111) for details

**Pull request merged**
