### PR TITLE
java doc fix

### PR DESCRIPTION
**Pull request by boliza**
1. change com.tinkerpop to org.apache.tinkerpop
2. remove some comment code

### CODE REVIEW

**Comment by pluradj** [comment]
LGTM, pending [CLA signing](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md).
Thanks for the contribution @boliza !

**Comment by boliza** [comment]
@pluradj I had sign the cla and send to janusgraph-cla@googlegroups.com

**Comment by pluradj** [comment]
@mbrukman has the ICLA been received?

**Comment by mbrukman** [comment]
@pluradj — not yet. If it were, I would add the record of the signature to the `janusgraph/legal` repo and @janusgraph-bot would flip the tags on this PR accordingly.

**Comment by mbrukman** [comment]
@pluradj – the CLA issue has been resolved. You'll have to mark it as approved via the GitHub review system, and then feel free to merge it.

**Pull request merged**
