### PR TITLE
Merge #674, #661 and #503 from 0.2 to master

### PR DESCRIPTION
**Pull request by davidclement90**
Thank you for contributing to JanusGraph.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there an issue associated with this PR? Is it referenced in the commit message?
- [ ] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [ ] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by davidclement90** [comment]
@robertdale @jerryjch I have an issue with this [commit ](https://github.com/JanusGraph/janusgraph/pull/724/commits/91244596e1ad75e7389a4d8f44d528b34073714d), is it not sign by @jerryjch

**Comment by sjudeng** [comment]
@mbrukman This is just a merge from the 0.2 release branch. Can we safely ignore the cla check result here?

**Comment by mbrukman** [comment]
@davidclement90 — please update your GitHub profile to use your full name. Whenever you do a merge commit, GitHub uses the name on your account, which appears to be either blank or set to your username. Thus, while commits you author use your full name (`David Clement`), your merge commits use your username (`davidclement90`) and hence there's a distinction, and hence the `[cla: no]` flag.

We can add your username as your "name" to the CLA config to work around this for past commits (since we can't rewrite past commits); please address this for future commits.

**Comment by mbrukman** [comment]
I submitted a proposed fix for the CLA issue in https://github.com/JanusGraph/legal/pull/76

**Comment by mbrukman** [comment]
Now that we've merged the other PR, according to @janusgraph-bot, you're all set on this PR from the CLA perspective.

**Comment by davidclement90** [comment]
Thanks

**Pull request merged**
