### PR TITLE
Returned to 0.3.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by pluradj**
Signed-off-by: Jason Plurad <pluradj@us.ibm.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [] Is there an issue associated with this PR? Is it referenced in the commit message?
- [] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [X] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [] Have you written and/or updated unit tests to verify your changes?
- [] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [] Have you ensured that format looks appropriate for the output in which it is rendered?
- [] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jerryjch** [comment]
We don't cut a 0.3 branch, and master becomes 0.4-SNAPSHOT?

**Comment by jerryjch** [comment]
Then when is the plan to branch off?   The reason I am asking is that one of the items I am thinking is HBase 2 support.  At some point I will need to upgrade the bundled HBase version to HBase 2, which does not seem to be compatible with HBase 1 server.

**Comment by jerryjch** [comment]
Also is there any reason we need to keep 0.2 live and actively merging?  Can we move up the pointer?

**Comment by pluradj** [comment]
We'd branch `0.3` from `master` when we have a PR that needs to go in for `0.4.0-SNAPSHOT`. If you have that PR ready now, we can create the branch now.

As far as `0.2` continued support, we need to discuss that on `janusgraph-dev` not in this PR.

**Pull request merged**
