### PR TITLE
Merge 0.1 branch

### PR DESCRIPTION
**Pull request by sjudeng**
A number of commits in 0.1 are missing in master. @srosenthal Thanks for catching.

### CODE REVIEW

**Comment by jerryjch** [comment]
Some of the commits are already in master.  e.g. 

> Add Spark/Scala version to version-compat list

> Get rid of the Titan-oriented introduction

Is it possible to do cherry-pick, not a whole-sale merge?
I hope we don't need to do this often in the future.

**Comment by sjudeng** [comment]
What's happened is that the same commits went into 0.1 and master with different SHA-1 hashes. Git merges okay in this case but I agree it's not ideal. The [merge diff](https://github.com/JanusGraph/janusgraph/pull/393/files) looks clean to me but I have no objections if someone wants to cherry pick out commits. I do think we want all the (non-duplicate) commits, including the 0.1.1 release notes and compatibility matrix updates (master was incorrect on this one). 

Incidentally I think we're making a lot of (error prone) work for ourselves with the current process of merging into master and cherry-picking into release branches.

**Comment by srosenthal** [comment]
I'm not a contributor to JanusGraph, just a user, but merging from a release branch to master is totally normal in my experience, and less error-prone than cherry-picking. I don't see any problem with a full merge.

**Comment by mbrukman** [comment]
Looks like the `[cla: no]` label is there because some of the commits are actually merges, and the email used for a web-UI-based merge commit is the account's default email address, which is not always the same one as what's on the CLA. I'll add the relevant emails for @jerryjch and @amcp to clear this up.

**Comment by amcp** [comment]
@sjudeng please rebase.

**Comment by amcp** [comment]
Since we were not religions about cherry picking, is it OK to bite the bullet and squash and merge all these changes? I think it is OK to have a commit in master that refers to a commit range on a different branch without actually adding extra 20+ commits to master.

**Comment by sjudeng** [comment]
I don't think we can merge the commits as we'd lose author attribution. If the merge is not desirable I think the missing commits should be identified/cherry-picked manually. Personally I prefer the approach of merging the release branch into master. It's a little messy this time because of the way we were doing things, but once it's done master will be up-to-date with the release branch and it'll be easier to keep it current going forward.

**Comment by jerryjch** [comment]
By going thru the list, I think only a few are missing in master and are needed.
It will be rare cases in the future where we have to merge commits from branches to master in the future.
Generally, we can continue to discuss the approach we should adopt on the dev list again.

**Comment by sjudeng** [comment]
@jerryjch Sounds good to me. I can leave this open to help evaluate the eventual cherry-pick-based merge request to make sure nothing gets missed.

**Comment by amcp** [comment]
@sjudeng excited to get this in. Are we going to work on the cherry-pick-based merge request next?

**Comment by sjudeng** [comment]
Yes I think @jerryjch is working on that as an alternative to the branch merge here.

**Comment by jerryjch** [comment]
I will work on it.   Is your branch open to push, @sjudeng?  Or I should get another PR?

**Comment by amcp** [comment]
@jerryjch to reduce clutter and to allow comparing commit lists, perhaps you should create a new PR.

**Comment by amcp** [comment]
closing this as the cleaner PR #406 is now merged

**Pull request closed without merging**
