### PR TITLE
Lazy relations test [cql-tests][tp-tests]

### PR DESCRIPTION
**Pull request by ntisseyre**
Making Lazy Load relations by default TRUE to validate the build.

This PR is opened only for testing purposes of the #4343 PR. Do not merge this PR.

### CODE REVIEW

**Comment by li-boxuan** [comment]
Great, I can see the ES tests capture an issue.

**Comment by porunov** [comment]
Really great that you executed this feature across all the test cases and some bugs were discovered.
I see currently some tests failing due to:
```
CQLGraphTest>JanusGraphTest.testPropertyIdAccessInDifferentTransaction:2647 » IllegalState Any lazy load operation is not supported when transaction is already closed.
```

I guess it would make sense to execute also `tp-tests` and extended `cql-tests` for this feature just to ensure that it works as expected. I'm adding `[cql-tests][tp-tests]` to the name of the PR, but you will also need to add the same tags to the end of your commit message to trigger full test cases suit for the next build. Notice, usually it takes 4-5 hours to execute all the TP tests using GitHub Actions.

**Comment by ntisseyre** [comment]
> Really great that you executed this feature across all the test cases and some bugs were discovered. I see currently some tests failing due to:
> 
> ```
> CQLGraphTest>JanusGraphTest.testPropertyIdAccessInDifferentTransaction:2647 » IllegalState Any lazy load operation is not supported when transaction is already closed.
> ```
> 
> I guess it would make sense to execute also `tp-tests` and extended `cql-tests` for this feature just to ensure that it works as expected. I'm adding `[cql-tests][tp-tests]` to the name of the PR, but you will also need to add the same tags to the end of your commit message to trigger full test cases suit for the next build. Notice, usually it takes 4-5 hours to execute all the TP tests using GitHub Actions.

This error `IllegalState Any lazy load operation is not supported when transaction is already closed.` is expected. In the dedicated test, i have overwritten the test:
https://github.com/JanusGraph/janusgraph/pull/4343/files#diff-740376f307b1e8385b2e38e7f1ebc4db4fa235dfb838679209a37ca7b3b7d3f6R41

The idea is that you can't access even the relation ID if it was a lazy load and the transaction is closed because, in some cases, to get the relation id, you also need to deserialize the value before.

**Comment by porunov** [comment]
> > Really great that you executed this feature across all the test cases and some bugs were discovered. I see currently some tests failing due to:
> > ```
> > CQLGraphTest>JanusGraphTest.testPropertyIdAccessInDifferentTransaction:2647 » IllegalState Any lazy load operation is not supported when transaction is already closed.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I guess it would make sense to execute also `tp-tests` and extended `cql-tests` for this feature just to ensure that it works as expected. I'm adding `[cql-tests][tp-tests]` to the name of the PR, but you will also need to add the same tags to the end of your commit message to trigger full test cases suit for the next build. Notice, usually it takes 4-5 hours to execute all the TP tests using GitHub Actions.
> 
> This error `IllegalState Any lazy load operation is not supported when transaction is already closed.` is expected. In the dedicated test, i have overwritten the test: https://github.com/JanusGraph/janusgraph/pull/4343/files#diff-740376f307b1e8385b2e38e7f1ebc4db4fa235dfb838679209a37ca7b3b7d3f6R41
> 
> The idea is that you can't access even the relation ID if it was a lazy load and the transaction is closed because, in some cases, to get the relation id, you also need to deserialize the value before.

Got it. Thank you for explanation. Make sense.

**Comment by porunov** [comment]
Closing this PR as the relative PR ( #4343 ) is now merged.

**Pull request closed without merging**
