### PR TITLE
Implement our own GraphBinary Geoshape serialization

### LINKED ISSUE #2856: Add proper GraphBinary serialization for Geoshapes
**Describe the feature:**
JanusGraph [got basic support for GraphBinary in version 0.6.0](https://docs.janusgraph.org/changelog/#graphbinary-is-now-supported). Unfortunately, it still uses a custom Java based binary serialization format for Geoshapes that is implemented in the Java library `Spatial4j`. This makes it very cumbersome to add support for these GraphBinary types to other languages, like .NET. This serialization is also very bloated. It produces for example a GraphBinary value consisting of 73 bytes for a single `Geoshape.Point` instance that only contains two double values (so the serialized value should only consist of 16 bytes).
This defies the purpose of GraphBinary which is supposed to be language agnostic and result in minimal payloads.

I suggest that we implement GraphBinary serialization of Geoshapes completely by ourselves to stay close to the GraphBinary standard and to make it easy to implement support for GraphBinary in other languages.
While we're doing that, we can also improve the serialization by adding a dedicated GraphBinary type for each Geoshape type (Point, Circle, ...) instead of using just a single Geoshape type for all of them. This would also simplify the serialization.

This will of course be a breaking change but we can probably at least keep support for deserialization of Geoshapes coming from 0.6 drivers in the server.

**Describe a specific use case for the feature:**
Being able to support GraphBinary for JanusGraph in other languages.

### PR DESCRIPTION
**Pull request by FlorianHockmann**
This makes it much easier to support GraphBinary outside of Java. It also reduces the payload size by a factor of 3 to 4 (taken from the examples used in the tests):

| Geoshape type      | Payload size (B) with previous serialization | Payload size (in B) with new serialization | Relation (new / old) |
|--------------------|----------------------------------------------|--------------------------------------------|----------------------|
| Point              | 73                                           | 22                                         | 30.1%                |
| Circle             | 105                                          | 30                                         | 28.6%                |
| Polygon            | 373                                          | 90                                         | 24.1%                |
| GeometryCollection | 633                                          | 164                                        | 25.9%                |

It is unfortunately not possible to add the Geoshape types also directly as GraphBinary types which would simplify the serialization and also reduce the payload size even more as we wouldn't have to serialize the Geoshape GraphBinary type together with the Geoshape type code. This however doesn't work with how Geoshapes are implemented right now in
Java as they are all represented by a single class `Geoshape`. We would need to split this class into different classes for the Geoshape types which seems out of scope for now as we just want to improve the GraphBinary serialization here.

Fixes #2856

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Review by farodin91 — APPROVED** [review]
LGTM! Thank you @FlorianHockmann. 

I discuss with @FlorianHockmann offline about the breaking change. As we just started to support GraphBinary, it should a big issue to introduce a breaking change. 

It could be a good idea to add a hint for 0.6 in the docs that we will introduce a breaking change with 1.0. So people are aware that GraphBinary isn't stable yet.

**Comment by FlorianHockmann** [comment]
> As we just started to support GraphBinary, it should a big issue to introduce a breaking change.

I assume you mean "_not_ a big issue" 😅 

> It could be a good idea to add a hint for 0.6 in the docs that we will introduce a breaking change with 1.0. So people are aware that GraphBinary isn't stable yet.

Good idea, I added a small note there.

**Comment by farodin91** [comment]
Not a big issue is correct. 🙊

**Comment by farodin91** [comment]
We have to cherry pick the note, if this got merged.

**Comment by FlorianHockmann** [comment]
> We have to cherry pick the note, if this got merged.

The problem is that we can only do that after 1.0.0 is released as we would otherwise refer and link to a release that isn't out yet. So, I'm not sure how we should approach this. Maybe we should just not merge it to the 0.6 branch at all and just keep it on master?

**Pull request merged**
