### PR TITLE
Fix Apache license copyright template. [skip ci]

### PR DESCRIPTION
**Pull request by mbrukman**
This line is not supposed to be a specific copyright holder or year;
it's a template line, and should have been transferred as-is from the
Apache 2.0 license, which can be found at
https://www.apache.org/licenses/LICENSE-2.0.txt

-----

@pluradj — should this be applied to the `0.2` branch? or `master`? or all the branches? I noticed there isn't a `0.3` branch for some reason, despite the recent 0.3.x releases...

----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [-] Is there an issue associated with this PR? Is it referenced in the commit message?
- [-] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [-] Have you written and/or updated unit tests to verify your changes?
- [-] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [-] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [-] Have you ensured that format looks appropriate for the output in which it is rendered?
- [x] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by porunov** [comment]
@mbrukman `master` branch is considered to be the latest branch. I.e. `0.3.x` right now.

**Comment by mbrukman** [comment]
@chupman — now that we have the `0.3` branch, should this PR target `0.3` branch or still target the `0.2` branch?

**Comment by chupman** [comment]
We still have one more 0.2 release.  I say just throw it there and I can merge it up later in the week.

**Comment by mbrukman** [comment]
@chupman — OK, done. CLA was upset when I did the massive branch change, but it's happy now that I cherry-picked that one commit onto the `0.2` branch, so we should be OK now.

**Comment by chupman** [comment]
Thanks @mbrukman. I'll try to remember to do a merge tomorrow.

**Pull request merged**
