### PR TITLE
Add possibility to remove stale mixed index entries for given vertices or edges

### PR DESCRIPTION
**Pull request by porunov**
Continuation of #3022

Related to #1099

Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### CODE REVIEW

**Review by li-boxuan — COMMENTED** [review]
Looks good to me! I just have two comments:

1. Can you reword the PR title and the commit message? This PR makes it possible to remove certain (stale) mixed index entries for given elements (vertices & edges). The PR title itself reads like "now users can delete mixed indexes via JG".

2. Maybe I missed it, but do we have test cases where the forceRemoveElementFromMixedIndex would fail? For example, the given vertex is not indexed by the given mixed index. This can be due to: 1) someone already manually deleted the entry from the mixed index backend, 2) that index has a label constraint and the given vertex does not apply, or 3) the given vertex does not contain any property to be indexed under the given index. The latter two cases might be the same intrinsically.

**Comment by porunov** [comment]
> Maybe I missed it, but do we have test cases where the forceRemoveElementFromMixedIndex would fail? For example, the given vertex is not indexed by the given mixed index. This can be due to: 1) someone already manually deleted the entry from the mixed index backend, 2) that index has a label constraint and the given vertex does not apply, or 3) the given vertex does not contain any property to be indexed under the given index. The latter two cases might be the same intrinsically.

I will add some tests to fail, but I'm not sure about the use-cases you suggest here. Explaining the cases below:

> For example, the given vertex is not indexed by the given mixed index.

It feels like an additional validation logic which we can validate and throw in case there is no entry. That said - I don't see much value in such logic. If users really need this validation logic then we can simply create a new method in this tool like `retrieveIndexRecords` which retrieves index records for a given element (possible for mixed indexes only) or `validateRecordExists` which validates that a record exists for a set of vertex id + provided properties (possible both for composite and mixed indexes). That said, this retrieval methods feels like a separate PR and I'm not sure what are the use cases of those methods.
At this moment - if a user tries to remove non-existing entries from the index - we don't throw anything. We just trigger removal of `nothing`.

> someone already manually deleted the entry from the mixed index backend.

For this we need to implement retrieval methods but again, it feels like a separate PR. Not 100% we need that but I guess in some cases some users may find it useful to verify there is a specific record in the index.

> that index has a label constraint and the given vertex does not apply.

This is similar to the above points. That said, if we are not talking about `fail` state but rather additional tests than it makes sense to add tests which remove records from indexes with label constraint. I will try to add such tests for mixed indices in this PR and will try to add more tests for composite indices in another PR.

 > the given vertex does not contain any property to be indexed under the given index.

I guess this case isn't fully valid because the main purpose of this util class is to add possibility to resolve those permanent inconsistency between storage backend and an index backend. Thus, even if the vertex doesn't have any indexed property it still may `had` those properties in the past which resulted in the stale index. 
In case you mean here that there is no index record exists for this id + properties then it's the same as your first use-case.

I will add some tests where I didn't cover a fail logic but not for the use cases you proposed. If you don't agree with any of the statements, let me know. I guess, I could implement verification / retrieval logic in this PR but I would prefer splitting that logic on multiple PRs.

**Comment by li-boxuan** [comment]
> At this moment - if a user tries to remove non-existing entries from the index - we don't throw anything. We just trigger removal of nothing.

That (together with your subsequent points) sounds totally reasonable to me. I was just unsure what the behavior would be. The worst case would be the whole DB crash - but I am glad to hear it would simply be a no-op.

**Comment by porunov** [comment]
@li-boxuan I renamed the commit and the PR title to `Add possibility to remove stale mixed index entries for given vertices or edges`.
I also added 3 additional tests:
`testForceRemoveElementFromMixedIndexShouldFailOnCompositeIndex` - fail test to check that we can't trigger `forceRemoveElementFromMixedIndex` for composite indices (i.e. only mixed indices).
`testForceRemoveElementFromMixedIndexShouldFailOnWrongPropertiesUsed` - fail test to check that we can use only those properties for mixed index records removal which exist in that index. I.e. you can't use properties which are not used in the index.
In this index I also demonstrate that multiple removals of non existent records are fine (they don't do anything other than making a redundant operation). 
Made `testStaleGraphIndexForceRemoveVertex` test parameterized so that it tests index record removal for both index with vertex label constraint and index without vertex label constraint.
Let me know if you think some more tests may be helpful as well.

**Review by li-boxuan — APPROVED** [review]
LGTM 👍

**Pull request merged**
