### PR TITLE
adds ArcadeAnalytics to list of tool

### PR DESCRIPTION
**Pull request by robfrank**
[skip ci] 

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?
- [x] If this PR is a documentation-only change, have you added a `[skip ci]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by FlorianHockmann** [comment]
Apart from the organizational issues @porunov explained, you can probably add ArcadeAnalytics at the first position of the list as it's sorted alphabetically.

**Comment by FlorianHockmann** [comment]
@robfrank: Should we just close this and let a committer add this one line to the README.md or do you plan to get back to this and sign the CLA as well as your commit?

**Comment by robfrank** [comment]
Sounds good to me

**Comment by FlorianHockmann** [comment]
Closing in favor of #1489 as discussed.

**Pull request closed without merging**
