### PR TITLE
Disable smart limit adjustment for count query

### LINKED ISSUE #2042: Do not adjust limit for count() query
For a global count query like `g.V().has("name", "bob").count()`, it is totally unnecessary and very inefficient to have `adjustQueryLimit` enabled, since it leads to several identical queries with progressive limits.

https://github.com/JanusGraph/janusgraph/blob/c01bfea2ce602696163aa50fde9be1cdeea13fc1/janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java#L356-L358

In general, JanusGraph does not have particular optimization for count steps as of now, and it is recommended to use a direct index query if possible. I see there are discussions around this, e.g. https://github.com/JanusGraph/janusgraph/issues/926, https://github.com/JanusGraph/janusgraph/issues/874. Before any of these optimizations are done, it is still valuable to do a small enhancement as this issue states.

### PR DESCRIPTION
**Pull request by li-boxuan**
Closes #2042

-----

I ran the following sample program to test the optimization on my laptop using Cassandra + ES:

```java
public void testMultipleIndexQueryWithHeavyLoad() {
    final PropertyKey name = makeKey("name", String.class);
    final PropertyKey text = makeKey("text", String.class);

    final JanusGraphIndex composite = mgmt.buildIndex("composite", Vertex.class).addKey(name).buildCompositeIndex();
    final JanusGraphIndex mixed = mgmt.buildIndex("mixed", Vertex.class).addKey(text, getTextMapping()).buildMixedIndex(INDEX);
    mixed.name();
    composite.name();
    finishSchema();

    final int numV = 100000;
    final String[] strings = {"houseboat", "humanoid", "differential", "extraordinary"};
    final int modulo = 5;

    for (int i = 0; i < numV; i++) {
        final JanusGraphVertex v = tx.addVertex();
        v.property("name", strings[i % 4]);
        v.property("text", strings[i % 3]);
    }
    tx.commit();

    long startTimeMs;
    long measuredTimeMs;

    for (int noOfSubqueries : Arrays.asList(1, 2)) {
        System.out.println("############################");
        System.out.println("Number of index subqueries is: " + noOfSubqueries);
        long totalTimeMs = 0;
        for (int i = 0; i < 5; i++) {
            GraphTraversalSource g = graph.traversal();
            startTimeMs = System.currentTimeMillis();
            GraphTraversal<Vertex, Vertex> query = g.V().has("name", "houseboat");
            if (noOfSubqueries > 1) query = query.has("text", Text.textContains("houseboat"));
            Long count = query.count().next();
            measuredTimeMs = System.currentTimeMillis() - startTimeMs;
            totalTimeMs += measuredTimeMs;
            System.out.println("search time: " + measuredTimeMs + ", count = " + count);
            g.tx().rollback();
        }
        System.out.println("average time (ms): " + totalTimeMs / 5.0);
    }
}
```

Optimized:

############################
Number of index subqueries is: 1
search time: 476, count = 25000
search time: 257, count = 25000
search time: 213, count = 25000
search time: 236, count = 25000
search time: 138, count = 25000
**average time (ms): 264.0**
############################
Number of index subqueries is: 2
search time: 28961, count = 8334
search time: 23486, count = 8334
search time: 22249, count = 8334
search time: 22687, count = 8334
search time: 22802, count = 8334
**average time (ms): 24037.0**

Original:

############################
Number of index subqueries is: 1
search time: 773, count = 25000
search time: 438, count = 25000
search time: 330, count = 25000
search time: 230, count = 25000
search time: 200, count = 25000
**average time (ms): 394.2**
############################
Number of index subqueries is: 2
search time: 74833, count = 8334
search time: 68750, count = 8334
search time: 68378, count = 8334
search time: 67366, count = 8334
search time: 67688, count = 8334
**average time (ms): 69403.0**

-----

Thank you for contributing to JanusGraph!

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
- [ ] If this PR is a documentation-only change, have you added a `[doc only]`
  tag to the first line of your commit message to avoid spending CPU cycles in
  Travis CI when no code, tests, or build configuration are modified?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by FlorianHockmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStep.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/JanusGraph/janusgraph/pullRequest?prid=5188884&bid=17022968)

**Comment by FlorianHockmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStep.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/JanusGraph/janusgraph/pullRequest?prid=5188884&bid=17022968)

**Comment by li-boxuan** [comment]
> JanusGraph should have a benchmark tooling system so such tests would be helpful.

Is it something that already exists or not? I was expecting some performance test tools (preferably integrated with CI) but didn't find one in JanusGraph. Thus I didn't add my test sample program to the commit.

**Comment by farodin91** [comment]
> Is it something that already exists or not?

Janusgraph doesn't have any default benchmarking that this time.

**Comment by farodin91** [comment]
Merged with lazy consensus.

**Pull request merged**
